### ISSUE TITLE
poster.py:56-59: Implement auth process following the...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#101]
The puzzle `67-d54199f4` from #67 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/18753bcaf060e3cc3712c169ee1c7dbfc926f6b8/poster.py#L56-L59

The puzzle was created by paulodamaso on 01-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `67-d54199f4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#197](https://github.com/timelesslounge/timelessis/issues/197) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#101](https://github.com/timelesslounge/timelessis/issues/101) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#232](https://github.com/timelesslounge/timelessis/issues/232) is still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#233](https://github.com/timelesslounge/timelessis/issues/233).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#232](https://github.com/timelesslounge/timelessis/issues/232), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340) are still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#233](https://github.com/timelesslounge/timelessis/issues/233).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#366](https://github.com/timelesslounge/timelessis/issues/366) are still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#339](https://github.com/timelesslounge/timelessis/issues/339), [#366](https://github.com/timelesslounge/timelessis/issues/366), [#370](https://github.com/timelesslounge/timelessis/issues/370) are still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#340](https://github.com/timelesslounge/timelessis/issues/340).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#370](https://github.com/timelesslounge/timelessis/issues/370) are still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389) are still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388) are still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#444](https://github.com/timelesslounge/timelessis/issues/444) are still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#444](https://github.com/timelesslounge/timelessis/issues/444), [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#444](https://github.com/timelesslounge/timelessis/issues/444), [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#444](https://github.com/timelesslounge/timelessis/issues/444), [#464](https://github.com/timelesslounge/timelessis/issues/464) are still not solved; solved: [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389), [#465](https://github.com/timelesslounge/timelessis/issues/465).
