### ISSUE TITLE
models.py:9-11: Continue implementation of Customer data...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#102]
The puzzle `25-09421710` from #25 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/306db59f86253b13117c3c99d367275de6a2d789/customers/models.py#L9-L11

The puzzle was created by Vatavuk on 01-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@vladarefiev[/z](https://www.0crat.com/u/vladarefiev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vladarefiev** [comment]
@0crat wait for PR - https://github.com/timelesslounge/timelessis/pull/193

**Comment by 0crat** [comment]
> @0crat wait for PR - https://github.com/timelesslounge/timelessis/pull/193 ([here](https://github.com/timelesslounge/timelessis/issues/102#issuecomment-462081918))

@vladarefiev The impediment for [#102](https://github.com/timelesslounge/timelessis/issues/102) was registered successfully by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0pdd** [comment]
The puzzle `25-09421710` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#225](https://github.com/timelesslounge/timelessis/issues/225) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#102](https://github.com/timelesslounge/timelessis/issues/102) is now out of scope

**Comment by ypshenychka** [comment]
@vladarefiev According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details into registered [impediment](https://github.com/timelesslounge/timelessis/issues/102#issuecomment-462081918).

**Comment by vladarefiev** [comment]
@ypshenychka fixed, take a look pls

**Comment by ypshenychka** [comment]
@vladarefiev thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262) are still not solved; solved: [#225](https://github.com/timelesslounge/timelessis/issues/225).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#261](https://github.com/timelesslounge/timelessis/issues/261), [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410) are still not solved; solved: [#225](https://github.com/timelesslounge/timelessis/issues/225), [#262](https://github.com/timelesslounge/timelessis/issues/262).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410) are still not solved; solved: [#225](https://github.com/timelesslounge/timelessis/issues/225), [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#409](https://github.com/timelesslounge/timelessis/issues/409) is still not solved; solved: [#225](https://github.com/timelesslounge/timelessis/issues/225), [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262), [#410](https://github.com/timelesslounge/timelessis/issues/410).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#531](https://github.com/timelesslounge/timelessis/issues/531) is still not solved; solved: [#225](https://github.com/timelesslounge/timelessis/issues/225), [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262), [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410).
