### ISSUE TITLE
models.py:7-9: Create a unit test for TimestampsMixin. We...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#103]
The puzzle `40-ad71f182` from #40 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/0c0654dda188cb0881bf135376cc44ec7bcd872c/models.py#L7-L9

The puzzle was created by Carlos Miranda on 03-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by krzyk** [comment]
@0crat waiting for review of PR #143

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #143  ([here](https://github.com/timelesslounge/timelessis/issues/103#issuecomment-461054413))

@krzyk The impediment for [#103](https://github.com/timelesslounge/timelessis/issues/103) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `40-ad71f182` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#103](https://github.com/timelesslounge/timelessis/issues/103) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
