### ISSUE TITLE
Floor model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#11]
The Floor model represents each fllor that is part of a given Location (as defined in #10).

These are the main attributes: 
- Id
- Location_id
- description

Floors should have its own management pages to list, create, edit and delete them. In the index page it should be possible to sort and filter for every column.

Floor management page should be accessed by the Location page.

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#95](https://github.com/timelesslounge/timelessis/issues/95) are still not solved; solved: [#42](https://github.com/timelesslounge/timelessis/issues/42).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#208](https://github.com/timelesslounge/timelessis/issues/208), [#95](https://github.com/timelesslounge/timelessis/issues/95) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#42](https://github.com/timelesslounge/timelessis/issues/42).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#134](https://github.com/timelesslounge/timelessis/issues/134), [#208](https://github.com/timelesslounge/timelessis/issues/208), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#95](https://github.com/timelesslounge/timelessis/issues/95) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#42](https://github.com/timelesslounge/timelessis/issues/42).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#208](https://github.com/timelesslounge/timelessis/issues/208), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#95](https://github.com/timelesslounge/timelessis/issues/95) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#42](https://github.com/timelesslounge/timelessis/issues/42).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#208](https://github.com/timelesslounge/timelessis/issues/208), [#338](https://github.com/timelesslounge/timelessis/issues/338), [#95](https://github.com/timelesslounge/timelessis/issues/95) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#42](https://github.com/timelesslounge/timelessis/issues/42).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#338](https://github.com/timelesslounge/timelessis/issues/338), [#363](https://github.com/timelesslounge/timelessis/issues/363), [#95](https://github.com/timelesslounge/timelessis/issues/95) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#208](https://github.com/timelesslounge/timelessis/issues/208), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#42](https://github.com/timelesslounge/timelessis/issues/42).

**Comment by 0pdd** [comment]
@emilianodellacasa 6 puzzles [#338](https://github.com/timelesslounge/timelessis/issues/338), [#363](https://github.com/timelesslounge/timelessis/issues/363), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#424](https://github.com/timelesslounge/timelessis/issues/424) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#208](https://github.com/timelesslounge/timelessis/issues/208), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#42](https://github.com/timelesslounge/timelessis/issues/42), [#95](https://github.com/timelesslounge/timelessis/issues/95).

**Comment by 0pdd** [comment]
@emilianodellacasa 6 puzzles [#338](https://github.com/timelesslounge/timelessis/issues/338), [#363](https://github.com/timelesslounge/timelessis/issues/363), [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#424](https://github.com/timelesslounge/timelessis/issues/424), [#483](https://github.com/timelesslounge/timelessis/issues/483) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#208](https://github.com/timelesslounge/timelessis/issues/208), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#42](https://github.com/timelesslounge/timelessis/issues/42), [#95](https://github.com/timelesslounge/timelessis/issues/95).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#338](https://github.com/timelesslounge/timelessis/issues/338), [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#424](https://github.com/timelesslounge/timelessis/issues/424), [#483](https://github.com/timelesslounge/timelessis/issues/483) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#208](https://github.com/timelesslounge/timelessis/issues/208), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#363](https://github.com/timelesslounge/timelessis/issues/363), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#42](https://github.com/timelesslounge/timelessis/issues/42), [#95](https://github.com/timelesslounge/timelessis/issues/95).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#424](https://github.com/timelesslounge/timelessis/issues/424), [#483](https://github.com/timelesslounge/timelessis/issues/483), [#494](https://github.com/timelesslounge/timelessis/issues/494) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#208](https://github.com/timelesslounge/timelessis/issues/208), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#338](https://github.com/timelesslounge/timelessis/issues/338), [#363](https://github.com/timelesslounge/timelessis/issues/363), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#42](https://github.com/timelesslounge/timelessis/issues/42), [#95](https://github.com/timelesslounge/timelessis/issues/95).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#483](https://github.com/timelesslounge/timelessis/issues/483), [#494](https://github.com/timelesslounge/timelessis/issues/494), [#499](https://github.com/timelesslounge/timelessis/issues/499) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#208](https://github.com/timelesslounge/timelessis/issues/208), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#338](https://github.com/timelesslounge/timelessis/issues/338), [#363](https://github.com/timelesslounge/timelessis/issues/363), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#424](https://github.com/timelesslounge/timelessis/issues/424), [#42](https://github.com/timelesslounge/timelessis/issues/42), [#95](https://github.com/timelesslounge/timelessis/issues/95).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#338](https://github.com/timelesslounge/timelessis/issues/338), [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#483](https://github.com/timelesslounge/timelessis/issues/483), [#499](https://github.com/timelesslounge/timelessis/issues/499) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#208](https://github.com/timelesslounge/timelessis/issues/208), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#363](https://github.com/timelesslounge/timelessis/issues/363), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#424](https://github.com/timelesslounge/timelessis/issues/424), [#42](https://github.com/timelesslounge/timelessis/issues/42), [#494](https://github.com/timelesslounge/timelessis/issues/494), [#95](https://github.com/timelesslounge/timelessis/issues/95).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#338](https://github.com/timelesslounge/timelessis/issues/338), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#483](https://github.com/timelesslounge/timelessis/issues/483), [#499](https://github.com/timelesslounge/timelessis/issues/499), [#530](https://github.com/timelesslounge/timelessis/issues/530) are still not solved; solved: [#133](https://github.com/timelesslounge/timelessis/issues/133), [#134](https://github.com/timelesslounge/timelessis/issues/134), [#192](https://github.com/timelesslounge/timelessis/issues/192), [#208](https://github.com/timelesslounge/timelessis/issues/208), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#363](https://github.com/timelesslounge/timelessis/issues/363), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#422](https://github.com/timelesslounge/timelessis/issues/422), [#424](https://github.com/timelesslounge/timelessis/issues/424), [#42](https://github.com/timelesslounge/timelessis/issues/42), [#494](https://github.com/timelesslounge/timelessis/issues/494), [#95](https://github.com/timelesslounge/timelessis/issues/95).
