### ISSUE TITLE
models.py:69-71: Continue implementation for Tables....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#112]
The puzzle `12-0192c409` from #12 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/89e31c8ef6f9fba75afd73b22c5e8fc1a4ee4714/restaurants/models.py#L69-L71

The puzzle was created by Paulo Lobo on 04-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by krzyk** [comment]
@0crat waiting for review of PR #140

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #140  ([here](https://github.com/timelesslounge/timelessis/issues/112#issuecomment-461057775))

@krzyk The impediment for [#112](https://github.com/timelesslounge/timelessis/issues/112) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `12-0192c409` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#169](https://github.com/timelesslounge/timelessis/issues/169), [#170](https://github.com/timelesslounge/timelessis/issues/170) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#112](https://github.com/timelesslounge/timelessis/issues/112) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#170](https://github.com/timelesslounge/timelessis/issues/170), [#214](https://github.com/timelesslounge/timelessis/issues/214) are still not solved; solved: [#169](https://github.com/timelesslounge/timelessis/issues/169).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#170](https://github.com/timelesslounge/timelessis/issues/170), [#214](https://github.com/timelesslounge/timelessis/issues/214), [#234](https://github.com/timelesslounge/timelessis/issues/234) are still not solved; solved: [#169](https://github.com/timelesslounge/timelessis/issues/169).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#170](https://github.com/timelesslounge/timelessis/issues/170), [#214](https://github.com/timelesslounge/timelessis/issues/214), [#381](https://github.com/timelesslounge/timelessis/issues/381) are still not solved; solved: [#169](https://github.com/timelesslounge/timelessis/issues/169), [#234](https://github.com/timelesslounge/timelessis/issues/234).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#381](https://github.com/timelesslounge/timelessis/issues/381) is still not solved; solved: [#169](https://github.com/timelesslounge/timelessis/issues/169), [#170](https://github.com/timelesslounge/timelessis/issues/170), [#214](https://github.com/timelesslounge/timelessis/issues/214), [#234](https://github.com/timelesslounge/timelessis/issues/234).
