### ISSUE TITLE
it_test_poster.py:10-12: Implement auth process for...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#113]
The puzzle `67-1c2a8720` from #67 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/9a3feae4c342ea4eb0bcae9787a32f15d5f103d8/ittests/it_test_poster.py#L10-L12

The puzzle was created by rultor on 04-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by krzyk** [comment]
@0crat waiting for #184 to finish before proceeding

**Comment by 0crat** [comment]
> @0crat waiting for #184 to finish before proceeding ([here](https://github.com/timelesslounge/timelessis/issues/113#issuecomment-462046239))

@krzyk The impediment for [#113](https://github.com/timelesslounge/timelessis/issues/113) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `67-1c2a8720` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#113](https://github.com/timelesslounge/timelessis/issues/113) is now out of scope

**Comment by ypshenychka** [comment]
@krzyk According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed

Please add reference to corresponding PR.

**Comment by krzyk** [comment]
@ypshenychka Actually I didn't do any work for this.

**Comment by ypshenychka** [comment]
@krzyk That's weird... Whey then the puzzle disappeared?

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@krzyk @ypshenychka Problem was that the file containing the puzzle had moved but puzzle not, the issue should be still in scope

**Comment by emilianodellacasa** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/timelesslounge/timelessis/issues/113#issuecomment-463123244))

@emilianodellacasa Job [#113](https://github.com/timelesslounge/timelessis/issues/113) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/timelesslounge/timelessis/issues/113#issuecomment-463123244))

@emilianodellacasa Job [#113](https://github.com/timelesslounge/timelessis/issues/113) is pending quality review, can't start a new order

**Comment by emilianodellacasa** [comment]
@ypshenychka What can we do here? You give a bad quality and I try putting in scope again?

**Comment by krzyk** [comment]
@emilianodellacasa I think bad quality and the new puzzle should be somewhere in new issues

**Comment by emilianodellacasa** [comment]
@krzyk So you are suggesting I close this issue and @ypshenychka give bad quality, then manually inserting the puzzle (I will do that) to open the new issue? I am fine with that

**Comment by ypshenychka** [comment]
@emilianodellacasa It's up to you. But I don't see any other options, as far as this puzzle is pending review, so you can't proceed with reopening it.

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0pdd** [comment]
@0pdd the puzzle [#245](https://github.com/timelesslounge/timelessis/issues/245) is still not solved.

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#113` is not assigned, can't get performer

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
The job [#113](https://github.com/timelesslounge/timelessis/issues/113) is now out of scope

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by krzyk** [comment]
@emilianodellacasa actually issue should be created automatically by pdd

**Comment by emilianodellacasa** [comment]
@krzyk See https://github.com/timelesslounge/timelessis/issues/245

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#245](https://github.com/timelesslounge/timelessis/issues/245) is solved here.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#245](https://github.com/timelesslounge/timelessis/issues/245) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
