### ISSUE TITLE
pg_backup.sh:6-9: Implement restore script for backups...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#114]
The puzzle `47-c02901a9` from #47 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/9a3feae4c342ea4eb0bcae9787a32f15d5f103d8/scripts/backup/pg_backup.sh#L6-L9

The puzzle was created by @rultor on 04-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by krzyk** [comment]
@0crat waiting for review of PR #185

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #185  ([here](https://github.com/timelesslounge/timelessis/issues/114#issuecomment-462046069))

@krzyk The impediment for [#114](https://github.com/timelesslounge/timelessis/issues/114) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `47-c02901a9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#191](https://github.com/timelesslounge/timelessis/issues/191) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#114](https://github.com/timelesslounge/timelessis/issues/114) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#191](https://github.com/timelesslounge/timelessis/issues/191) is solved here.
