### ISSUE TITLE
pg_backup.sh:10-12: Implement google drive account...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#115]
The puzzle `47-f3931a04` from #47 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/9a3feae4c342ea4eb0bcae9787a32f15d5f103d8/scripts/backup/pg_backup.sh#L10-L12

The puzzle was created by @rultor on 04-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat wait busy on other tasks

**Comment by 0crat** [comment]
> @0crat wait busy on other tasks  ([here](https://github.com/timelesslounge/timelessis/issues/115#issuecomment-462085115))

@carlosmiranda The impediment for [#115](https://github.com/timelesslounge/timelessis/issues/115) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@emilianodellacasa See PR #210.

**Comment by 0pdd** [comment]
The puzzle `47-f3931a04` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#224](https://github.com/timelesslounge/timelessis/issues/224) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#115](https://github.com/timelesslounge/timelessis/issues/115) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by lastk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/115#issuecomment-464351001))

@lastk Job `gh:timelesslounge/timelessis#115` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the puzzle [#296](https://github.com/timelesslounge/timelessis/issues/296) is still not solved; solved: [#224](https://github.com/timelesslounge/timelessis/issues/224).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#352](https://github.com/timelesslounge/timelessis/issues/352) is still not solved; solved: [#224](https://github.com/timelesslounge/timelessis/issues/224), [#296](https://github.com/timelesslounge/timelessis/issues/296).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#224](https://github.com/timelesslounge/timelessis/issues/224), [#296](https://github.com/timelesslounge/timelessis/issues/296), [#352](https://github.com/timelesslounge/timelessis/issues/352).
