### ISSUE TITLE
Table model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#12]
The Table model represents the tables that are part of the Location. The Table model should also contain a reference to a Floor model (defined in #11).

These are the main attributes:

- Id
- Table name (unique in the same location);
- floor_id (link to Floor)
- X-axis table coordinate
- Y-axis table coordinate
- Table height
- Table width
- Table status (available / unavailable / removed)
- Max Capacity
- Multi-reservation flag (if a table can fit > 1 reservation)
- PlayStation tag (if a table has a PlayStation)

Tables should have its own management pages to list, create, edit and delete them. In the index page it should be possible to sort and filter for every column.

Table management page should be accessed by the Location and Floor pages.

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#169](https://github.com/timelesslounge/timelessis/issues/169), [#170](https://github.com/timelesslounge/timelessis/issues/170) are still not solved; solved: [#112](https://github.com/timelesslounge/timelessis/issues/112).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#170](https://github.com/timelesslounge/timelessis/issues/170), [#214](https://github.com/timelesslounge/timelessis/issues/214) are still not solved; solved: [#112](https://github.com/timelesslounge/timelessis/issues/112), [#169](https://github.com/timelesslounge/timelessis/issues/169).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#170](https://github.com/timelesslounge/timelessis/issues/170), [#214](https://github.com/timelesslounge/timelessis/issues/214), [#234](https://github.com/timelesslounge/timelessis/issues/234) are still not solved; solved: [#112](https://github.com/timelesslounge/timelessis/issues/112), [#169](https://github.com/timelesslounge/timelessis/issues/169).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#170](https://github.com/timelesslounge/timelessis/issues/170), [#214](https://github.com/timelesslounge/timelessis/issues/214), [#381](https://github.com/timelesslounge/timelessis/issues/381) are still not solved; solved: [#112](https://github.com/timelesslounge/timelessis/issues/112), [#169](https://github.com/timelesslounge/timelessis/issues/169), [#234](https://github.com/timelesslounge/timelessis/issues/234).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#381](https://github.com/timelesslounge/timelessis/issues/381) is still not solved; solved: [#112](https://github.com/timelesslounge/timelessis/issues/112), [#169](https://github.com/timelesslounge/timelessis/issues/169), [#170](https://github.com/timelesslounge/timelessis/issues/170), [#214](https://github.com/timelesslounge/timelessis/issues/214), [#234](https://github.com/timelesslounge/timelessis/issues/234).
