### ISSUE TITLE
views.py:23-25: Continue implementation of view methods...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#123]
The puzzle `87-a64a4a29` from #87 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/73b4517319f7010f360d0b54eeef739849658815/timeless/reservations/views.py#L23-L25

The puzzle was created by Vatavuk on 03-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Vatavuk** [comment]
@0crat wait for #207 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #207 to be merged ([here](https://github.com/timelesslounge/timelessis/issues/123#issuecomment-462459443))

@Vatavuk The impediment for [#123](https://github.com/timelesslounge/timelessis/issues/123) was registered successfully by @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0pdd** [comment]
The puzzle `87-a64a4a29` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#221](https://github.com/timelesslounge/timelessis/issues/221), [#222](https://github.com/timelesslounge/timelessis/issues/222) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#123](https://github.com/timelesslounge/timelessis/issues/123) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#221](https://github.com/timelesslounge/timelessis/issues/221), [#266](https://github.com/timelesslounge/timelessis/issues/266), [#267](https://github.com/timelesslounge/timelessis/issues/267) are still not solved; solved: [#222](https://github.com/timelesslounge/timelessis/issues/222).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#266](https://github.com/timelesslounge/timelessis/issues/266), [#267](https://github.com/timelesslounge/timelessis/issues/267), [#288](https://github.com/timelesslounge/timelessis/issues/288), [#289](https://github.com/timelesslounge/timelessis/issues/289) are still not solved; solved: [#221](https://github.com/timelesslounge/timelessis/issues/221), [#222](https://github.com/timelesslounge/timelessis/issues/222).

**Comment by 0pdd** [comment]
@0pdd 6 puzzles [#266](https://github.com/timelesslounge/timelessis/issues/266), [#267](https://github.com/timelesslounge/timelessis/issues/267), [#288](https://github.com/timelesslounge/timelessis/issues/288), [#447](https://github.com/timelesslounge/timelessis/issues/447), [#448](https://github.com/timelesslounge/timelessis/issues/448), [#449](https://github.com/timelesslounge/timelessis/issues/449) are still not solved; solved: [#221](https://github.com/timelesslounge/timelessis/issues/221), [#222](https://github.com/timelesslounge/timelessis/issues/222), [#289](https://github.com/timelesslounge/timelessis/issues/289).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#266](https://github.com/timelesslounge/timelessis/issues/266), [#267](https://github.com/timelesslounge/timelessis/issues/267), [#288](https://github.com/timelesslounge/timelessis/issues/288), [#447](https://github.com/timelesslounge/timelessis/issues/447), [#448](https://github.com/timelesslounge/timelessis/issues/448) are still not solved; solved: [#221](https://github.com/timelesslounge/timelessis/issues/221), [#222](https://github.com/timelesslounge/timelessis/issues/222), [#289](https://github.com/timelesslounge/timelessis/issues/289), [#449](https://github.com/timelesslounge/timelessis/issues/449).
