### ISSUE TITLE
sms.py:32-34: setup rultor settings to install python 3.6...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#124]
The puzzle `46-eeb69d3e` from #46 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/e59b1d2237e73a90d198d121564ab4fab8347298/timeless/sms.py#L32-L34

The puzzle was created by Vlad Arefev on 05-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `46-eeb69d3e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#124](https://github.com/timelesslounge/timelessis/issues/124) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
