### ISSUE TITLE
sms.py:49-51: handle exceptional cases and maybe write a...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#125]
The puzzle `46-df3761df` from #46 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/e59b1d2237e73a90d198d121564ab4fab8347298/timeless/sms.py#L49-L51

The puzzle was created by Vlad Arefev on 04-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `46-df3761df` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#125](https://github.com/timelesslounge/timelessis/issues/125) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
