### ISSUE TITLE
Table Shape Model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#13]
The Table Shape model represents the shape a Table can have. 

The main attributes are:
- Id
- Description (Unique)
- Picture/Raster
- company_id

Table Shape should have its own management pages to list, create, edit and delete them. In the index page it should be possible to sort and filter for every column.

In this issue, a table_shape_id should be also added to Table model (developed in #12) and managed/viewed.

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#162](https://github.com/timelesslounge/timelessis/issues/162) is still not solved; solved: [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#203](https://github.com/timelesslounge/timelessis/issues/203), [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#203](https://github.com/timelesslounge/timelessis/issues/203), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 8 puzzles [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#203](https://github.com/timelesslounge/timelessis/issues/203), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 8 puzzles [#205](https://github.com/timelesslounge/timelessis/issues/205), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 10 puzzles [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#415](https://github.com/timelesslounge/timelessis/issues/415), [#416](https://github.com/timelesslounge/timelessis/issues/416) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 10 puzzles [#205](https://github.com/timelesslounge/timelessis/issues/205), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#415](https://github.com/timelesslounge/timelessis/issues/415), [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 10 puzzles [#205](https://github.com/timelesslounge/timelessis/issues/205), [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416), [#462](https://github.com/timelesslounge/timelessis/issues/462) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#415](https://github.com/timelesslounge/timelessis/issues/415), [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 9 puzzles [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416), [#462](https://github.com/timelesslounge/timelessis/issues/462) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#415](https://github.com/timelesslounge/timelessis/issues/415), [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 8 puzzles [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416), [#462](https://github.com/timelesslounge/timelessis/issues/462) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#415](https://github.com/timelesslounge/timelessis/issues/415), [#72](https://github.com/timelesslounge/timelessis/issues/72).

**Comment by 0pdd** [comment]
@emilianodellacasa 8 puzzles [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416), [#462](https://github.com/timelesslounge/timelessis/issues/462), [#538](https://github.com/timelesslounge/timelessis/issues/538) are still not solved; solved: [#162](https://github.com/timelesslounge/timelessis/issues/162), [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#415](https://github.com/timelesslounge/timelessis/issues/415), [#72](https://github.com/timelesslounge/timelessis/issues/72).
