### ISSUE TITLE
views.py:2-6: Continue implementing list_locations(),...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#133]
The puzzle `42-a6cc90a9` from #42 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/f053398d36cc63215ea5c7062e4bdfa325a8c851/timeless/restaurants/locations/views.py#L2-L6

The puzzle was created by Carlos Miranda on 03-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `42-a6cc90a9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#208](https://github.com/timelesslounge/timelessis/issues/208) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#133](https://github.com/timelesslounge/timelessis/issues/133) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#363](https://github.com/timelesslounge/timelessis/issues/363) is still not solved; solved: [#208](https://github.com/timelesslounge/timelessis/issues/208).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#208](https://github.com/timelesslounge/timelessis/issues/208), [#363](https://github.com/timelesslounge/timelessis/issues/363).
