### ISSUE TITLE
views.py:7-9: We should create generic logic in other...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#134]
The puzzle `42-ca2a2c0a` from #42 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/f053398d36cc63215ea5c7062e4bdfa325a8c851/timeless/restaurants/locations/views.py#L7-L9

The puzzle was created by Carlos Miranda on 03-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/134#issuecomment-462137347))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#134](https://github.com/timelesslounge/timelessis/issues/134), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#134](https://github.com/timelesslounge/timelessis/issues/134) assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/9fe6eb91-7abb-450c-a76e-e2f28d7c4868); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#134` already assigned to @vladarefiev, can't assign to @vladarefiev

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#134` already assigned to @vladarefiev, can't assign to @vladarefiev

**Comment by 0crat** [comment]
@vladarefiev[/z](https://www.0crat.com/u/vladarefiev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `42-ca2a2c0a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#134](https://github.com/timelesslounge/timelessis/issues/134) is not in the agenda of @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), can't inspect

**Comment by 0crat** [comment]
The job [#134](https://github.com/timelesslounge/timelessis/issues/134) is now out of scope

**Comment by vladarefiev** [comment]
@ypshenychka something went wrong, 0crat didn't mention you.

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/134#issuecomment-464443246))

@ypshenychka This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#134](https://github.com/timelesslounge/timelessis/issues/134) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 19hr
  * @vladarefiev[/z](https://www.0crat.com/u/vladarefiev) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23134%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@vladarefiev According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Some of your commits contain plain text instead of links. Please confirm you'll try to follow this rule next time.

**Comment by vladarefiev** [comment]
@ypshenychka Confirm, this one was made before your last notice.

**Comment by ypshenychka** [comment]
@vladarefiev thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
