### ISSUE TITLE
models.py:7-9: Continue the implementation. Items must...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#141]
The puzzle `15-4d06d88e` from #15 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/b38a7a29e88df7a5225567f962c857fd26046d2f/timeless/items/models.py#L7-L9

The puzzle was created by marceloamadeu on 06-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#141](https://github.com/timelesslounge/timelessis/issues/141) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#141](https://github.com/timelesslounge/timelessis/issues/141) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/2ee6c270-1515-4fa6-8e16-1ede82c65b15); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#141` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by ammaratef45** [comment]
@0crat wait for #142 to be done first (changes are in the same file)

**Comment by 0crat** [comment]
> @0crat wait for #142 to be done first (changes are in the same file) ([here](https://github.com/timelesslounge/timelessis/issues/141#issuecomment-462107513))

@ammaratef45 The impediment for [#141](https://github.com/timelesslounge/timelessis/issues/141) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `15-4d06d88e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#270](https://github.com/timelesslounge/timelessis/issues/270) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#141](https://github.com/timelesslounge/timelessis/issues/141) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#417](https://github.com/timelesslounge/timelessis/issues/417), [#418](https://github.com/timelesslounge/timelessis/issues/418) are still not solved; solved: [#270](https://github.com/timelesslounge/timelessis/issues/270).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#418](https://github.com/timelesslounge/timelessis/issues/418), [#527](https://github.com/timelesslounge/timelessis/issues/527) are still not solved; solved: [#270](https://github.com/timelesslounge/timelessis/issues/270), [#417](https://github.com/timelesslounge/timelessis/issues/417).
