### ISSUE TITLE
models.py:10-12: A new function to assign items to users...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#142]
The puzzle `15-02768d14` from #15 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/b38a7a29e88df7a5225567f962c857fd26046d2f/timeless/items/models.py#L10-L12

The puzzle was created by marceloamadeu on 06-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#142](https://github.com/timelesslounge/timelessis/issues/142) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#142](https://github.com/timelesslounge/timelessis/issues/142) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/0fbf9c96-6e54-46bb-8fe7-d831645c0824); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@emilianodellacasa users here are employees not customers right?

**Comment by emilianodellacasa** [comment]
@ammaratef45 right

**Comment by 0pdd** [comment]
The puzzle `15-02768d14` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#217](https://github.com/timelesslounge/timelessis/issues/217) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#142](https://github.com/timelesslounge/timelessis/issues/142) is now out of scope

**Comment by ypshenychka** [comment]
@ammaratef45 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

[One](https://github.com/timelesslounge/timelessis/pull/194/commits/6fb4cc82f394bfb8e33dcda3d7f2681a08dcabab) of your commits does not contain link to issue. Please confirm you'll try to follow this rule next time.

**Comment by ammaratef45** [comment]
@ypshenychka Confirm.

**Comment by ypshenychka** [comment]
@ammaratef45 thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#318](https://github.com/timelesslounge/timelessis/issues/318) is still not solved; solved: [#217](https://github.com/timelesslounge/timelessis/issues/217).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#217](https://github.com/timelesslounge/timelessis/issues/217), [#318](https://github.com/timelesslounge/timelessis/issues/318).
