### ISSUE TITLE
Add the postgres installation to the ReadMe 

### ISSUE THREAD

**Issue by ammaratef45** [timelesslounge/timelessis#147]
Can we update the readme with the installation of Postgres just before the database setup section?

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#147](https://github.com/timelesslounge/timelessis/issues/147) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#147](https://github.com/timelesslounge/timelessis/issues/147) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/998540bf-0987-4de0-a51d-4741e1d25c63); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vryazanov** [comment]
@emilianodellacasa what do you think if I update the readme and also add docker(docker-compose) support in one PR for this ticket? It will be a way more easier for devs

**Comment by emilianodellacasa** [comment]
@vryazanov Docker will be added in issue #35, for now let's just add instructions on how to install postgres

**Comment by vryazanov** [comment]
@ammaratef45 I've updated readme, please have a look

**Comment by ammaratef45** [comment]
@vryazanov 
I got this error

> Err:7 http://apt.postgresql.org/pub/repos/apt 16.0.4-pgdg/main i386 Packages   
>   404  Not Found [IP: 204.145.124.244 80]
> 

While trying [this ](https://www.godaddy.com/garage/how-to-install-postgresql-on-ubuntu-14-04/)tutorial worked

**Comment by vryazanov** [comment]
@ammaratef45  There should be 
```
sudo deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
```
in your case. Got it, I will create a separate PR and clarify this.

**Comment by ammaratef45** [comment]
@vryazanov Yes that is true,
Thanks 👍

**Comment by vryazanov** [comment]
@ammaratef45 readme is fixed, now  it's clear

**Comment by ammaratef45** [comment]
@vryazanov great work
Should I close the ticket or leave that to @emilianodellacasa ?
I guess the Arc closes tickets not reporters right?

**Comment by emilianodellacasa** [comment]
@ammaratef45 It is the reporter that has to close it

**Comment by ammaratef45** [comment]
@emilianodellacasa Okay, nice

**Comment by 0crat** [comment]
Job was finished in 26 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ammaratef45** [comment]
@0crat quality good

**Comment by 0crat** [comment]
The job [#147](https://github.com/timelesslounge/timelessis/issues/147) is now out of scope

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/timelesslounge/timelessis/issues/147#issuecomment-461929763))

@ammaratef45 You can't do "Complete `QA` review", unless you have one of these roles: `ARC`, `QA`; current roles of @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) are: `DEV`, `REV`

**Comment by ypshenychka** [comment]
@vryazanov According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues 

Some of your commits ([this](https://github.com/timelesslounge/timelessis/pull/151/commits/815de55d08c31c8b1590ba9ca2e8eb798436733b) and [this](https://github.com/timelesslounge/timelessis/pull/151/commits/5977947b47f84e5c52728c1ea68596dfe81444f8)) do not contain link to this issue. Please confirm you'll try to follow this rule next time.

**Comment by vryazanov** [comment]
@ypshenychka confirm

**Comment by ypshenychka** [comment]
@vryazanov thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +35 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
