### ISSUE TITLE
Item model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#15]
The Item model represents an inventory object that can be given to Employees or stored in a Location

These are the main attributes:
- Id
- Name
- Stock Date (Item added to warehouse)
- Comment
- company_id

Items should store its historic data (i.e. XL Shirt was in Location until yesterday, then today John Smith received it) in a separate table, with starting and ending time (if ending is missing, the item is currently in that place).

Companies should have its own management pages to list, create, edit and delete them. In the index page it should be possible to sort and filter for every column. A new function to assign items to users should be developed as well (in User management pages).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#141](https://github.com/timelesslounge/timelessis/issues/141), [#142](https://github.com/timelesslounge/timelessis/issues/142) are still not solved.

**Comment by emilianodellacasa** [comment]
@marceloamadeu Thanks a lot!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#15](https://github.com/timelesslounge/timelessis/issues/15) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#141](https://github.com/timelesslounge/timelessis/issues/141), [#217](https://github.com/timelesslounge/timelessis/issues/217) are still not solved; solved: [#142](https://github.com/timelesslounge/timelessis/issues/142).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#217](https://github.com/timelesslounge/timelessis/issues/217), [#270](https://github.com/timelesslounge/timelessis/issues/270) are still not solved; solved: [#141](https://github.com/timelesslounge/timelessis/issues/141), [#142](https://github.com/timelesslounge/timelessis/issues/142).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#270](https://github.com/timelesslounge/timelessis/issues/270), [#318](https://github.com/timelesslounge/timelessis/issues/318) are still not solved; solved: [#141](https://github.com/timelesslounge/timelessis/issues/141), [#142](https://github.com/timelesslounge/timelessis/issues/142), [#217](https://github.com/timelesslounge/timelessis/issues/217).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#270](https://github.com/timelesslounge/timelessis/issues/270) is still not solved; solved: [#141](https://github.com/timelesslounge/timelessis/issues/141), [#142](https://github.com/timelesslounge/timelessis/issues/142), [#217](https://github.com/timelesslounge/timelessis/issues/217), [#318](https://github.com/timelesslounge/timelessis/issues/318).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#417](https://github.com/timelesslounge/timelessis/issues/417), [#418](https://github.com/timelesslounge/timelessis/issues/418) are still not solved; solved: [#141](https://github.com/timelesslounge/timelessis/issues/141), [#142](https://github.com/timelesslounge/timelessis/issues/142), [#217](https://github.com/timelesslounge/timelessis/issues/217), [#270](https://github.com/timelesslounge/timelessis/issues/270), [#318](https://github.com/timelesslounge/timelessis/issues/318).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#418](https://github.com/timelesslounge/timelessis/issues/418), [#527](https://github.com/timelesslounge/timelessis/issues/527) are still not solved; solved: [#141](https://github.com/timelesslounge/timelessis/issues/141), [#142](https://github.com/timelesslounge/timelessis/issues/142), [#217](https://github.com/timelesslounge/timelessis/issues/217), [#270](https://github.com/timelesslounge/timelessis/issues/270), [#318](https://github.com/timelesslounge/timelessis/issues/318), [#417](https://github.com/timelesslounge/timelessis/issues/417).
