### ISSUE TITLE
Integration tests modules

### ISSUE THREAD

**Issue by Vatavuk** [timelesslounge/timelessis#155]
Currently we have integration tests mixed with unit tests in the same module.
For instance, `test_comments`, `test_locations` etc. use app client and executing http requests on the application. These are basically integration tests, they will soon need to use database as development progresses. There is also `test_employees` file that only tests  `Employee` model without using client. It's a little bit messy, so I suggest to move all those test classes that use app_client to integration package and prefix them with `it`. Also let's move tests from `test_employees` to `test_models`

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#155](https://github.com/timelesslounge/timelessis/issues/155) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#155](https://github.com/timelesslounge/timelessis/issues/155) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/29dd97d4-388f-4fb6-80b3-134e6f021532); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by bkuzmic** [comment]
@Vatavuk Can you close the issue now that PRs are merged?

**Comment by 0crat** [comment]
Job [#155](https://github.com/timelesslounge/timelessis/issues/155) is not in the agenda of @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), can't inspect

**Comment by 0crat** [comment]
The job [#155](https://github.com/timelesslounge/timelessis/issues/155) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/155#issuecomment-464500092))

@ypshenychka This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#155](https://github.com/timelesslounge/timelessis/issues/155) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 5hr
  * @bkuzmic[/z](https://www.0crat.com/u/bkuzmic) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23155%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
