### ISSUE TITLE
views.py:2-6: Continue implementing list(), create(),...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#162]
The puzzle `72-ff413457` from #72 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/d9c473707c1af8ff0ebf45ca038b4fd634774e9f/timeless/restaurants/table_shapes/views.py#L2-L6

The puzzle was created by Krzysztof Krason on 06-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#162](https://github.com/timelesslounge/timelessis/issues/162) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#162](https://github.com/timelesslounge/timelessis/issues/162) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/882d1846-145f-4094-a36a-d5c1fb442730); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vryazanov** [comment]
@0crat wait for #163

**Comment by 0crat** [comment]
> @0crat wait for #163  ([here](https://github.com/timelesslounge/timelessis/issues/162#issuecomment-461892322))

@vryazanov The impediment for [#162](https://github.com/timelesslounge/timelessis/issues/162) was registered successfully by @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0pdd** [comment]
The puzzle `72-ff413457` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#162](https://github.com/timelesslounge/timelessis/issues/162) is now out of scope

**Comment by ypshenychka** [comment]
@vryazanov According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details into registered [impediment](https://github.com/timelesslounge/timelessis/issues/162#issuecomment-461892322).

**Comment by vryazanov** [comment]
@ypshenychka I needed some clarifications before implementing this task, since I had two different options. Correct me pls if I shouldn't have put this task on hold. And I thought zerocrat removes "on hold" status when related task is closed..

**Comment by ypshenychka** [comment]
@vryazanov There's no problem, that you put it on hold. What I'm asking is you to add this explanation into your comment about impediment. It can be any reasonable explanation, why would you need more time (e.g. wait for PR to be merged\review etc., wait because I need more clarifications and so on).

**Comment by vryazanov** [comment]
@ypshenychka thx. I've updated the comment

**Comment by ypshenychka** [comment]
@vryazanov thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260) are still not solved; solved: [#203](https://github.com/timelesslounge/timelessis/issues/203).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286) are still not solved; solved: [#203](https://github.com/timelesslounge/timelessis/issues/203), [#206](https://github.com/timelesslounge/timelessis/issues/206).

**Comment by 0pdd** [comment]
@0pdd 8 puzzles [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317) are still not solved; solved: [#203](https://github.com/timelesslounge/timelessis/issues/203), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260).

**Comment by 0pdd** [comment]
@0pdd 8 puzzles [#205](https://github.com/timelesslounge/timelessis/issues/205), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354) are still not solved; solved: [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260).

**Comment by 0pdd** [comment]
@0pdd 10 puzzles [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#415](https://github.com/timelesslounge/timelessis/issues/415), [#416](https://github.com/timelesslounge/timelessis/issues/416) are still not solved; solved: [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260).

**Comment by 0pdd** [comment]
@0pdd 10 puzzles [#205](https://github.com/timelesslounge/timelessis/issues/205), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416) are still not solved; solved: [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#415](https://github.com/timelesslounge/timelessis/issues/415).

**Comment by 0pdd** [comment]
@0pdd 10 puzzles [#205](https://github.com/timelesslounge/timelessis/issues/205), [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416), [#462](https://github.com/timelesslounge/timelessis/issues/462) are still not solved; solved: [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#415](https://github.com/timelesslounge/timelessis/issues/415).

**Comment by 0pdd** [comment]
@0pdd 9 puzzles [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416), [#462](https://github.com/timelesslounge/timelessis/issues/462) are still not solved; solved: [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#415](https://github.com/timelesslounge/timelessis/issues/415).

**Comment by 0pdd** [comment]
@0pdd 8 puzzles [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416), [#462](https://github.com/timelesslounge/timelessis/issues/462) are still not solved; solved: [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#415](https://github.com/timelesslounge/timelessis/issues/415).

**Comment by 0pdd** [comment]
@0pdd 8 puzzles [#286](https://github.com/timelesslounge/timelessis/issues/286), [#314](https://github.com/timelesslounge/timelessis/issues/314), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#354](https://github.com/timelesslounge/timelessis/issues/354), [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416), [#462](https://github.com/timelesslounge/timelessis/issues/462), [#538](https://github.com/timelesslounge/timelessis/issues/538) are still not solved; solved: [#203](https://github.com/timelesslounge/timelessis/issues/203), [#204](https://github.com/timelesslounge/timelessis/issues/204), [#205](https://github.com/timelesslounge/timelessis/issues/205), [#206](https://github.com/timelesslounge/timelessis/issues/206), [#260](https://github.com/timelesslounge/timelessis/issues/260), [#285](https://github.com/timelesslounge/timelessis/issues/285), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#415](https://github.com/timelesslounge/timelessis/issues/415).
