### ISSUE TITLE
Interaction between frontend and backend

### ISSUE THREAD

**Issue by vryazanov** [timelesslounge/timelessis#163]
I've received a puzzle where a need to implement creating and editing models from DB..
So my questions is:
What's the way of interaction between frontend and backend? I mean, I need to implement processing form data or ajax request with json?
I know that we are going to use React, but at the same time I see lots of templates.

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@vryazanov we will use html templates for common crud operations and react for more complex pages

**Comment by vryazanov** [comment]
@emilianodellacasa then I will use http://flask.pocoo.org/docs/0.12/patterns/wtforms/. is it fine?

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#163` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
