### ISSUE TITLE
Flask and pylint integration

### ISSUE THREAD

**Issue by vryazanov** [timelesslounge/timelessis#168]
I started to implement views (CRUD operations for models) and noticed that `Pylint` doesn't see methods of session instance from SQL Alchemy. So for me It means that I cannot pass linters successfully.
I see the following errors:
```
timeless/restaurants/table_shapes/views.py:37:8: E1101: Instance of 'scoped_session' has no 'add' member (no-member)
timeless/restaurants/table_shapes/views.py:38:8: E1101: Instance of 'scoped_session' has no 'commit' member (no-member)
timeless/restaurants/table_shapes/views.py:66:4: E1101: Instance of 'scoped_session' has no 'delete' member (no-member)
```
Solution is to setup `Pylint-flask` extension.
See https://stackoverflow.com/questions/28193025/pylint-cant-find-sqlalchemy-query-member for details.

FYI pull request which has been affected: https://github.com/timelesslounge/timelessis/pull/166

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@vryazanov We should also remove this in pylint config file 
 https://github.com/timelesslounge/timelessis/blob/e0f7561b2702cb938620f35970b029d673b22f62/pylintrc#L264

**Comment by 0crat** [comment]
Job [#168](https://github.com/timelesslounge/timelessis/issues/168) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0crat** [comment]
The job [#168](https://github.com/timelesslounge/timelessis/issues/168) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/41ff9fe2-1d27-499f-bbda-11c1c2cf0a88); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@vryazanov @emilianodellacasa The proposed solution doesn't fix problem with SQLAlchemy, it sitll fails with e.g.:
```
Instance of 'SQLAlchemy' has no 'Column' member (no-member)
```

I also tried pylint_sqlalchemy plugin but it doesn't help either.

**Comment by emilianodellacasa** [comment]
@krzyk Have you tried excluding the "no-member" warning from pylint, as the link suggests?

**Comment by krzyk** [comment]
@emilianodellacasa but excluding no-member is not a great solution, it will mask some errors, so if we need to add something it would be better to exclude specific classes, I'll create PR for that

**Comment by krzyk** [comment]
@0crat waiting for review of PR #364

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #364  ([here](https://github.com/timelesslounge/timelessis/issues/168#issuecomment-466092718))

@krzyk The impediment for [#168](https://github.com/timelesslounge/timelessis/issues/168) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@vryazanov changes have been merged to master in #364 please close this issue

**Comment by vryazanov** [comment]
@krzyk thanks :+1:

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job [#168](https://github.com/timelesslounge/timelessis/issues/168) is not in the agenda of @krzyk[/z](https://www.0crat.com/u/krzyk), can't inspect

**Comment by krzyk** [comment]
@0crat status

**Comment by 0crat** [comment]
The job [#168](https://github.com/timelesslounge/timelessis/issues/168) is now out of scope

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/168#issuecomment-466350591))

@krzyk This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#168](https://github.com/timelesslounge/timelessis/issues/168) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 31min
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will receive 35 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23168%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
