### ISSUE TITLE
views.py:2-7: Continue implementing list_tables(),...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#169]
The puzzle `112-775e8804` from #112 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/6ad83ecd071f581701c7047d674bad78a17acb03/timeless/restaurants/tables/views.py#L2-L7

The puzzle was created by Krzysztof Krason on 06-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#169](https://github.com/timelesslounge/timelessis/issues/169) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#169](https://github.com/timelesslounge/timelessis/issues/169) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/47d580c0-6c39-4617-9686-98c28b23f3ed); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `112-775e8804` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#214](https://github.com/timelesslounge/timelessis/issues/214) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#169](https://github.com/timelesslounge/timelessis/issues/169) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by vryazanov** [comment]
@emilianodellacasa @ypshenychka Hey, I left the puzzle (https://github.com/timelesslounge/timelessis/pull/209/files#diff-765b70aaa2f87f24231ed87164d732e5R2) in PR for this ticket. But looks like 0pdd bot didn't create ticket. Is it a bug in 0ppd or I did something wrong?

**Comment by emilianodellacasa** [comment]
@vryazanov test directory was excluded in theory, I will add it now and I guess with next PR merged it will be taken into consideration

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#214](https://github.com/timelesslounge/timelessis/issues/214), [#234](https://github.com/timelesslounge/timelessis/issues/234) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#214](https://github.com/timelesslounge/timelessis/issues/214), [#381](https://github.com/timelesslounge/timelessis/issues/381) are still not solved; solved: [#234](https://github.com/timelesslounge/timelessis/issues/234).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#381](https://github.com/timelesslounge/timelessis/issues/381) is still not solved; solved: [#214](https://github.com/timelesslounge/timelessis/issues/214), [#234](https://github.com/timelesslounge/timelessis/issues/234).
