### ISSUE TITLE
Scheme Type Model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#17]
Scheme Type model is a special feature of Timeless IS, designed to given more flexibilities to some models.

Essentialy, Scheme Type is a complex data type that can be assigned to any model defined in TimelessIS, allowing certain attributes to have a default value at certain conditions, but this value could change based for example on the day or time of the day.

For example, a Table model could require a given Deposit price during the weekdays and a different one (higher) during weekend.

These are the attributes:

- Id
- Description (Unique)
- Default value (Mandatory)
- ValueType (Can be any type supported by python)
- Sets of conditions (This will be developed issue #18)

SchemeType should have its own management pages to list, create, edit and delete them. In the index page it should be possible to sort and filter for every column.

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#361](https://github.com/timelesslounge/timelessis/issues/361), [#362](https://github.com/timelesslounge/timelessis/issues/362) are still not solved; solved: [#56](https://github.com/timelesslounge/timelessis/issues/56).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#362](https://github.com/timelesslounge/timelessis/issues/362) is still not solved; solved: [#361](https://github.com/timelesslounge/timelessis/issues/361), [#56](https://github.com/timelesslounge/timelessis/issues/56).
