### ISSUE TITLE
views.py:8-10: Modify this file and also all other...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#170]
The puzzle `112-a9b349f8` from #112 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/6ad83ecd071f581701c7047d674bad78a17acb03/timeless/restaurants/tables/views.py#L8-L10

The puzzle was created by Krzysztof Krason on 08-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#170](https://github.com/timelesslounge/timelessis/issues/170) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#170](https://github.com/timelesslounge/timelessis/issues/170) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/a9c6e8b2-560f-4de8-94f7-24cb17893eb1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vryazanov** [comment]
@emilianodellacasa pls validate that this puzzle is correct and check #173. Puzzle creator wants me to make views for SPA, not with templates

**Comment by emilianodellacasa** [comment]
@vryazanov see my response

**Comment by vryazanov** [comment]
@emilianodellacasa this puzzle is still not clear for me. it requires register existing template views like API endpoints (using `register_api`). 
@krzyk pls help me with clarification as well.
We must definitely update README and notify developers what kind of views we expect, template or API endpoints. or both..

**Comment by krzyk** [comment]
@vryazanov This was a resulf of this comment: https://github.com/timelesslounge/timelessis/pull/140#discussion_r254867776 For now as I understand we use template views.

**Comment by vryazanov** [comment]
@emilianodellacasa can we close this one if it's not relevant anymore?

**Comment by 0crat** [comment]
Job was finished in 45 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#170](https://github.com/timelesslounge/timelessis/issues/170) is now out of scope

**Comment by ypshenychka** [comment]
@vryazanov Looks like no work was done in scope of this issue, right?

**Comment by vryazanov** [comment]
@ypshenychka yes, puzzle is a bit out of date

**Comment by ypshenychka** [comment]
@vryazanov got it, thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
