### ISSUE TITLE
models.py:118-120: Calculate reservation duration in...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#171]
The puzzle `27-19ac7d90` from #27 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/375590bcaffa5d4893ae35688faf50655497385a/timeless/restaurants/models.py#L118-L120

The puzzle was created by Vatavuk on 05-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#171](https://github.com/timelesslounge/timelessis/issues/171) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#171](https://github.com/timelesslounge/timelessis/issues/171) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/2fcc005f-fde1-4157-9dcd-76f059c85c19); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@paulodamaso
Why changing what is required in the ticket? the todo was confirmed by the Arc and made for a reason.
You had to discuss this in the ticket first if you are going to change it.

**Comment by 0pdd** [comment]
The puzzle `27-19ac7d90` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 43 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#171](https://github.com/timelesslounge/timelessis/issues/171) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
