### ISSUE TITLE
models.py:121-125: Continue implementation of views....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#172]
The puzzle `27-38242c64` from #27 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/375590bcaffa5d4893ae35688faf50655497385a/timeless/restaurants/models.py#L121-L125

The puzzle was created by Vatavuk on 05-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#172](https://github.com/timelesslounge/timelessis/issues/172) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#172](https://github.com/timelesslounge/timelessis/issues/172) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/b70a7a33-8a8a-487f-9a13-3628ed553578); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@emilianodellacasa 0pdd did not caught my two new puzzles in `test_reservations.py, please take a look

**Comment by paulodamaso** [comment]
@emilianodellacasa Alse please take a look at #219, I've forgot to remove the todo related to this task.

**Comment by 0pdd** [comment]
The puzzle `27-38242c64` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#172](https://github.com/timelesslounge/timelessis/issues/172) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#215](https://github.com/timelesslounge/timelessis/issues/215), [#235](https://github.com/timelesslounge/timelessis/issues/235), [#236](https://github.com/timelesslounge/timelessis/issues/236) are still not solved.

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#215](https://github.com/timelesslounge/timelessis/issues/215), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#379](https://github.com/timelesslounge/timelessis/issues/379), [#380](https://github.com/timelesslounge/timelessis/issues/380) are still not solved; solved: [#235](https://github.com/timelesslounge/timelessis/issues/235).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#215](https://github.com/timelesslounge/timelessis/issues/215), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#379](https://github.com/timelesslounge/timelessis/issues/379), [#434](https://github.com/timelesslounge/timelessis/issues/434) are still not solved; solved: [#235](https://github.com/timelesslounge/timelessis/issues/235), [#380](https://github.com/timelesslounge/timelessis/issues/380).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#215](https://github.com/timelesslounge/timelessis/issues/215), [#379](https://github.com/timelesslounge/timelessis/issues/379), [#434](https://github.com/timelesslounge/timelessis/issues/434) are still not solved; solved: [#235](https://github.com/timelesslounge/timelessis/issues/235), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#380](https://github.com/timelesslounge/timelessis/issues/380).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#379](https://github.com/timelesslounge/timelessis/issues/379), [#434](https://github.com/timelesslounge/timelessis/issues/434), [#484](https://github.com/timelesslounge/timelessis/issues/484) are still not solved; solved: [#215](https://github.com/timelesslounge/timelessis/issues/215), [#235](https://github.com/timelesslounge/timelessis/issues/235), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#380](https://github.com/timelesslounge/timelessis/issues/380).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#379](https://github.com/timelesslounge/timelessis/issues/379), [#484](https://github.com/timelesslounge/timelessis/issues/484), [#492](https://github.com/timelesslounge/timelessis/issues/492) are still not solved; solved: [#215](https://github.com/timelesslounge/timelessis/issues/215), [#235](https://github.com/timelesslounge/timelessis/issues/235), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#380](https://github.com/timelesslounge/timelessis/issues/380), [#434](https://github.com/timelesslounge/timelessis/issues/434).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#379](https://github.com/timelesslounge/timelessis/issues/379), [#492](https://github.com/timelesslounge/timelessis/issues/492) are still not solved; solved: [#215](https://github.com/timelesslounge/timelessis/issues/215), [#235](https://github.com/timelesslounge/timelessis/issues/235), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#380](https://github.com/timelesslounge/timelessis/issues/380), [#434](https://github.com/timelesslounge/timelessis/issues/434), [#484](https://github.com/timelesslounge/timelessis/issues/484).
