### ISSUE TITLE
__init__.py:2-5: Implement Administrator access control...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#174]
The puzzle `22-8f1c33a4` from #22 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/ae4c725b13e7afb9f349eb20f55e5a2d22cd4ebb/timeless/access_control/__init__.py#L2-L5

The puzzle was created by Vatavuk on 09-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#174](https://github.com/timelesslounge/timelessis/issues/174) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#174](https://github.com/timelesslounge/timelessis/issues/174) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/1d337243-50a2-406c-a2e0-53b40416c07f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@emilianodellacasa question about Administrator role, you wrote:
```
Administrator

    * Add / Modify / Archive Locations

    * Create / modify / activate / deactivate accounts for all Locationspots Employees

    * View All Employee profiles
```
What does `Archive` mean for locations? Is there/will be an endpoint for that?

And what does `Locationspots Employees` mean? This is different from general `Employees`?

**Comment by emilianodellacasa** [comment]
@krzyk It's an error on the initial documentation, "archive" here should be substituted by "delete"

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@emilianodellacasa what about the second question? :
> And what does `Locationspots Employees` mean? This is different from general `Employees`?

**Comment by emilianodellacasa** [comment]
@krzyk you are right sorry, this is just employee, it's a typo

**Comment by krzyk** [comment]
@0crat waiting for review of PR #277

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #277  ([here](https://github.com/timelesslounge/timelessis/issues/174#issuecomment-464469468))

@krzyk The impediment for [#174](https://github.com/timelesslounge/timelessis/issues/174) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `22-8f1c33a4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#174](https://github.com/timelesslounge/timelessis/issues/174) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
