### ISSUE TITLE
__init__.py:13-16: Implement Location Admin access...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#177]
The puzzle `22-186c8876` from #22 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/ae4c725b13e7afb9f349eb20f55e5a2d22cd4ebb/timeless/access_control/__init__.py#L13-L16

The puzzle was created by Vatavuk on 09-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#177](https://github.com/timelesslounge/timelessis/issues/177) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#177](https://github.com/timelesslounge/timelessis/issues/177) assigned to @blackout314[/z](https://www.0crat.com/u/blackout314), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/95b5ca29-3e2f-436b-92e4-59ac5bc4c93a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@blackout314[/z](https://www.0crat.com/u/blackout314) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @blackout314[/z](https://www.0crat.com/u/blackout314) resigned from [#177](https://github.com/timelesslounge/timelessis/issues/177), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @blackout314[/z](https://www.0crat.com/u/blackout314)

**Comment by 0crat** [comment]
The job [#177](https://github.com/timelesslounge/timelessis/issues/177) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/de3bdbc4-9c88-4705-9c7d-cf87dac02b61); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#177` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@0crat waiting for #377 to be merged

**Comment by 0crat** [comment]
> @0crat waiting for #377 to be merged ([here](https://github.com/timelesslounge/timelessis/issues/177#issuecomment-467167591))

@amihaiemil The impediment for [#177](https://github.com/timelesslounge/timelessis/issues/177) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0pdd** [comment]
The puzzle `22-186c8876` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#425](https://github.com/timelesslounge/timelessis/issues/425) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#177](https://github.com/timelesslounge/timelessis/issues/177) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
