### ISSUE TITLE
SchemeCondition model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#18]
The SchemeCondition model is strictly bound to SchemeType model (developed in #17), representing the conditions at which the default value stored in the SchemeType model can change (see issue #17 for an example).

These are the main attributes:
- Id
- Value
- Priority
- Start Time
- End Time
- Set of weekdays
- Set of month days
- Set of dates

The possibility to create/edit/delete the conditions shall be made inside SchemeType page for consistency.

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#386](https://github.com/timelesslounge/timelessis/issues/386) is still not solved; solved: [#43](https://github.com/timelesslounge/timelessis/issues/43), [#97](https://github.com/timelesslounge/timelessis/issues/97).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#386](https://github.com/timelesslounge/timelessis/issues/386), [#455](https://github.com/timelesslounge/timelessis/issues/455) are still not solved; solved: [#43](https://github.com/timelesslounge/timelessis/issues/43), [#97](https://github.com/timelesslounge/timelessis/issues/97).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#455](https://github.com/timelesslounge/timelessis/issues/455) is still not solved; solved: [#386](https://github.com/timelesslounge/timelessis/issues/386), [#43](https://github.com/timelesslounge/timelessis/issues/43), [#97](https://github.com/timelesslounge/timelessis/issues/97).
