### ISSUE TITLE
owner_privileges.py:17-20: Implement __location_access....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#181]
The puzzle `22-0fe68fd2` from #22 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/ae4c725b13e7afb9f349eb20f55e5a2d22cd4ebb/timeless/access_control/owner_privileges.py#L17-L20

The puzzle was created by Vatavuk on 05-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#181](https://github.com/timelesslounge/timelessis/issues/181) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#181](https://github.com/timelesslounge/timelessis/issues/181) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/792b2888-0224-4104-abec-ac3ea40467c3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@0crat refuse because I am a little tight on time at the moment

**Comment by 0crat** [comment]
> @0crat refuse because I am a little tight on time at the moment ([here](https://github.com/timelesslounge/timelessis/issues/181#issuecomment-464871583))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#181](https://github.com/timelesslounge/timelessis/issues/181), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#181](https://github.com/timelesslounge/timelessis/issues/181) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/7460ece1-9194-4044-bfde-fd12071aef45); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat waiting for review of PR #304

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #304  ([here](https://github.com/timelesslounge/timelessis/issues/181#issuecomment-465149468))

@krzyk The impediment for [#181](https://github.com/timelesslounge/timelessis/issues/181) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `22-0fe68fd2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#329](https://github.com/timelesslounge/timelessis/issues/329) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 34 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job [#181](https://github.com/timelesslounge/timelessis/issues/181) is not in the agenda of @krzyk[/z](https://www.0crat.com/u/krzyk), can't inspect

**Comment by 0crat** [comment]
The job [#181](https://github.com/timelesslounge/timelessis/issues/181) is now out of scope

**Comment by krzyk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/181#issuecomment-465510634))

@krzyk This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#181](https://github.com/timelesslounge/timelessis/issues/181) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 1hr
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will receive 35 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23181%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#358](https://github.com/timelesslounge/timelessis/issues/358) is still not solved; solved: [#329](https://github.com/timelesslounge/timelessis/issues/329).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#526](https://github.com/timelesslounge/timelessis/issues/526) is still not solved; solved: [#329](https://github.com/timelesslounge/timelessis/issues/329), [#358](https://github.com/timelesslounge/timelessis/issues/358).
