### ISSUE TITLE
authorization.py:10-12: Get role from actual user instead...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#182]
The puzzle `22-9d43a2f0` from #22 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/ae4c725b13e7afb9f349eb20f55e5a2d22cd4ebb/timeless/access_control/authorization.py#L10-L12

The puzzle was created by Vatavuk on 05-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#182](https://github.com/timelesslounge/timelessis/issues/182) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#182](https://github.com/timelesslounge/timelessis/issues/182) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/83e576e6-01fd-413f-9f35-e07aad0cd9c9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by bkuzmic** [comment]
@0crat refuse Sorry, busy on other tasks.

**Comment by 0crat** [comment]
> @0crat refuse Sorry, busy on other tasks. ([here](https://github.com/timelesslounge/timelessis/issues/182#issuecomment-464707164))

@bkuzmic The user @bkuzmic[/z](https://www.0crat.com/u/bkuzmic) resigned from [#182](https://github.com/timelesslounge/timelessis/issues/182), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
The job [#182](https://github.com/timelesslounge/timelessis/issues/182) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/3a7f795f-d6ea-4df8-9b7f-422234358a52); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #403 review and merge

**Comment by 0crat** [comment]
> @0crat wait for #403 review and merge ([here](https://github.com/timelesslounge/timelessis/issues/182#issuecomment-467275988))

@paulodamaso The impediment for [#182](https://github.com/timelesslounge/timelessis/issues/182) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `22-9d43a2f0` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#432](https://github.com/timelesslounge/timelessis/issues/432), [#433](https://github.com/timelesslounge/timelessis/issues/433) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#182](https://github.com/timelesslounge/timelessis/issues/182) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#unknown](), [#unknown]() are still not solved.
