### ISSUE TITLE
views.py:13-15: Continue with SecuredView implementation....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#183]
The puzzle `22-e83d9f5c` from #22 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/ae4c725b13e7afb9f349eb20f55e5a2d22cd4ebb/timeless/access_control/views.py#L13-L15

The puzzle was created by Vatavuk on 05-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#183](https://github.com/timelesslounge/timelessis/issues/183) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#183](https://github.com/timelesslounge/timelessis/issues/183) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/78948f1b-a7d9-4d94-ab3c-cae5f9083300); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/183#issuecomment-463626521))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#183](https://github.com/timelesslounge/timelessis/issues/183), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#183](https://github.com/timelesslounge/timelessis/issues/183) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/77731c93-2a43-455c-8544-8ca2455e3691); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by amihaiemil** [comment]
@0crat refuse because I am a little tight on time at the moment

**Comment by 0crat** [comment]
> @0crat refuse because I am a little tight on time at the moment ([here](https://github.com/timelesslounge/timelessis/issues/183#issuecomment-464871655))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#183](https://github.com/timelesslounge/timelessis/issues/183), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#183](https://github.com/timelesslounge/timelessis/issues/183) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/350f3f6f-3cc5-4e41-ad39-45a795eac36e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@0pdd the puzzle [#330](https://github.com/timelesslounge/timelessis/issues/330) is still not solved.

**Comment by 0pdd** [comment]
The puzzle `22-e83d9f5c` has disappeared from the source code, that's why I closed this issue.

**Comment by vryazanov** [comment]
@0crat status

**Comment by 0crat** [comment]
Job was finished in 36 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by vryazanov** [comment]
@ypshenychka looks like something goes wrong. @0pdd didn't mention you %)

**Comment by 0crat** [comment]
Job [#183](https://github.com/timelesslounge/timelessis/issues/183) is not in the agenda of @vryazanov[/z](https://www.0crat.com/u/vryazanov), can't inspect

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/183#issuecomment-465532776))

@vryazanov This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#183](https://github.com/timelesslounge/timelessis/issues/183) is [in scope](http://www.zerocracy.com/policy.html#14) for 11days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @krzyk[/z](https://www.0crat.com/u/krzyk): User was resigned from the ticket
    * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil): User was resigned from the ticket
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 2min
  * @vryazanov[/z](https://www.0crat.com/u/vryazanov) will receive 35 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23183%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#183](https://github.com/timelesslounge/timelessis/issues/183) is now out of scope

**Comment by vryazanov** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/183#issuecomment-465585615))

@vryazanov This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#183](https://github.com/timelesslounge/timelessis/issues/183) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 3hr
  * @vryazanov[/z](https://www.0crat.com/u/vryazanov) will receive 35 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23183%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#330](https://github.com/timelesslounge/timelessis/issues/330) is solved here.
