### ISSUE TITLE
Different integration tests with different frameworks

### ISSUE THREAD

**Issue by krzyk** [timelesslounge/timelessis#184]
We have two integration tests, one is https://github.com/timelesslounge/timelessis/blob/master/tests/integration/it_employees_test.py (uses pytest) and the other https://github.com/timelesslounge/timelessis/blob/master/ittests/it_test_poster.py (uses unittest).
Which way should we write integration tests?
After the decision one of the mentioned tests needs to be migrated to the same location as other and should change the framework.

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by vryazanov** [comment]
by my opinion `unittest` must die. `pytest` is `must have` in python world

**Comment by emilianodellacasa** [comment]
@krzyk of course unit test must die

**Comment by 0crat** [comment]
Job [#184](https://github.com/timelesslounge/timelessis/issues/184) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#184](https://github.com/timelesslounge/timelessis/issues/184) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/b45e2cab-866a-4a1d-8954-a2844908e868); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#184` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by amihaiemil** [comment]
@krzyk PR #189 has been merged, can we close here?

**Comment by krzyk** [comment]
@amihaiemil thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@vryazanov According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/timelesslounge/timelessis/issues/184#issuecomment-462043644) by indicating an addressee in the beginning.

**Comment by vryazanov** [comment]
> @vryazanov According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
> 
> > Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.
> 
> Please correct your [message](https://github.com/timelesslounge/timelessis/issues/184#issuecomment-462043644) by indicating an addressee in the beginning.

@ypshenychka done. sorry for that

**Comment by ypshenychka** [comment]
@vryazanov thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
