### ISSUE TITLE
sync.py:10-13: Implement synchronization between Poster...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#187]
The puzzle `24-ac1cbe1a` from #24 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/6894529ca93af4641713b0dc143f8b5f09c1a7e1/timeless/sync/sync.py#L10-L13

The puzzle was created by rultor on 09-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#187](https://github.com/timelesslounge/timelessis/issues/187) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#187](https://github.com/timelesslounge/timelessis/issues/187) assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/eea67215-2bf7-4802-b2c8-38db47823a39); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vladarefiev** [comment]
@0crat wait for https://github.com/timelesslounge/timelessis/pull/226

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/timelesslounge/timelessis/pull/226 ([here](https://github.com/timelesslounge/timelessis/issues/187#issuecomment-462754748))

@vladarefiev The impediment for [#187](https://github.com/timelesslounge/timelessis/issues/187) was registered successfully by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0pdd** [comment]
The puzzle `24-ac1cbe1a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#342](https://github.com/timelesslounge/timelessis/issues/342), [#343](https://github.com/timelesslounge/timelessis/issues/343), [#344](https://github.com/timelesslounge/timelessis/issues/344), [#345](https://github.com/timelesslounge/timelessis/issues/345) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#187](https://github.com/timelesslounge/timelessis/issues/187) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#342](https://github.com/timelesslounge/timelessis/issues/342), [#343](https://github.com/timelesslounge/timelessis/issues/343), [#344](https://github.com/timelesslounge/timelessis/issues/344), [#376](https://github.com/timelesslounge/timelessis/issues/376) are still not solved; solved: [#345](https://github.com/timelesslounge/timelessis/issues/345).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#343](https://github.com/timelesslounge/timelessis/issues/343), [#344](https://github.com/timelesslounge/timelessis/issues/344), [#376](https://github.com/timelesslounge/timelessis/issues/376) are still not solved; solved: [#342](https://github.com/timelesslounge/timelessis/issues/342), [#345](https://github.com/timelesslounge/timelessis/issues/345).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#344](https://github.com/timelesslounge/timelessis/issues/344), [#376](https://github.com/timelesslounge/timelessis/issues/376), [#453](https://github.com/timelesslounge/timelessis/issues/453) are still not solved; solved: [#342](https://github.com/timelesslounge/timelessis/issues/342), [#343](https://github.com/timelesslounge/timelessis/issues/343), [#345](https://github.com/timelesslounge/timelessis/issues/345).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
