### ISSUE TITLE
Employee is lacking a field for Roles

### ISSUE THREAD

**Issue by amihaiemil** [timelesslounge/timelessis#188]
At the moment [Employee](https://github.com/timelesslounge/timelessis/blob/master/timeless/employees/models.py#L9) doesn't have a Role(s) field, we don't know what roles the person has in the Company.

I found this missing while looking over #181, where basically I need to know if the user (employee) has the owner in the Company that manages the Location in question.

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@amihaiemil I guess you could develop the relationship between employees and roles or leave a puzzle for others to develop

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#188` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
