### ISSUE TITLE
pg_restore.sh:2-3: Add a detailed description to both...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#191]
The puzzle `114-7a54db2f` from #114 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/2ab6bbfef4dba5a246b12b2909abd17e81186289/scripts/backup/pg_restore.sh#L2-L3

The puzzle was created by Krzysztof Krason on 09-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#191](https://github.com/timelesslounge/timelessis/issues/191) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#191](https://github.com/timelesslounge/timelessis/issues/191) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/6482dd5b-76dc-4b83-988d-d0af17bc3c78); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by Vatavuk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/191#issuecomment-462896031))

@Vatavuk The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#191](https://github.com/timelesslounge/timelessis/issues/191), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
The job [#191](https://github.com/timelesslounge/timelessis/issues/191) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/db65d48e-147f-45af-b7f6-25e29cb4e913); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by amihaiemil** [comment]
@emilianodellacasa I'm sorry, I don't know what else to add besides the existing comments (nor do I understand the scripts entirely, to be honest). Each section of the script has a header comment saying what it is and there are also ``echo``s after each important step.

I guess for more information developers need the context (how those scripts work together), which they can find by tracing the tickets graph up to the [initial ticket](https://github.com/timelesslounge/timelessis/issues/47).

If you think more info is needed, try assigning this to @paulodamaso or @krzyk (they wrote those scripts)

**Comment by emilianodellacasa** [comment]
@amihaiemil I think you are right, there is no need to add more information for these scripts

**Comment by krzyk** [comment]
@emilianodellacasa @amihaiemil it would be good to at least remove the todo from the code

**Comment by emilianodellacasa** [comment]
@krzyk You are definitely right, I'll do that manually

**Comment by 0crat** [comment]
Job was finished in 36 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#191](https://github.com/timelesslounge/timelessis/issues/191) is now out of scope

**Comment by ypshenychka** [comment]
@amihaiemil There was no work done in scope of this ticket, right?

**Comment by amihaiemil** [comment]
@ypshenychka right :)

**Comment by ypshenychka** [comment]
@amihaiemil thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
