### ISSUE TITLE
views.py:2-6: Continue implementing list(), create(),...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#192]
The puzzle `95-9eb0bf3b` from #95 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/21c27c86b7bad02c3ec9eddcc543f7def0dbc24f/timeless/roles/views.py#L2-L6

The puzzle was created by Krzysztof Krason on 06-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#192](https://github.com/timelesslounge/timelessis/issues/192) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#192](https://github.com/timelesslounge/timelessis/issues/192) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/9e0156fe-90a8-4b76-abee-21ea6bb92977); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#192` already assigned to @vatavuk, can't assign to @vatavuk

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#192` already assigned to @vatavuk, can't assign to @vatavuk

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#192` already assigned to @vatavuk, can't assign to @vatavuk

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#192` already assigned to @vatavuk, can't assign to @bkuzmic

**Comment by 0pdd** [comment]
The puzzle `95-9eb0bf3b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#255](https://github.com/timelesslounge/timelessis/issues/255) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#192](https://github.com/timelesslounge/timelessis/issues/192) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by Vatavuk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/192#issuecomment-463960021))

@Vatavuk This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#192](https://github.com/timelesslounge/timelessis/issues/192) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23192%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#338](https://github.com/timelesslounge/timelessis/issues/338) is still not solved; solved: [#255](https://github.com/timelesslounge/timelessis/issues/255).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#494](https://github.com/timelesslounge/timelessis/issues/494) is still not solved; solved: [#255](https://github.com/timelesslounge/timelessis/issues/255), [#338](https://github.com/timelesslounge/timelessis/issues/338).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#338](https://github.com/timelesslounge/timelessis/issues/338) is still not solved; solved: [#255](https://github.com/timelesslounge/timelessis/issues/255), [#494](https://github.com/timelesslounge/timelessis/issues/494).
