### ISSUE TITLE
Lint rules following

### ISSUE THREAD

**Issue by ammaratef45** [timelesslounge/timelessis#195]
I wonder if we should fully resolve pylint warnings or not.
Some warnings like (bad white spaces, missing docstring, too-many-locals and line-too-long) are there.
I think we should avoid them and if we have to make one so we should suppress the warning.

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@ammaratef45 The resasoning here is that we have to produce the best code possible. Pylint is not perfect - no tool actually is- but allows to have a simple number that is the score of the quality of the code. 

For the moment, the minimum allowed score is 8 but this will grow as we need to improve the quality of the codebase.

**Comment by ammaratef45** [comment]
@emilianodellacasa I meant we have to force every PR to take care with this,
My PR fails because of score below 8 and most of lint errors are made by other code.

**Comment by emilianodellacasa** [comment]
@ammaratef45 See my comments on your PR - a couple of them are actually yours.

And, if code has been merged, it means that before score was above 8. No mistakes possible.

**Comment by ammaratef45** [comment]
@emilianodellacasa 
Yes, you are right.
Okay then.

**Comment by emilianodellacasa** [comment]
@ammaratef45 Soon we will have other tools to help as as soon as #86 is fixed

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#195` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
