### ISSUE TITLE
api.py:75-79: Implement auth process following the Poster...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#197]
The puzzle `101-4e9718a8` from #101 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/579dfcb6e05b3a72f7ba43dd2632b2e80b24eedc/timeless/poster/api.py#L75-L79

The puzzle was created by Paulo Lobo on 07-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#197](https://github.com/timelesslounge/timelessis/issues/197) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#197](https://github.com/timelesslounge/timelessis/issues/197) assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/0f9b35e5-57e0-4db6-aa0d-53869b7f9268); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `101-4e9718a8` has disappeared from the source code, that's why I closed this issue.

**Comment by vladarefiev** [comment]
@ypshenychka this puzzle is very similar to https://github.com/timelesslounge/timelessis/issues/197
and both were done in this PR https://github.com/timelesslounge/timelessis/pull/249

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#197](https://github.com/timelesslounge/timelessis/issues/197) is now out of scope

**Comment by ypshenychka** [comment]
@vladarefiev According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Your commits contain issue number, not links. Please confirm you'll try to follow this rule next time.

**Comment by vladarefiev** [comment]
@ypshenychka Confirm, my fault

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
