### ISSUE TITLE
auth.py:7-10: The backend should return only error codes...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#201]
The puzzle `59-2d69b226` from #59 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/874c14b8f4c59d1689ed000a0487c0466447c503/timeless/auth/auth.py#L7-L10

The puzzle was created by Vatavuk on 09-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#201](https://github.com/timelesslounge/timelessis/issues/201) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#201](https://github.com/timelesslounge/timelessis/issues/201) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/ad9f366f-a86d-4c82-b0b9-c38a7b22ea8a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for #264 review and merge

**Comment by 0crat** [comment]
> @0crat wait for #264 review and merge ([here](https://github.com/timelesslounge/timelessis/issues/201#issuecomment-463879526))

@paulodamaso The impediment for [#201](https://github.com/timelesslounge/timelessis/issues/201) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `59-2d69b226` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#269](https://github.com/timelesslounge/timelessis/issues/269) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#201](https://github.com/timelesslounge/timelessis/issues/201) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#269](https://github.com/timelesslounge/timelessis/issues/269), [#297](https://github.com/timelesslounge/timelessis/issues/297) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#297](https://github.com/timelesslounge/timelessis/issues/297) is still not solved; solved: [#269](https://github.com/timelesslounge/timelessis/issues/269).
