### ISSUE TITLE
views.py:17-19: Implement ordering and sorting of...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#203]
The puzzle `162-da16af36` from #162 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/fb3009b27a5b3b6d2ece2f8064447a9e1f7e14c7/timeless/restaurants/table_shapes/views.py#L17-L19

The puzzle was created by Vadim Ryazanov on 08-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#203](https://github.com/timelesslounge/timelessis/issues/203) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#203](https://github.com/timelesslounge/timelessis/issues/203) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/0c62524d-d8c2-4143-80d7-76685e4efe15); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `162-da16af36` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#260](https://github.com/timelesslounge/timelessis/issues/260) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#203](https://github.com/timelesslounge/timelessis/issues/203) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317) are still not solved; solved: [#260](https://github.com/timelesslounge/timelessis/issues/260).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#314](https://github.com/timelesslounge/timelessis/issues/314), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317) are still not solved; solved: [#260](https://github.com/timelesslounge/timelessis/issues/260), [#315](https://github.com/timelesslounge/timelessis/issues/315).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#314](https://github.com/timelesslounge/timelessis/issues/314), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#538](https://github.com/timelesslounge/timelessis/issues/538) are still not solved; solved: [#260](https://github.com/timelesslounge/timelessis/issues/260), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316).
