### ISSUE TITLE
views.py:36-38: This form currenly cannot save pictures....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#205]
The puzzle `162-af883d11` from #162 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/fb3009b27a5b3b6d2ece2f8064447a9e1f7e14c7/timeless/restaurants/table_shapes/views.py#L36-L38

The puzzle was created by Vadim Ryazanov on 10-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#205](https://github.com/timelesslounge/timelessis/issues/205) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#205](https://github.com/timelesslounge/timelessis/issues/205) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/dd7483b7-b05a-4e44-9566-28a01f5d3ac1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by bkuzmic** [comment]
@0crat refuse I'm sorry, but I'm busy with other tasks.

**Comment by 0crat** [comment]
> @0crat refuse I'm sorry, but I'm busy with other tasks. ([here](https://github.com/timelesslounge/timelessis/issues/205#issuecomment-465612329))

@bkuzmic The user @bkuzmic[/z](https://www.0crat.com/u/bkuzmic) resigned from [#205](https://github.com/timelesslounge/timelessis/issues/205), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
The job [#205](https://github.com/timelesslounge/timelessis/issues/205) assigned to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/e18c112d-2ed2-4c10-ad3a-1edf0d5f6346); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@ekondrashev[/z](https://www.0crat.com/u/ekondrashev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `162-af883d11` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#414](https://github.com/timelesslounge/timelessis/issues/414), [#415](https://github.com/timelesslounge/timelessis/issues/415), [#416](https://github.com/timelesslounge/timelessis/issues/416) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#205](https://github.com/timelesslounge/timelessis/issues/205) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#414](https://github.com/timelesslounge/timelessis/issues/414), [#416](https://github.com/timelesslounge/timelessis/issues/416) are still not solved; solved: [#415](https://github.com/timelesslounge/timelessis/issues/415).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#567](https://github.com/timelesslounge/timelessis/issues/567), [#unknown]() are still not solved.
