### ISSUE TITLE
views.py:49-51: Implement edit() method of TableShape...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#206]
The puzzle `162-9f769eb8` from #162 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/fb3009b27a5b3b6d2ece2f8064447a9e1f7e14c7/timeless/restaurants/table_shapes/views.py#L49-L51

The puzzle was created by Vadim Ryazanov on 09-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#206](https://github.com/timelesslounge/timelessis/issues/206) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#206](https://github.com/timelesslounge/timelessis/issues/206) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/92e0a6f8-8618-4fe6-82df-d979519df47d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for review of PR #274

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #274  ([here](https://github.com/timelesslounge/timelessis/issues/206#issuecomment-464357436))

@krzyk The impediment for [#206](https://github.com/timelesslounge/timelessis/issues/206) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `162-9f769eb8` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#285](https://github.com/timelesslounge/timelessis/issues/285), [#286](https://github.com/timelesslounge/timelessis/issues/286) are still not solved.

**Comment by 0crat** [comment]
Job [#206](https://github.com/timelesslounge/timelessis/issues/206) is not in the agenda of @krzyk[/z](https://www.0crat.com/u/krzyk), can't inspect

**Comment by 0crat** [comment]
The job [#206](https://github.com/timelesslounge/timelessis/issues/206) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/206#issuecomment-465070728))

@ypshenychka This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#206](https://github.com/timelesslounge/timelessis/issues/206) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 12hr
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23206%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#286](https://github.com/timelesslounge/timelessis/issues/286), [#462](https://github.com/timelesslounge/timelessis/issues/462) are still not solved; solved: [#285](https://github.com/timelesslounge/timelessis/issues/285).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
