### ISSUE TITLE
views.py:2-7: Continue implementing list_locations(),...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#208]
The puzzle `133-6fbe419f` from #133 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/6f4bcf867e5434fd60ae7cc511a8499352a57f8f/timeless/restaurants/locations/views.py#L2-L7

The puzzle was created by Paulo Lobo on 09-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#208](https://github.com/timelesslounge/timelessis/issues/208) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#208](https://github.com/timelesslounge/timelessis/issues/208) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/51741de4-b148-475e-ada8-00c6ce9aa891); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by bkuzmic** [comment]
@0crat wait I'm currently busy on other tasks.

**Comment by 0crat** [comment]
> @0crat wait I'm currently busy on other tasks.  ([here](https://github.com/timelesslounge/timelessis/issues/208#issuecomment-465612700))

@bkuzmic The impediment for [#208](https://github.com/timelesslounge/timelessis/issues/208) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0pdd** [comment]
The puzzle `133-6fbe419f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#363](https://github.com/timelesslounge/timelessis/issues/363) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#208](https://github.com/timelesslounge/timelessis/issues/208) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#363](https://github.com/timelesslounge/timelessis/issues/363) is solved here.
