### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#21]
In order to provide fast response to HTTPS requests, we should add to TimlessIS application support for caching using Redis.

It's up to the developer how to implement caching, but the solution provided should be easy and effective.

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/21#issuecomment-461018740))

@carlosmiranda There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@55d69b91-ec34-4bf1-baee-b9c4b56fbdad, thread: AsyncProc-3
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "orders.xml" in "CF9LG1YCA" in 2min: java.util.concurrent.locks.ReentrantLock@62e21b4b[Locked by thread BkParallel-7]
```

[0.40.15](https://github.com/zerocracy/farm): CID: [ac184e98-d54d-4ccc-917d-47cf33aed405](https://www.0crat.com/footprint/CF9LG1YCA/ac184e98-d54d-4ccc-917d-47cf33aed405), Type: "Cancel order"

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/21#issuecomment-461197824))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#21](https://github.com/timelesslounge/timelessis/issues/21), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#21](https://github.com/timelesslounge/timelessis/issues/21) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/12f4c5f3-2d94-4fb6-a694-adaf6b4f35d9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@emilianodellacasa what about adding `__cache__` and `__retrieve__` methods for cachable models?

**Comment by emilianodellacasa** [comment]
@ammaratef45 it's up to you, choose the method you think is the best for the project

**Comment by vryazanov** [comment]
@ammaratef45 do we really need to cache models? I think it's a better to make some code which will cache HTTP methods or templates. It will be easier to invalidate cache and also we get rid of serializing/deserializing models from Redis.

**Comment by ammaratef45** [comment]
@vryazanov I will go for that,
I found templates, @emilianodellacasa is there any requests available yet?

**Comment by emilianodellacasa** [comment]
@ammaratef45 I don't understand what you mean

**Comment by ammaratef45** [comment]
@emilianodellacasa Sorry for confusing you 😅 
I meant HTTP methods.

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#211](https://github.com/timelesslounge/timelessis/issues/211) is still not solved.

**Comment by ammaratef45** [comment]
@emilianodellacasa is it fine?

**Comment by emilianodellacasa** [comment]
@ammaratef45 We can close it, thanks a lot!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#21](https://github.com/timelesslounge/timelessis/issues/21) is now out of scope

**Comment by ypshenychka** [comment]
@ammaratef45 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Some of your commits do not contain link to issue. Please confirm you'll try to follow this rule next time.

**Comment by ammaratef45** [comment]
@ypshenychka Confirm

**Comment by ypshenychka** [comment]
@ammaratef45 thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@emilianodellacasa the only puzzle [#211](https://github.com/timelesslounge/timelessis/issues/211) is solved here.
