### ISSUE TITLE
__init__.py:19-21: Install redis in the docker. Also, Add...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#211]
The puzzle `21-91335e76` from #21 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/0c818ed0a15cbff316f7a041becc31072d474d1e/timeless/__init__.py#L19-L21

The puzzle was created by Ammar Atef on 11-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#211](https://github.com/timelesslounge/timelessis/issues/211) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#211](https://github.com/timelesslounge/timelessis/issues/211) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/70a54438-3da6-4a2c-97b1-5c04b18553ee); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `21-91335e76` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 36 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#211](https://github.com/timelesslounge/timelessis/issues/211) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
