### ISSUE TITLE
Add encrypted secret files

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#213]
Let's add an encrypted secret file (decrypted by rultor at deploy time) cotaining credentials for:

- deploy server;
- postgresql database;
- google drive account;
- redsms;
- poster;

The file will be a JSON file with this structure:

```
{
  "credentials": {
    "server": {
      "staging": {
        "address": "...",
        "username": "...",
        "password": "...",
      },
      "production": {
        "address": "...",
        "username": "...",
        "password": "...",
      }
    }
  }
}
```

**Comment by emilianodellacasa** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Job [#213](https://github.com/timelesslounge/timelessis/issues/213) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/timelesslounge/timelessis/issues/213#issuecomment-462289534))

@emilianodellacasa The job [#213](https://github.com/timelesslounge/timelessis/issues/213) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/b02f8f68-407d-4dd5-91b3-e157b1a775ad); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
Solved in 2070e3e6488387ac9c9878c239bd462faa0683d2

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#213](https://github.com/timelesslounge/timelessis/issues/213) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)
