### ISSUE TITLE
views.py:68-71: Refactor this after the implementation of...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#215]
The puzzle `172-d4bc0248` from #172 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/e981e7dcccd76e828e1574d36ce06e7922eceb1d/timeless/reservations/views.py#L68-L71

The puzzle was created by rultor on 11-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#215](https://github.com/timelesslounge/timelessis/issues/215) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#215](https://github.com/timelesslounge/timelessis/issues/215) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/24bb6ab2-f999-48f3-ab9e-19437378b640); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/215#issuecomment-466394118))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#215](https://github.com/timelesslounge/timelessis/issues/215), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#215](https://github.com/timelesslounge/timelessis/issues/215) assigned to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/b1d82596-a5de-4a2a-820e-82e3917db1b9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@ebercamargo[/z](https://www.0crat.com/u/ebercamargo) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @ebercamargo[/z](https://www.0crat.com/u/ebercamargo) resigned from [#215](https://github.com/timelesslounge/timelessis/issues/215), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by emilianodellacasa** [comment]
@0crat assign @ebercamargo

**Comment by 0crat** [comment]
> @0crat assign @ebercamargo  ([here](https://github.com/timelesslounge/timelessis/issues/215#issuecomment-469373544))

@emilianodellacasa The job [#215](https://github.com/timelesslounge/timelessis/issues/215) assigned to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/557c4d3a-7fd9-413d-a9e3-df63005a1045); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `172-d4bc0248` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#484](https://github.com/timelesslounge/timelessis/issues/484) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 45 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ebercamargo[/z](https://www.0crat.com/u/ebercamargo), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#215](https://github.com/timelesslounge/timelessis/issues/215) is now out of scope

**Comment by ypshenychka** [comment]
@ebercamargo According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Most of your commits don't contain link to issue or contain link to invalid issue. Please confirm you'll try to follow this rule next time.

**Comment by ypshenychka** [comment]
@ebercamargo ping

**Comment by ebercamargo** [comment]
> 
> 
> @ebercamargo According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
> 
> > All commit messages have links to issues
> 
> Most of your commits don't contain link to issue or contain link to invalid issue. Please confirm you'll try to follow this rule next time.

@ypshenychka Understood.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +35 point(s) just awarded to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#484](https://github.com/timelesslounge/timelessis/issues/484) is solved here.
