### ISSUE TITLE
Cache configurations for views

### ISSUE THREAD

**Issue by paulodamaso** [timelesslounge/timelessis#216]
At the moment we have cache being defined in each view of applications, as per #21 . This cache could be global to avoid being declared in each view file. We already have cache definition in `base.html`, but it is set to `6000`. 

Alter the cache definition in `base.html` to `600` and remove all other cache definitions from the view files where it have this same value.

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#216](https://github.com/timelesslounge/timelessis/issues/216) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#216](https://github.com/timelesslounge/timelessis/issues/216) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/84aa6686-d45e-4bd0-a207-3d06709b4c15); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vryazanov** [comment]
@paulodamaso It's done, please have a look and close if have no questions.

**Comment by paulodamaso** [comment]
@vryazanov Great, thanks!

**Comment by 0crat** [comment]
Job was finished in 37 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#216](https://github.com/timelesslounge/timelessis/issues/216) is now out of scope

**Comment by ypshenychka** [comment]
@0crat QUALITY GOOD

**Comment by 0crat** [comment]
> @0crat QUALITY GOOD ([here](https://github.com/timelesslounge/timelessis/issues/216#issuecomment-463172095))

@ypshenychka I didn't understand what is "GOOD"

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
