### ISSUE TITLE
models.py:29-31: Continue implememntation of assining....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#217]
The puzzle `142-43e9175c` from #142 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/8648a1e388fcb0d5a1bb4fa6b1c8ff692e3aa48b/timeless/items/models.py#L29-L31

The puzzle was created by Ammar Atef on 10-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#217](https://github.com/timelesslounge/timelessis/issues/217) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#217](https://github.com/timelesslounge/timelessis/issues/217) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/44a72471-6187-4927-8bbf-6c853e7e353c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait for #263 review and merge

**Comment by 0crat** [comment]
> @0crat wait for #263 review and merge ([here](https://github.com/timelesslounge/timelessis/issues/217#issuecomment-463856945))

@paulodamaso The impediment for [#217](https://github.com/timelesslounge/timelessis/issues/217) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `142-43e9175c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#318](https://github.com/timelesslounge/timelessis/issues/318) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#217](https://github.com/timelesslounge/timelessis/issues/217) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#318](https://github.com/timelesslounge/timelessis/issues/318) is solved here.
