### ISSUE TITLE
views.py:41-43: After CrudView implementation is finished...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#222]
The puzzle `123-ae2bbb0c` from #123 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/4177f7a3eee90eb7b948fb023b4d9436a72cb9a3/timeless/reservations/views.py#L41-L43

The puzzle was created by Vedran Grgo Vatavuk on 11-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#222](https://github.com/timelesslounge/timelessis/issues/222) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#222](https://github.com/timelesslounge/timelessis/issues/222) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/1eff803e-7fac-4433-9e8b-906ac944dfb8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `123-ae2bbb0c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#266](https://github.com/timelesslounge/timelessis/issues/266), [#267](https://github.com/timelesslounge/timelessis/issues/267) are still not solved.

**Comment by 0crat** [comment]
Job [#222](https://github.com/timelesslounge/timelessis/issues/222) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by 0crat** [comment]
The job [#222](https://github.com/timelesslounge/timelessis/issues/222) is now out of scope

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/222#issuecomment-464093564))

@paulodamaso This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#222](https://github.com/timelesslounge/timelessis/issues/222) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 3hr
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23222%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@ypshenychka Looks like 0crat did not warned you, please take a look

**Comment by ypshenychka** [comment]
@paulodamaso thanks!

**Comment by ypshenychka** [comment]
@paulodamaso According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

[One](https://github.com/timelesslounge/timelessis/pull/228/commits/ca52777b3f34fe1f34c588e0b4a81ebc1c7c53e6) of your commits contains link to another issue. Please confirm you'll try to avoid this mistake in future.

**Comment by paulodamaso** [comment]
@ypshenychka I confirm. Just for the record, I'd like to say that I've tried to ammend the comment and change its title, but looks like that github does no overwrite a commit

**Comment by ypshenychka** [comment]
@paulodamaso It seems to be not a very good practice to rename commits, so probably GitHub doesn't allow it on purpose :) Thanks@

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#unknown](), [#unknown]() are still not solved.
