### ISSUE TITLE
pg_restore.sh:4-5: Implement retrieval of database backup...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#224]
The puzzle `115-f221d667` from #115 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/cdc8fc9de88cbefa0cda8a5c8d7bfe0520961ce1/scripts/backup/pg_restore.sh#L4-L5

The puzzle was created by Carlos Miranda on 11-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#224](https://github.com/timelesslounge/timelessis/issues/224) is now in scope, role is `DEV`

**Comment by emilianodellacasa** [comment]
@0crat assign @lastk

**Comment by 0crat** [comment]
> @0crat assign @lastk ([here](https://github.com/timelesslounge/timelessis/issues/224#issuecomment-462677996))

@emilianodellacasa The job [#224](https://github.com/timelesslounge/timelessis/issues/224) assigned to @lastk[/z](https://www.0crat.com/u/lastk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/82de5499-be87-4f53-9a0c-5de9721feabf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
@lastk[/z](https://www.0crat.com/u/lastk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by lastk** [comment]
@0crat refuse

**Comment by lastk** [comment]
sorry, i think i refused in the wrong place. : (

**Comment by 0crat** [comment]
> @0crat refuse  ([here](https://github.com/timelesslounge/timelessis/issues/224#issuecomment-464499666))

@lastk The user @lastk[/z](https://www.0crat.com/u/lastk) resigned from [#224](https://github.com/timelesslounge/timelessis/issues/224), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @lastk[/z](https://www.0crat.com/u/lastk)

**Comment by 0crat** [comment]
The job [#224](https://github.com/timelesslounge/timelessis/issues/224) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/ea2ddddc-e697-43fe-a911-b5c59bf20126); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#224` already assigned to @carlosmiranda, can't assign to @paulodamaso

**Comment by carlosmiranda** [comment]
@emilianodellacasa see PR #282

**Comment by 0pdd** [comment]
The puzzle `115-f221d667` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#296](https://github.com/timelesslounge/timelessis/issues/296) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 36 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#224](https://github.com/timelesslounge/timelessis/issues/224) is now out of scope

**Comment by ypshenychka** [comment]
@lastk  According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job always start with a name of a user they are addressed to

Please correct your [message](https://github.com/timelesslounge/timelessis/issues/224#issuecomment-464499688) by indicating an addressee in the beginning.

**Comment by carlosmiranda** [comment]
@ypshenychka looks like @lastk removed the comment

**Comment by lastk** [comment]
@ypshenychka I removed the comment,  it was irrelevant

**Comment by ypshenychka** [comment]
@lastk thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#352](https://github.com/timelesslounge/timelessis/issues/352) is still not solved; solved: [#296](https://github.com/timelesslounge/timelessis/issues/296).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#296](https://github.com/timelesslounge/timelessis/issues/296), [#352](https://github.com/timelesslounge/timelessis/issues/352).
