### ISSUE TITLE
models.py:9-11: Set up celery to project which will...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#225]
The puzzle `102-39a9b3fe` from #102 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/e0f7561b2702cb938620f35970b029d673b22f62/timeless/customers/models.py#L9-L11

The puzzle was created by Vlad Arefev on 09-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#225](https://github.com/timelesslounge/timelessis/issues/225) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#225](https://github.com/timelesslounge/timelessis/issues/225) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/6b9a872b-1d5e-4a47-b2ec-e6ee958be671); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `102-39a9b3fe` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#225](https://github.com/timelesslounge/timelessis/issues/225) is now out of scope

**Comment by ypshenychka** [comment]
@paulodamaso According to our [QA Rules] http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

[One](https://github.com/timelesslounge/timelessis/pull/226/commits/0dc442ed45fad0d95e9ff1ebd38d184113641793) of your commits contains link to incorrect issue. Please confirm you'll try to avoid this mistake in future.

**Comment by paulodamaso** [comment]
@ypshenychka Confirm,thanks. Did not noticed.

**Comment by ypshenychka** [comment]
@paulodamaso thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#261](https://github.com/timelesslounge/timelessis/issues/261), [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410) are still not solved; solved: [#262](https://github.com/timelesslounge/timelessis/issues/262).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410) are still not solved; solved: [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#409](https://github.com/timelesslounge/timelessis/issues/409) is still not solved; solved: [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262), [#410](https://github.com/timelesslounge/timelessis/issues/410).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#531](https://github.com/timelesslounge/timelessis/issues/531) is still not solved; solved: [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262), [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410).
