### ISSUE TITLE
Poster integration for Location model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#23]
In this first step, we need to synchronize TimelessIs database with an existing database managed by Poster application. The API description can be found at the following address: 

https://dev.joinposter.com/en/docs/api#introduction

In this issue a job will be created to sync data for the Location model, using the appropriate API:

- the job will be run using cron on a daily base;
- a new attribute poster_id will be added to the Location model, to store there the id of the BE in Poster;
- a new attribute synchronized_on will be added to the Location model;
- data coming from Poster has priority upon data stored in our database (for now);
- while solving this issue, take into account that other jobs will be developed for other models in Timeless, so try to develop reusable code;

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157) are still not solved; solved: [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#113](https://github.com/timelesslounge/timelessis/issues/113), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#212](https://github.com/timelesslounge/timelessis/issues/212) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#197](https://github.com/timelesslounge/timelessis/issues/197), [#212](https://github.com/timelesslounge/timelessis/issues/212) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#197](https://github.com/timelesslounge/timelessis/issues/197), [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#113](https://github.com/timelesslounge/timelessis/issues/113), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#197](https://github.com/timelesslounge/timelessis/issues/197), [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#245](https://github.com/timelesslounge/timelessis/issues/245) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#245](https://github.com/timelesslounge/timelessis/issues/245) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#245](https://github.com/timelesslounge/timelessis/issues/245), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#245](https://github.com/timelesslounge/timelessis/issues/245) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#245](https://github.com/timelesslounge/timelessis/issues/245), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#212](https://github.com/timelesslounge/timelessis/issues/212), [#245](https://github.com/timelesslounge/timelessis/issues/245), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#366](https://github.com/timelesslounge/timelessis/issues/366) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#212](https://github.com/timelesslounge/timelessis/issues/212), [#245](https://github.com/timelesslounge/timelessis/issues/245), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#366](https://github.com/timelesslounge/timelessis/issues/366), [#370](https://github.com/timelesslounge/timelessis/issues/370) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#212](https://github.com/timelesslounge/timelessis/issues/212), [#245](https://github.com/timelesslounge/timelessis/issues/245), [#366](https://github.com/timelesslounge/timelessis/issues/366), [#370](https://github.com/timelesslounge/timelessis/issues/370) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 6 puzzles [#212](https://github.com/timelesslounge/timelessis/issues/212), [#245](https://github.com/timelesslounge/timelessis/issues/245), [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#212](https://github.com/timelesslounge/timelessis/issues/212), [#245](https://github.com/timelesslounge/timelessis/issues/245), [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#389](https://github.com/timelesslounge/timelessis/issues/389), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#245](https://github.com/timelesslounge/timelessis/issues/245), [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#444](https://github.com/timelesslounge/timelessis/issues/444) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#389](https://github.com/timelesslounge/timelessis/issues/389), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 6 puzzles [#245](https://github.com/timelesslounge/timelessis/issues/245), [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#444](https://github.com/timelesslounge/timelessis/issues/444), [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#245](https://github.com/timelesslounge/timelessis/issues/245), [#366](https://github.com/timelesslounge/timelessis/issues/366), [#444](https://github.com/timelesslounge/timelessis/issues/444), [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#245](https://github.com/timelesslounge/timelessis/issues/245), [#366](https://github.com/timelesslounge/timelessis/issues/366), [#444](https://github.com/timelesslounge/timelessis/issues/444), [#464](https://github.com/timelesslounge/timelessis/issues/464) are still not solved; solved: [#101](https://github.com/timelesslounge/timelessis/issues/101), [#113](https://github.com/timelesslounge/timelessis/issues/113), [#157](https://github.com/timelesslounge/timelessis/issues/157), [#197](https://github.com/timelesslounge/timelessis/issues/197), [#212](https://github.com/timelesslounge/timelessis/issues/212), [#232](https://github.com/timelesslounge/timelessis/issues/232), [#233](https://github.com/timelesslounge/timelessis/issues/233), [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389), [#465](https://github.com/timelesslounge/timelessis/issues/465), [#66](https://github.com/timelesslounge/timelessis/issues/66), [#67](https://github.com/timelesslounge/timelessis/issues/67), [#88](https://github.com/timelesslounge/timelessis/issues/88).
