### ISSUE TITLE
poster_mock.py:31-36: Poster server mock refactor. To...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#232]
The puzzle `101-590ecdb6` from #101 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/38fe4de0be999c5df48e06f9978d5d71c600566f/tests/poster_mock.py#L31-L36

The puzzle was created by Emiliano Della Casa on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#232](https://github.com/timelesslounge/timelessis/issues/232) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#232](https://github.com/timelesslounge/timelessis/issues/232) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/19be271f-93cd-4df4-84c6-7f5e432bf67b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@emilianodellacasa 
Will we replace all start_server usage and make just an instance of a server mock of a type to be used?
some tests like test_posters need more than one endpoint.

**Comment by emilianodellacasa** [comment]
@ammaratef45 I am not sure I understood your question, could you be clarify?

**Comment by ammaratef45** [comment]
@emilianodellacasa 
We have to make `PosterServerMock` a generic and make `LocationServerMock` extends it (and so on)
So that `LocationServerMock` is going to be used for location endpoints tests.
But tests like `tests/test_posters` uses more than one endpoint pattern (like locations and tables .. etc)
Am I understanding the puzzle correctly?

**Comment by emilianodellacasa** [comment]
@ammaratef45 it is correct, could you please me point me out a test where more than a single endpoint is used?

**Comment by ammaratef45** [comment]
@0crat refuse
@emilianodellacasa sorry didn't figure it out, will watch the solution instead.

**Comment by 0crat** [comment]
> @0crat refuse @emilianodellacasa sorry didn't figure it out, will watch the solution instead. ([here](https://github.com/timelesslounge/timelessis/issues/232#issuecomment-464424260))

@ammaratef45 The user @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) resigned from [#232](https://github.com/timelesslounge/timelessis/issues/232), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
The job [#232](https://github.com/timelesslounge/timelessis/issues/232) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/96361066-6e5d-483e-b143-bd929216b114); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#232` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340) are still not solved.

**Comment by 0pdd** [comment]
The puzzle `101-590ecdb6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#366](https://github.com/timelesslounge/timelessis/issues/366) are still not solved.

**Comment by 0crat** [comment]
Job [#232](https://github.com/timelesslounge/timelessis/issues/232) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by 0crat** [comment]
The job [#232](https://github.com/timelesslounge/timelessis/issues/232) is now out of scope

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/232#issuecomment-466133124))

@paulodamaso This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#232](https://github.com/timelesslounge/timelessis/issues/232) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 1hr
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23232%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@ypshenychka ping, looks like 0crat did not warned you

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#339](https://github.com/timelesslounge/timelessis/issues/339), [#366](https://github.com/timelesslounge/timelessis/issues/366), [#370](https://github.com/timelesslounge/timelessis/issues/370) are still not solved; solved: [#340](https://github.com/timelesslounge/timelessis/issues/340).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#370](https://github.com/timelesslounge/timelessis/issues/370) are still not solved; solved: [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389) are still not solved; solved: [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388) are still not solved; solved: [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#444](https://github.com/timelesslounge/timelessis/issues/444) are still not solved; solved: [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#444](https://github.com/timelesslounge/timelessis/issues/444), [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved; solved: [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#444](https://github.com/timelesslounge/timelessis/issues/444), [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved; solved: [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#366](https://github.com/timelesslounge/timelessis/issues/366), [#444](https://github.com/timelesslounge/timelessis/issues/444), [#464](https://github.com/timelesslounge/timelessis/issues/464) are still not solved; solved: [#339](https://github.com/timelesslounge/timelessis/issues/339), [#340](https://github.com/timelesslounge/timelessis/issues/340), [#370](https://github.com/timelesslounge/timelessis/issues/370), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389), [#465](https://github.com/timelesslounge/timelessis/issues/465).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#unknown](), [#unknown]() are still not solved.
