### ISSUE TITLE
test_auth.py:67-70: Implement other test cases for poster...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#233]
The puzzle `101-e1e35f6e` from #101 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/38fe4de0be999c5df48e06f9978d5d71c600566f/tests/test_auth.py#L67-L70

The puzzle was created by Emiliano Della Casa on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#233](https://github.com/timelesslounge/timelessis/issues/233) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#233](https://github.com/timelesslounge/timelessis/issues/233) assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/461690ed-29d2-463f-894f-cb912ac37208); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `101-e1e35f6e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 38 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#233](https://github.com/timelesslounge/timelessis/issues/233) is now out of scope

**Comment by ypshenychka** [comment]
@vladarefiev According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed

Please add reference to corresponding PR into this issue

**Comment by vladarefiev** [comment]
@ypshenychka corresponding PR - https://github.com/timelesslounge/timelessis/issues/197

**Comment by ypshenychka** [comment]
@vladarefiev To make it as a reference - you should mention this issue number in PR's description. Please do so. Also I don't like this approach, to be honest. Commits also contains only one issue number. I'm not sure we should do like this next time.
@emilianodellacasa What do you think about situation when one PR solves two issues?

**Comment by vladarefiev** [comment]
@ypshenychka done.
@emilianodellacasa I don't like this situation too, but puzzles are intersected. When I was implementing this - https://github.com/timelesslounge/timelessis/issues/197 I needed to fix tests, which actually required in this issue and I did it and removed puzzle. 
I think we can just remove this issue from scope without payment.

**Comment by emilianodellacasa** [comment]
@vladarefiev My fault, I should have noticed before merging. As a general rule, we make a single PR for a single issue - no exceptions! Next time, just fix the tests, send the PR and as soon as it is merged, send another PR.

Work has been done so payment is due for both of the issues, just pay attention next time

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by vladarefiev** [comment]
@emilianodellacasa Ok, it's clear, thanks

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +35 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
