### ISSUE TITLE
test_tables.py:2-8: Write test for creating and editing...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#234]
The puzzle `169-076d68de` from #169 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/38fe4de0be999c5df48e06f9978d5d71c600566f/tests/test_tables.py#L2-L8

The puzzle was created by Emiliano Della Casa on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#234](https://github.com/timelesslounge/timelessis/issues/234) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#234](https://github.com/timelesslounge/timelessis/issues/234) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/116094b9-2f12-4a64-b64e-893e89e823a1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Vatavuk** [comment]
@emilianodellacasa need a little help. The issue specifies that we need to use `Factory Boy` factories in order to fake relationships in IT tests. I don't think this is necessary at IT level, nor do we have `nullable=True` relationship fields that forces us to do so. Should I just add create/edit/delete test like we have in oder tests without factories to speed things up? We can add them later if we find usage for them. If not, I believe we need to update all other IT tests with factories to be consistent.

**Comment by Vatavuk** [comment]
@0crat wait for rev comment

**Comment by 0crat** [comment]
> @0crat wait for arc comment ([here](https://github.com/timelesslounge/timelessis/issues/234#issuecomment-464869347))

@Vatavuk The impediment for [#234](https://github.com/timelesslounge/timelessis/issues/234) was registered successfully by @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by emilianodellacasa** [comment]
@Vatavuk let's take the faster approach, if we will ever need FactoryBot we will add it

**Comment by 0pdd** [comment]
The puzzle `169-076d68de` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#381](https://github.com/timelesslounge/timelessis/issues/381) is still not solved.

**Comment by 0crat** [comment]
Job [#234](https://github.com/timelesslounge/timelessis/issues/234) is not in the agenda of @vatavuk[/z](https://www.0crat.com/u/vatavuk), can't inspect

**Comment by 0crat** [comment]
The job [#234](https://github.com/timelesslounge/timelessis/issues/234) is now out of scope

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
