### ISSUE TITLE
test_models.py:13-15: We need to move tests in this file...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#237]
The puzzle `31-8e09cb2a` from #31 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/38fe4de0be999c5df48e06f9978d5d71c600566f/tests/test_models.py#L13-L15

The puzzle was created by Emiliano Della Casa on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#237](https://github.com/timelesslounge/timelessis/issues/237) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#237](https://github.com/timelesslounge/timelessis/issues/237) assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/63e12e7d-dc65-4c20-8fd4-0771cf9171ef); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vladarefiev** [comment]
@emilianodellacasa I think this one is out of date. Some structure of tests is already emerged, and now test_models looks logic

**Comment by emilianodellacasa** [comment]
@vladarefiev Thanks, closing it

**Comment by 0crat** [comment]
Job [#237](https://github.com/timelesslounge/timelessis/issues/237) is not in the agenda of @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), can't inspect

**Comment by 0crat** [comment]
The job [#237](https://github.com/timelesslounge/timelessis/issues/237) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/237#issuecomment-464500137))

@ypshenychka This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#237](https://github.com/timelesslounge/timelessis/issues/237) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 2hr
  * @vladarefiev[/z](https://www.0crat.com/u/vladarefiev) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23237%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@vladarefiev Look like no work was done in scope of this issue, right?

**Comment by ypshenychka** [comment]
@vladarefiev Look like no work was done in scope of this issue, right?

**Comment by vladarefiev** [comment]
@ypshenychka correct.

**Comment by ypshenychka** [comment]
@vladarefiev thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
