### ISSUE TITLE
deploy.sh:7-10: Add parameter to this script that will...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#239]
The puzzle `126-b9037461` from #126 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/da6291a3b28261e37598f485daf4d6c8ca44af8a/deploy.sh#L7-L10

The puzzle was created by Boris Kuzmic on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#239](https://github.com/timelesslounge/timelessis/issues/239) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#239](https://github.com/timelesslounge/timelessis/issues/239) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/dabd8d94-4c0d-4b6a-bd83-406a9fd5433f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@bkuzmic @emilianodellacasa It does not seem like Rultor supports this. See [here](http://doc.rultor.com/basics.html), I don't see any way to pass any arguments to the `@rultor deploy` command. Meanwhile the tag param is supported only for `release`.

So it looks like we'll have to do this differently. What do you think?

**Comment by carlosmiranda** [comment]
@0crat wait for clarification

**Comment by 0crat** [comment]
> @0crat wait for clarification ([here](https://github.com/timelesslounge/timelessis/issues/239#issuecomment-464585042))

@carlosmiranda The impediment for [#239](https://github.com/timelesslounge/timelessis/issues/239) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by emilianodellacasa** [comment]
@carlosmiranda you are right, then let's skip the environment parameter for the moment (I will open an issue for it on rultor), and switch from deploy to release

**Comment by carlosmiranda** [comment]
@emilianodellacasa see PR #295

**Comment by 0pdd** [comment]
The puzzle `126-b9037461` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#239](https://github.com/timelesslounge/timelessis/issues/239) is not in the agenda of @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), can't inspect

**Comment by 0crat** [comment]
The job [#239](https://github.com/timelesslounge/timelessis/issues/239) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/timelesslounge/timelessis/issues/239#issuecomment-465532007))

@carlosmiranda This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#239](https://github.com/timelesslounge/timelessis/issues/239) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 1hr
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23239%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/239#issuecomment-465518108))

@ypshenychka This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#239](https://github.com/timelesslounge/timelessis/issues/239) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 1hr
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23239%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
