### ISSUE TITLE
Poster Integration for Table model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#24]
In this first step, we need to synchronize TimelessIs database with an existing database managed by Poster application. The API description can be found at the following address:

https://dev.joinposter.com/en/docs/api#introduction

In this issue a job will be created to sync data for the Table model, using the appropriate API:

- the job will be run using cron on a daily base;
- a new attribute poster_id will be added to the Table model, to store there the id of the BE in Poster;
- a new attribute synchronized_on will be added to the Table model;
- data coming from Poster has priority upon data stored in our database (for now);
- try reusing code taken from issue #23

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#187](https://github.com/timelesslounge/timelessis/issues/187) is still not solved.

**Comment by Vatavuk** [comment]
@emilianodellacasa please close this issue, it was solved in #154 with an extra puzzle

**Comment by emilianodellacasa** [comment]
@vatavuk thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#24](https://github.com/timelesslounge/timelessis/issues/24) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#342](https://github.com/timelesslounge/timelessis/issues/342), [#343](https://github.com/timelesslounge/timelessis/issues/343), [#344](https://github.com/timelesslounge/timelessis/issues/344), [#345](https://github.com/timelesslounge/timelessis/issues/345) are still not solved; solved: [#187](https://github.com/timelesslounge/timelessis/issues/187).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#342](https://github.com/timelesslounge/timelessis/issues/342), [#343](https://github.com/timelesslounge/timelessis/issues/343), [#344](https://github.com/timelesslounge/timelessis/issues/344), [#376](https://github.com/timelesslounge/timelessis/issues/376) are still not solved; solved: [#187](https://github.com/timelesslounge/timelessis/issues/187), [#345](https://github.com/timelesslounge/timelessis/issues/345).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#343](https://github.com/timelesslounge/timelessis/issues/343), [#344](https://github.com/timelesslounge/timelessis/issues/344), [#376](https://github.com/timelesslounge/timelessis/issues/376) are still not solved; solved: [#187](https://github.com/timelesslounge/timelessis/issues/187), [#342](https://github.com/timelesslounge/timelessis/issues/342), [#345](https://github.com/timelesslounge/timelessis/issues/345).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#344](https://github.com/timelesslounge/timelessis/issues/344), [#376](https://github.com/timelesslounge/timelessis/issues/376), [#453](https://github.com/timelesslounge/timelessis/issues/453) are still not solved; solved: [#187](https://github.com/timelesslounge/timelessis/issues/187), [#342](https://github.com/timelesslounge/timelessis/issues/342), [#343](https://github.com/timelesslounge/timelessis/issues/343), [#345](https://github.com/timelesslounge/timelessis/issues/345).
