### ISSUE TITLE
deploy.sh:11-14: Extend the script to check if...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#240]
The puzzle `126-dc28674a` from #126 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/da6291a3b28261e37598f485daf4d6c8ca44af8a/deploy.sh#L11-L14

The puzzle was created by Boris Kuzmic on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#240](https://github.com/timelesslounge/timelessis/issues/240) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#240](https://github.com/timelesslounge/timelessis/issues/240) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/3ec603fd-9ed1-4871-b2d1-1102d280eb67); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@0crat assign @ekondrashev

**Comment by 0crat** [comment]
> @0crat assign @ekondrashev ([here](https://github.com/timelesslounge/timelessis/issues/240#issuecomment-463075278))

@emilianodellacasa The job [#240](https://github.com/timelesslounge/timelessis/issues/240) assigned to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/26ef8364-7894-473d-963d-7cac50775fb9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0pdd** [comment]
The puzzle `126-dc28674a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#248](https://github.com/timelesslounge/timelessis/issues/248) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 9 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@ekondrashev According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Most of your commits contain issue number as a plain text, but not as a link. Please confirm you'll try to avoid this mistake in future.

**Comment by 0crat** [comment]
The job [#240](https://github.com/timelesslounge/timelessis/issues/240) is now out of scope

**Comment by ekondrashev** [comment]
@ypshenychka sure, will do, thanks you!

**Comment by ypshenychka** [comment]
@ekondrashev thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +35 point(s) just awarded to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300) are still not solved; solved: [#248](https://github.com/timelesslounge/timelessis/issues/248).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#299](https://github.com/timelesslounge/timelessis/issues/299) is still not solved; solved: [#248](https://github.com/timelesslounge/timelessis/issues/248), [#300](https://github.com/timelesslounge/timelessis/issues/300).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#374](https://github.com/timelesslounge/timelessis/issues/374) is still not solved; solved: [#248](https://github.com/timelesslounge/timelessis/issues/248), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#490](https://github.com/timelesslounge/timelessis/issues/490) is still not solved; solved: [#248](https://github.com/timelesslounge/timelessis/issues/248), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300), [#374](https://github.com/timelesslounge/timelessis/issues/374).

**Comment by 0pdd** [comment]
@0pdd all 5 puzzles are solved here: [#248](https://github.com/timelesslounge/timelessis/issues/248), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300), [#374](https://github.com/timelesslounge/timelessis/issues/374), [#490](https://github.com/timelesslounge/timelessis/issues/490).
