### ISSUE TITLE
test_owner_privilages.py:33-35: We need to clean global...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#241]
The puzzle `180-d5879bc3` from #180 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/341c734d0d7da7f7418a5591ea4ba8737b7ffd7a/tests/test_owner_privilages.py#L33-L35

The puzzle was created by Vedran Grgo Vatavuk on 13-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#241](https://github.com/timelesslounge/timelessis/issues/241) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#241](https://github.com/timelesslounge/timelessis/issues/241) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/fb16beac-5eea-41d7-afe5-b659cda596d3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@Vatavuk I didn't find any global objects that need to be cleaned.
We have the fixture app which scope is session (And if it may cause problems we need only to change its scope)
Or did you mean something else?

**Comment by Vatavuk** [comment]
@ammaratef45 this one: flask.g.user

**Comment by ammaratef45** [comment]
@Vatavuk thanks :+1:

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@0crat wait for the PR review

**Comment by 0crat** [comment]
> @0crat wait for the PR #276 review ([here](https://github.com/timelesslounge/timelessis/issues/241#issuecomment-465439690))

@ammaratef45 The impediment for [#241](https://github.com/timelesslounge/timelessis/issues/241) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `180-d5879bc3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#241](https://github.com/timelesslounge/timelessis/issues/241) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
