### ISSUE TITLE
it_poster_test.py:8-10: Implement auth process for Poster...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#245]
The puzzle `113-1c2a8720` from #113 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/16b132814356b8a14f49c710821eb17a4eab26b8/tests/integration/it_poster_test.py#L8-L10

The puzzle was created by Emiliano Della Casa on 13-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#245](https://github.com/timelesslounge/timelessis/issues/245) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#245](https://github.com/timelesslounge/timelessis/issues/245) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/72a7b92b-04ff-457b-83f4-aa448e579fc4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `113-1c2a8720` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 46 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#245](https://github.com/timelesslounge/timelessis/issues/245) is now out of scope

**Comment by ypshenychka** [comment]
@amihaiemil Was there any work done in scope of this issue?

**Comment by amihaiemil** [comment]
@ypshenychka no, I haven't had the time to look over it and the puzzle has been removed by mistake in another PR

**Comment by ypshenychka** [comment]
@amihaiemil got it. Thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
