### ISSUE TITLE
install_redis.sh:3-6: Implement redis availability check...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#248]
The puzzle `240-24a1360a` from #240 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/d1ac77f070e153795cf6d119c35ac5b728553c49/scripts/install/deploy/install_redis.sh#L3-L6

The puzzle was created by Eugene Kondrashev on 13-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#248](https://github.com/timelesslounge/timelessis/issues/248) is now in scope, role is `DEV`

**Comment by emilianodellacasa** [comment]
@0crat assign @ekondrashev

**Comment by 0crat** [comment]
The job [#248](https://github.com/timelesslounge/timelessis/issues/248) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/a6d1dc57-267d-486b-9ea1-92bf25b6fa81); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
> @0crat assign @ekondrashev ([here](https://github.com/timelesslounge/timelessis/issues/248#issuecomment-463271502))

@emilianodellacasa The job [#248](https://github.com/timelesslounge/timelessis/issues/248) assigned to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/81f672e5-30e5-4034-80a2-a052a8942c3e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
@ekondrashev[/z](https://www.0crat.com/u/ekondrashev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `240-24a1360a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#248](https://github.com/timelesslounge/timelessis/issues/248) is now out of scope

**Comment by ypshenychka** [comment]
@ekondrashev According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

[One](https://github.com/timelesslounge/timelessis/pull/257/commits/bb0ff00bd2726a8513b63378cc7f282d479d6a53) of your commits contains plain issue number instead of link. Please confirm you'll try to avoid this mistake in future.

**Comment by ypshenychka** [comment]
@ekondrashev ping

**Comment by 0pdd** [comment]
@0pdd the puzzle [#299](https://github.com/timelesslounge/timelessis/issues/299) is still not solved; solved: [#300](https://github.com/timelesslounge/timelessis/issues/300).

**Comment by ypshenychka** [comment]
@ekondrashev Please respond to my above comment.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#374](https://github.com/timelesslounge/timelessis/issues/374) is still not solved; solved: [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300).

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#490](https://github.com/timelesslounge/timelessis/issues/490) is still not solved; solved: [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300), [#374](https://github.com/timelesslounge/timelessis/issues/374).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300), [#374](https://github.com/timelesslounge/timelessis/issues/374), [#490](https://github.com/timelesslounge/timelessis/issues/490).
