### ISSUE TITLE
Poster integration for Customer model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#25]
In this first step, we need to synchronize TimelessIs database with an existing database managed by Poster application. The API description can be found at the following address:

https://dev.joinposter.com/en/docs/api#introduction

In this issue a job will be created to sync data for a new model called Customer (that will be also developed in this issue), using the appropriate API.

The main attributes of the Customer model are:

- Identifier
- Name
- Last Name
- Phone
- poster_id
- created_on
- updated_on
- synchronized_on 

These are the features for the import job:

- the job will be run using cron on a daily base;
- data coming from Poster has priority upon data stored in our database (for now);
- try reusing code taken from issue #23

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#225](https://github.com/timelesslounge/timelessis/issues/225) is still not solved; solved: [#102](https://github.com/timelesslounge/timelessis/issues/102).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262) are still not solved; solved: [#102](https://github.com/timelesslounge/timelessis/issues/102), [#225](https://github.com/timelesslounge/timelessis/issues/225).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#261](https://github.com/timelesslounge/timelessis/issues/261), [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410) are still not solved; solved: [#102](https://github.com/timelesslounge/timelessis/issues/102), [#225](https://github.com/timelesslounge/timelessis/issues/225), [#262](https://github.com/timelesslounge/timelessis/issues/262).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410) are still not solved; solved: [#102](https://github.com/timelesslounge/timelessis/issues/102), [#225](https://github.com/timelesslounge/timelessis/issues/225), [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#409](https://github.com/timelesslounge/timelessis/issues/409) is still not solved; solved: [#102](https://github.com/timelesslounge/timelessis/issues/102), [#225](https://github.com/timelesslounge/timelessis/issues/225), [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262), [#410](https://github.com/timelesslounge/timelessis/issues/410).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#531](https://github.com/timelesslounge/timelessis/issues/531) is still not solved; solved: [#102](https://github.com/timelesslounge/timelessis/issues/102), [#225](https://github.com/timelesslounge/timelessis/issues/225), [#261](https://github.com/timelesslounge/timelessis/issues/261), [#262](https://github.com/timelesslounge/timelessis/issues/262), [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410).
