### ISSUE TITLE
views.py:2-6: Continue implementing edit() and delete()...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#255]
The puzzle `192-19881263` from #192 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/f0bba806d57256e4fbc7665243828412c40fb71f/timeless/roles/views.py#L2-L6

The puzzle was created by Vedran Grgo Vatavuk on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#255](https://github.com/timelesslounge/timelessis/issues/255) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#255](https://github.com/timelesslounge/timelessis/issues/255) assigned to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/3b063f1c-00e7-4266-ba65-999223f537eb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@ekondrashev[/z](https://www.0crat.com/u/ekondrashev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `192-19881263` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#338](https://github.com/timelesslounge/timelessis/issues/338) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#255](https://github.com/timelesslounge/timelessis/issues/255) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#494](https://github.com/timelesslounge/timelessis/issues/494) is still not solved; solved: [#338](https://github.com/timelesslounge/timelessis/issues/338).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#338](https://github.com/timelesslounge/timelessis/issues/338) is still not solved; solved: [#494](https://github.com/timelesslounge/timelessis/issues/494).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
