### ISSUE TITLE
Comment of the day

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#26]
For the Reservation module, it is required to create a new simple model called Comment, that will be displayed on the Timeline view (that will be developed in a future issue).

The main attributes of this model are:

- id
- employee_id
- description
- date
- created_on
- updated_on

The date attribute will be used to decide when to show the comment on the Timeline view (only for a single day).

Comments should have its own management pages to list, create, edit and delete them. In the index page it should be possible to sort and filter for every column.

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#221](https://github.com/timelesslounge/timelessis/issues/221), [#222](https://github.com/timelesslounge/timelessis/issues/222) are still not solved; solved: [#123](https://github.com/timelesslounge/timelessis/issues/123), [#87](https://github.com/timelesslounge/timelessis/issues/87).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#221](https://github.com/timelesslounge/timelessis/issues/221), [#266](https://github.com/timelesslounge/timelessis/issues/266), [#267](https://github.com/timelesslounge/timelessis/issues/267) are still not solved; solved: [#123](https://github.com/timelesslounge/timelessis/issues/123), [#222](https://github.com/timelesslounge/timelessis/issues/222), [#87](https://github.com/timelesslounge/timelessis/issues/87).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#266](https://github.com/timelesslounge/timelessis/issues/266), [#267](https://github.com/timelesslounge/timelessis/issues/267), [#288](https://github.com/timelesslounge/timelessis/issues/288), [#289](https://github.com/timelesslounge/timelessis/issues/289) are still not solved; solved: [#123](https://github.com/timelesslounge/timelessis/issues/123), [#221](https://github.com/timelesslounge/timelessis/issues/221), [#222](https://github.com/timelesslounge/timelessis/issues/222), [#87](https://github.com/timelesslounge/timelessis/issues/87).

**Comment by 0pdd** [comment]
@emilianodellacasa 6 puzzles [#266](https://github.com/timelesslounge/timelessis/issues/266), [#267](https://github.com/timelesslounge/timelessis/issues/267), [#288](https://github.com/timelesslounge/timelessis/issues/288), [#447](https://github.com/timelesslounge/timelessis/issues/447), [#448](https://github.com/timelesslounge/timelessis/issues/448), [#449](https://github.com/timelesslounge/timelessis/issues/449) are still not solved; solved: [#123](https://github.com/timelesslounge/timelessis/issues/123), [#221](https://github.com/timelesslounge/timelessis/issues/221), [#222](https://github.com/timelesslounge/timelessis/issues/222), [#289](https://github.com/timelesslounge/timelessis/issues/289), [#87](https://github.com/timelesslounge/timelessis/issues/87).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#266](https://github.com/timelesslounge/timelessis/issues/266), [#267](https://github.com/timelesslounge/timelessis/issues/267), [#288](https://github.com/timelesslounge/timelessis/issues/288), [#447](https://github.com/timelesslounge/timelessis/issues/447), [#448](https://github.com/timelesslounge/timelessis/issues/448) are still not solved; solved: [#123](https://github.com/timelesslounge/timelessis/issues/123), [#221](https://github.com/timelesslounge/timelessis/issues/221), [#222](https://github.com/timelesslounge/timelessis/issues/222), [#289](https://github.com/timelesslounge/timelessis/issues/289), [#449](https://github.com/timelesslounge/timelessis/issues/449), [#87](https://github.com/timelesslounge/timelessis/issues/87).
