### ISSUE TITLE
views.py:17-19: Implement filtering of TableShape model...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#260]
The puzzle `203-7b2a1685` from #203 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/efb9c7a6cbfa1c66aaba887b6aca986d6bcd99d0/timeless/restaurants/table_shapes/views.py#L17-L19

The puzzle was created by rultor on 14-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#260](https://github.com/timelesslounge/timelessis/issues/260) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#260](https://github.com/timelesslounge/timelessis/issues/260) assigned to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/42eec317-65eb-4a98-a231-4851c7d18bd4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#260` already assigned to @ekondrashev, can't assign to @vatavuk

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#260` already assigned to @ekondrashev, can't assign to @ekondrashev

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#260` already assigned to @ekondrashev, can't assign to @vatavuk

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#314](https://github.com/timelesslounge/timelessis/issues/314), [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317) are still not solved.

**Comment by 0crat** [comment]
@ekondrashev[/z](https://www.0crat.com/u/ekondrashev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev)

**Comment by 0crat** [comment]
The user @ekondrashev[/z](https://www.0crat.com/u/ekondrashev) resigned from [#260](https://github.com/timelesslounge/timelessis/issues/260), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#260](https://github.com/timelesslounge/timelessis/issues/260) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/1074d3b8-ac3e-47db-bdc9-707235135ea1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@emilianodellacasa Something wring happened here, please take a look

**Comment by emilianodellacasa** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/260#issuecomment-467037158))

@emilianodellacasa This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#260](https://github.com/timelesslounge/timelessis/issues/260) is [in scope](http://www.zerocracy.com/policy.html#14) for 11days
  * The role is `DEV`
  * The job is assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) for [6hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @ekondrashev[/z](https://www.0crat.com/u/ekondrashev): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23260%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by emilianodellacasa** [comment]
@0crat out

**Comment by 0crat** [comment]
Job was finished in 5 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/timelesslounge/timelessis/issues/260#issuecomment-467039038))

@emilianodellacasa Job [#260](https://github.com/timelesslounge/timelessis/issues/260) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/timelesslounge/timelessis/issues/260#issuecomment-467039038))

@emilianodellacasa The job [#260](https://github.com/timelesslounge/timelessis/issues/260) is now out of scope

**Comment by emilianodellacasa** [comment]
@ypshenychka something weird happened here, please don't review this job, I will award the author (not @paulodamaso )

**Comment by emilianodellacasa** [comment]
@0crat pay @ekondrashev 30min

**Comment by ypshenychka** [comment]
@emilianodellacasa Ok. But it will be still in my agenda. Should I mark it as "bad"?

**Comment by 0crat** [comment]
> @0crat pay @ekondrashev 30min ([here](https://github.com/timelesslounge/timelessis/issues/260#issuecomment-467040947))

@emilianodellacasa Argument "@ekondrashev" doesn't match regex `\d+min`

**Comment by emilianodellacasa** [comment]
@ypshenychka correct

**Comment by emilianodellacasa** [comment]
@0crat pay 30min @ekondrashev

**Comment by 0crat** [comment]
Direct payment to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev) in #260, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -20 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Direct payment from @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa): +30 point(s) just awarded to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev)

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#314](https://github.com/timelesslounge/timelessis/issues/314), [#316](https://github.com/timelesslounge/timelessis/issues/316), [#317](https://github.com/timelesslounge/timelessis/issues/317) are still not solved; solved: [#315](https://github.com/timelesslounge/timelessis/issues/315).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#314](https://github.com/timelesslounge/timelessis/issues/314), [#317](https://github.com/timelesslounge/timelessis/issues/317), [#538](https://github.com/timelesslounge/timelessis/issues/538) are still not solved; solved: [#315](https://github.com/timelesslounge/timelessis/issues/315), [#316](https://github.com/timelesslounge/timelessis/issues/316).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#unknown](), [#unknown]() are still not solved.
