### ISSUE TITLE
synced_location.py:11-13: Use celery instead jobs...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#261]
The puzzle `225-de90aee1` from #225 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/253294b701e10459e94695eda82cb2ac00d58d75/timeless/sync/synced_location.py#L11-L13

The puzzle was created by Paulo Lobo on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#261](https://github.com/timelesslounge/timelessis/issues/261) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#261](https://github.com/timelesslounge/timelessis/issues/261) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/6d465521-30fd-4596-a085-4ac2064536ee); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#261` already assigned to @vatavuk, can't assign to @vatavuk

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Vatavuk** [comment]
@0crat wait other tasks

**Comment by 0crat** [comment]
> @0crat wait other tasks ([here](https://github.com/timelesslounge/timelessis/issues/261#issuecomment-466550143))

@Vatavuk The impediment for [#261](https://github.com/timelesslounge/timelessis/issues/261) was registered successfully by @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by Vatavuk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/261#issuecomment-466741465))

@Vatavuk The user @vatavuk[/z](https://www.0crat.com/u/vatavuk) resigned from [#261](https://github.com/timelesslounge/timelessis/issues/261), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
The job [#261](https://github.com/timelesslounge/timelessis/issues/261) assigned to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/863ee135-46f2-49c9-be4e-ee1aec1431b2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@ekondrashev[/z](https://www.0crat.com/u/ekondrashev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ekondrashev** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/261#issuecomment-469167414))

@ekondrashev The user @ekondrashev[/z](https://www.0crat.com/u/ekondrashev) resigned from [#261](https://github.com/timelesslounge/timelessis/issues/261), please stop working. Reason for job resignation: Order was cancelled

**Comment by ekondrashev** [comment]
@paulodamaso Failed understanding what one need to do in order for this puzzle get resolved

Basically I failed to find a cron-based celery configuration for the timelessis project. And also I can see that Locations are already being synced with a shared_task sync_locations
https://github.com/timelesslounge/timelessis/blob/master/timeless/poster/tasks.py#L63

**Comment by 0crat** [comment]
The job [#261](https://github.com/timelesslounge/timelessis/issues/261) assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/815ef5f1-4acd-4aec-a870-720236c83f80); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev)

**Comment by 0pdd** [comment]
The puzzle `225-de90aee1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 47 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#261](https://github.com/timelesslounge/timelessis/issues/261) is not in the agenda of @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), can't inspect

**Comment by 0crat** [comment]
The job [#261](https://github.com/timelesslounge/timelessis/issues/261) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)
