### ISSUE TITLE
synced_customer.py:6-10: Implement synchronization...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#262]
The puzzle `225-44860f19` from #225 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/253294b701e10459e94695eda82cb2ac00d58d75/timeless/sync/synced_customer.py#L6-L10

The puzzle was created by Paulo Lobo on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#262](https://github.com/timelesslounge/timelessis/issues/262) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#262](https://github.com/timelesslounge/timelessis/issues/262) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/73dc1d7b-aba5-48a7-bada-a09930e491c2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Vatavuk** [comment]
@0crat wait other tasks

**Comment by 0crat** [comment]
> @0crat wait other tasks ([here](https://github.com/timelesslounge/timelessis/issues/262#issuecomment-466550218))

@Vatavuk The impediment for [#262](https://github.com/timelesslounge/timelessis/issues/262) was registered successfully by @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0pdd** [comment]
The puzzle `225-44860f19` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410) are still not solved.

**Comment by 0crat** [comment]
Job [#262](https://github.com/timelesslounge/timelessis/issues/262) is not in the agenda of @vatavuk[/z](https://www.0crat.com/u/vatavuk), can't inspect

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#262](https://github.com/timelesslounge/timelessis/issues/262) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quailty good

**Comment by 0crat** [comment]
> @0crat quailty good ([here](https://github.com/timelesslounge/timelessis/issues/262#issuecomment-467579629))

@ypshenychka Can't understand "quailty", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#409](https://github.com/timelesslounge/timelessis/issues/409) is still not solved; solved: [#410](https://github.com/timelesslounge/timelessis/issues/410).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#531](https://github.com/timelesslounge/timelessis/issues/531) is still not solved; solved: [#409](https://github.com/timelesslounge/timelessis/issues/409), [#410](https://github.com/timelesslounge/timelessis/issues/410).
