### ISSUE TITLE
test_comment.py:12-14: Finish CommentView implementation...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#266]
The puzzle `222-d023110c` from #222 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/c717d71ed34bda7a889fe9591a6990bde507152c/tests/view/crudeapi/test_comment.py#L12-L14

The puzzle was created by Paulo Lobo on 12-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#266](https://github.com/timelesslounge/timelessis/issues/266) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#266](https://github.com/timelesslounge/timelessis/issues/266) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/8c937c65-58b3-4e4b-890e-0a2842af6d04); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@emilianodellacasa I think I've made a mistake on previous PRs: looks like we do not need an  `CommentView` implementation besides what we already have because all the four methods will be implemented in `CrudAPIView` as result of a puzzle left on #221. I can't see anything else to implement in `CommentView`, could you gave me some directions here?

**Comment by emilianodellacasa** [comment]
@paulodamaso It is correct, let's close this

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#266](https://github.com/timelesslounge/timelessis/issues/266) is now out of scope

**Comment by ypshenychka** [comment]
@paulodamaso Looks like no work was done in this specific ticket, right?

**Comment by paulodamaso** [comment]
@ypshenychka Yes, no work here :)

**Comment by ypshenychka** [comment]
@paulodamaso thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
