### ISSUE TITLE
auth.py:7-11: Translate login error codes. The codes...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#269]
The puzzle `201-b5198280` from #201 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/4e14d92750b120152214582d5c3f908dae4fcf6a/timeless/auth/auth.py#L7-L11

The puzzle was created by Paulo Lobo on 15-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#269](https://github.com/timelesslounge/timelessis/issues/269) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#269](https://github.com/timelesslounge/timelessis/issues/269) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/3484f3cc-ce13-4876-abed-b106d9232f80); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@0pdd the puzzle [#297](https://github.com/timelesslounge/timelessis/issues/297) is still not solved.

**Comment by paulodamaso** [comment]
@emilianodellacasa Forgot to remove the puzzle (again), please take a look

**Comment by 0pdd** [comment]
The puzzle `201-b5198280` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by paulodamaso** [comment]
@ypshenychka ping

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
