### ISSUE TITLE
Reservation model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#27]
The Reservation model represents the reservations that can be made for a given Table (developed in #12)  at a given Location (developed in #10).

Those are the main attributes for the model:
- Id
- Start Time
- End Time
- Duration
- Customer Identifier
- Table Identifiers
- Number of persons
- Comment
- Status (See reservtion lifecycle in the README file)
- created_on
- updated_on

In this issue just an index and a view page will be developed to list all reservations, as a different one will be created to create/edit reservations. In the index page there should be also a function to delete the reservation (after confirmation). In the index page it should be possible to sort and filter for every column.

Also, when developing this please take note of the following features:

- Reservation Management module should be deployed on separate subdomain;
- One reservation can contain multiple tables;

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#171](https://github.com/timelesslounge/timelessis/issues/171), [#172](https://github.com/timelesslounge/timelessis/issues/172) are still not solved.

**Comment by Vatavuk** [comment]
@emilianodellacasa please close this issue, it was solved in #153 with extra puzzles

**Comment by emilianodellacasa** [comment]
@vatavuk thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#27](https://github.com/timelesslounge/timelessis/issues/27) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/timelesslounge/timelessis/issues/27#issuecomment-462073337))

@ypshenychka There is no quality review for [#27](https://github.com/timelesslounge/timelessis/issues/27), no performer

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#172](https://github.com/timelesslounge/timelessis/issues/172) is still not solved; solved: [#171](https://github.com/timelesslounge/timelessis/issues/171).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#172](https://github.com/timelesslounge/timelessis/issues/172), [#215](https://github.com/timelesslounge/timelessis/issues/215) are still not solved; solved: [#171](https://github.com/timelesslounge/timelessis/issues/171).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#215](https://github.com/timelesslounge/timelessis/issues/215) is still not solved; solved: [#171](https://github.com/timelesslounge/timelessis/issues/171), [#172](https://github.com/timelesslounge/timelessis/issues/172).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#215](https://github.com/timelesslounge/timelessis/issues/215), [#235](https://github.com/timelesslounge/timelessis/issues/235), [#236](https://github.com/timelesslounge/timelessis/issues/236) are still not solved; solved: [#171](https://github.com/timelesslounge/timelessis/issues/171), [#172](https://github.com/timelesslounge/timelessis/issues/172).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#215](https://github.com/timelesslounge/timelessis/issues/215), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#379](https://github.com/timelesslounge/timelessis/issues/379), [#380](https://github.com/timelesslounge/timelessis/issues/380) are still not solved; solved: [#171](https://github.com/timelesslounge/timelessis/issues/171), [#172](https://github.com/timelesslounge/timelessis/issues/172), [#235](https://github.com/timelesslounge/timelessis/issues/235).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#215](https://github.com/timelesslounge/timelessis/issues/215), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#379](https://github.com/timelesslounge/timelessis/issues/379), [#434](https://github.com/timelesslounge/timelessis/issues/434) are still not solved; solved: [#171](https://github.com/timelesslounge/timelessis/issues/171), [#172](https://github.com/timelesslounge/timelessis/issues/172), [#235](https://github.com/timelesslounge/timelessis/issues/235), [#380](https://github.com/timelesslounge/timelessis/issues/380).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#215](https://github.com/timelesslounge/timelessis/issues/215), [#379](https://github.com/timelesslounge/timelessis/issues/379), [#434](https://github.com/timelesslounge/timelessis/issues/434) are still not solved; solved: [#171](https://github.com/timelesslounge/timelessis/issues/171), [#172](https://github.com/timelesslounge/timelessis/issues/172), [#235](https://github.com/timelesslounge/timelessis/issues/235), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#380](https://github.com/timelesslounge/timelessis/issues/380).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#379](https://github.com/timelesslounge/timelessis/issues/379), [#434](https://github.com/timelesslounge/timelessis/issues/434), [#484](https://github.com/timelesslounge/timelessis/issues/484) are still not solved; solved: [#171](https://github.com/timelesslounge/timelessis/issues/171), [#172](https://github.com/timelesslounge/timelessis/issues/172), [#215](https://github.com/timelesslounge/timelessis/issues/215), [#235](https://github.com/timelesslounge/timelessis/issues/235), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#380](https://github.com/timelesslounge/timelessis/issues/380).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#379](https://github.com/timelesslounge/timelessis/issues/379), [#484](https://github.com/timelesslounge/timelessis/issues/484), [#492](https://github.com/timelesslounge/timelessis/issues/492) are still not solved; solved: [#171](https://github.com/timelesslounge/timelessis/issues/171), [#172](https://github.com/timelesslounge/timelessis/issues/172), [#215](https://github.com/timelesslounge/timelessis/issues/215), [#235](https://github.com/timelesslounge/timelessis/issues/235), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#380](https://github.com/timelesslounge/timelessis/issues/380), [#434](https://github.com/timelesslounge/timelessis/issues/434).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#379](https://github.com/timelesslounge/timelessis/issues/379), [#492](https://github.com/timelesslounge/timelessis/issues/492) are still not solved; solved: [#171](https://github.com/timelesslounge/timelessis/issues/171), [#172](https://github.com/timelesslounge/timelessis/issues/172), [#215](https://github.com/timelesslounge/timelessis/issues/215), [#235](https://github.com/timelesslounge/timelessis/issues/235), [#236](https://github.com/timelesslounge/timelessis/issues/236), [#380](https://github.com/timelesslounge/timelessis/issues/380), [#434](https://github.com/timelesslounge/timelessis/issues/434), [#484](https://github.com/timelesslounge/timelessis/issues/484).
