### ISSUE TITLE
views.py:2-5: Continue implementation of views class. Use...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#270]
The puzzle `141-9f3e8d9b` from #141 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/d9e9560bafcdc307150970ff10f7ba6d61f73ad0/timeless/items/views.py#L2-L5

The puzzle was created by Ammar Atef on 14-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#270](https://github.com/timelesslounge/timelessis/issues/270) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#270](https://github.com/timelesslounge/timelessis/issues/270) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/9ba557c1-34c3-4fb6-b3b0-b22e67146af5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #270 review and merge

**Comment by 0crat** [comment]
> @0crat wait for #270 review and merge ([here](https://github.com/timelesslounge/timelessis/issues/270#issuecomment-467110198))

@paulodamaso The impediment for [#270](https://github.com/timelesslounge/timelessis/issues/270) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `141-9f3e8d9b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#417](https://github.com/timelesslounge/timelessis/issues/417), [#418](https://github.com/timelesslounge/timelessis/issues/418) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#270](https://github.com/timelesslounge/timelessis/issues/270) is now out of scope

**Comment by ypshenychka** [comment]
@paulodamaso According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

Not all commits contains link to issue. Please confirm you'll try to follow this rule next time.

**Comment by paulodamaso** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@paulodamaso thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#418](https://github.com/timelesslounge/timelessis/issues/418), [#527](https://github.com/timelesslounge/timelessis/issues/527) are still not solved; solved: [#417](https://github.com/timelesslounge/timelessis/issues/417).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#569](https://github.com/timelesslounge/timelessis/issues/569) is still not solved.
