### ISSUE TITLE
Caching problems

### ISSUE THREAD

**Issue by vryazanov** [timelesslounge/timelessis#273]
Hi there,
As I can see now we have a few problems related to cache:
1. We are caching base template, it means we cache forms for creating / editing models. And I guess with their initial values (for editing forms). 
2. Need to have ability to set redis hostname in config files. Right now, unfortunately, docker setup is broken since cache is looking at local redis and we cannot setup a specific hostname.
3. Now we initialized the following way:
```python
    cache = Cache(app, config={"CACHE_TYPE": "redis"})
```
inside `create_app` function. It means we cannot import instance of `cache` and use it as decorator. Another words, currently it works only in templates and we cannot cache views or functions.
See how it could be done: https://github.com/sloria/cookiecutter-flask/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/%7B%7Bcookiecutter.app_name%7D%7D/extensions.py

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#273](https://github.com/timelesslounge/timelessis/issues/273) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#273` already assigned to @ammaratef45, can't assign to @ammaratef45

**Comment by 0crat** [comment]
The job [#273](https://github.com/timelesslounge/timelessis/issues/273) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/a4c3ad48-df81-4a66-b8d7-8ed24dab980f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by ammaratef45** [comment]
@vryazanov Is it fine after merging #294?

**Comment by vryazanov** [comment]
@ammaratef45 bellissimo :+1:

**Comment by ammaratef45** [comment]
@vryazanov Grazie :laughing:

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#273](https://github.com/timelesslounge/timelessis/issues/273) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
