### ISSUE TITLE
__init__.py:21-23: Continue securing other views, by...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#278]
The puzzle `179-b0e1041f` from #179 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/66ab6f4dbe68b90a6fc6455e94f510b7e17e6acf/timeless/access_control/__init__.py#L21-L23

The puzzle was created by amihaiemil on 13-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#278](https://github.com/timelesslounge/timelessis/issues/278) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#278](https://github.com/timelesslounge/timelessis/issues/278) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/c0575aeb-dd0f-49a0-beb1-bfbed3d27a23); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/timelesslounge/timelessis/pull/436 review and merge

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/timelesslounge/timelessis/pull/436 review and merge ([here](https://github.com/timelesslounge/timelessis/issues/278#issuecomment-468016726))

@paulodamaso The impediment for [#278](https://github.com/timelesslounge/timelessis/issues/278) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `179-b0e1041f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#473](https://github.com/timelesslounge/timelessis/issues/473), [#474](https://github.com/timelesslounge/timelessis/issues/474) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#278](https://github.com/timelesslounge/timelessis/issues/278) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#570](https://github.com/timelesslounge/timelessis/issues/570), [#unknown]() are still not solved.
