### ISSUE TITLE
API to retrieve Reservations

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#28]
An API endpoint should be created to retrieve a list of reservations (developed in #27) in JSON format, based on following parameters:

- location;
- date;

The API should be password protected and linked to a specific Company (developed in #3), that will be used to filter out all data not belonging to that company.

**Comment by carlosmiranda** [comment]
@emilianodellacasa I was originally waiting for this because of #27. However, now I find that there is a more generic framework being created for JSON CRUD operations (#221).

So it seems like this is being superseded by that framework. Or am I wrong, and is there something different about this task?

**Comment by emilianodellacasa** [comment]
@carlosmiranda We still need to password protect the API (a token defined per Company) and filter by location and date

**Comment by carlosmiranda** [comment]
@emilianodellacasa see PR #254

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#328](https://github.com/timelesslounge/timelessis/issues/328) is still not solved.

**Comment by carlosmiranda** [comment]
@emilianodellacasa #254 merged, may we close this now?

**Comment by emilianodellacasa** [comment]
@carlosmiranda Sure, thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#28](https://github.com/timelesslounge/timelessis/issues/28) is now out of scope

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

[One](https://github.com/timelesslounge/timelessis/pull/254/commits/c93cc26c2f95f46ea511ab635f5945165c43eb43) of your commits contains link to another issue. Please confirm you'll try to avoid this mistake in future.

**Comment by ypshenychka** [comment]
@carlosmiranda According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details into registered [impediment](https://github.com/timelesslounge/timelessis/issues/28#issuecomment-458376892).

**Comment by carlosmiranda** [comment]
@ypshenychka confirmed

**Comment by ypshenychka** [comment]
@carlosmiranda thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#unknown]() is still not solved.
