### ISSUE TITLE
it_auth_test.py:29-32: Continue implementation of the...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#283]
The puzzle `149-40cd4662` from #149 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/fe8ba2ffcd47ba876ef4c9036ffbe046320ccfc4/tests/integration/it_auth_test.py#L29-L32

The puzzle was created by @rultor on 18-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
Job [#283](https://github.com/timelesslounge/timelessis/issues/283) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#283](https://github.com/timelesslounge/timelessis/issues/283) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/d356c062-7072-4609-a434-430170b25ef5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#283` already assigned to @carlosmiranda, can't assign to @carlosmiranda

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#283` already assigned to @carlosmiranda, can't assign to @carlosmiranda

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu  ([here](https://github.com/timelesslounge/timelessis/issues/283#issuecomment-464708141))

@emilianodellacasa Job `gh:timelesslounge/timelessis#283` already assigned to @carlosmiranda, can't assign to @marceloamadeu

**Comment by 0crat** [comment]
The job [#283](https://github.com/timelesslounge/timelessis/issues/283) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/b4e808dc-8d8b-49b2-8473-59c76f1f601e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#283` already assigned to @carlosmiranda, can't assign to @carlosmiranda

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/283#issuecomment-466703378))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#283](https://github.com/timelesslounge/timelessis/issues/283), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
The job [#283](https://github.com/timelesslounge/timelessis/issues/283) assigned to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/d9cbfcca-0be3-4e01-b8a6-0685218ffc08); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@ekondrashev[/z](https://www.0crat.com/u/ekondrashev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `149-40cd4662` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#460](https://github.com/timelesslounge/timelessis/issues/460) is still not solved.

**Comment by 0crat** [comment]
Job [#283](https://github.com/timelesslounge/timelessis/issues/283) is not in the agenda of @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), can't inspect

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#283](https://github.com/timelesslounge/timelessis/issues/283) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
