### ISSUE TITLE
director_privileges.py:16-18: Add role to the employee...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#284]
The puzzle `175-e2d8fa4e` from #175 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/688d24eee5d1252d9dfd5314a48fb79e38217e3e/timeless/access_control/director_privileges.py#L16-L18

The puzzle was created by Krzysztof Krason on 17-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#284](https://github.com/timelesslounge/timelessis/issues/284) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#284](https://github.com/timelesslounge/timelessis/issues/284) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/2cd27e69-3bcc-45aa-afc6-963c6305bf6d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@0crat waiting for #427 to be merged

**Comment by 0crat** [comment]
> @0crat waiting for #427 to be merged ([here](https://github.com/timelesslounge/timelessis/issues/284#issuecomment-467596226))

@amihaiemil The impediment for [#284](https://github.com/timelesslounge/timelessis/issues/284) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0pdd** [comment]
The puzzle `175-e2d8fa4e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#284](https://github.com/timelesslounge/timelessis/issues/284) is not in the agenda of @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), can't inspect

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#284](https://github.com/timelesslounge/timelessis/issues/284) is now out of scope

**Comment by amihaiemil** [comment]
@ypshenychka ping :)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
