### ISSUE TITLE
it_table_shapes_test.py:38-40: Fix...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#285]
The puzzle `206-24391b14` from #206 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/3c79e5aed367090b3493f764ba6916d48660094a/tests/integration/it_table_shapes_test.py#L38-L40

The puzzle was created by Krzysztof Krason on 16-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#285](https://github.com/timelesslounge/timelessis/issues/285) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#285](https://github.com/timelesslounge/timelessis/issues/285) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/b7b0d800-8797-46d6-baae-01172d3716a2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat refuse

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/285#issuecomment-465149618))

@krzyk Job `gh:timelesslounge/timelessis#285` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/285#issuecomment-465022666))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#285](https://github.com/timelesslounge/timelessis/issues/285), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#285](https://github.com/timelesslounge/timelessis/issues/285) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/d3e59875-c12e-42dd-bfca-d948a02ce96f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vryazanov** [comment]
@0crat wait for #310 
I need to reuse some base method implemented in PR for that task. So I cannot implement current task the best way without it.

**Comment by 0crat** [comment]
> @0crat wait for #310 I need to reuse some base method implemented in PR for that task. So I can... ([here](https://github.com/timelesslounge/timelessis/issues/285#issuecomment-466690239))

@vryazanov The impediment for [#285](https://github.com/timelesslounge/timelessis/issues/285) was registered successfully by @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0pdd** [comment]
The puzzle `206-24391b14` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#462](https://github.com/timelesslounge/timelessis/issues/462) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#285](https://github.com/timelesslounge/timelessis/issues/285) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
