### ISSUE TITLE
it_reservation_settings_test.py:2-4: Write tests for...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#291]
The puzzle `186-9fde7513` from #186 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/1a7bf6bc7e7067ecd0d154dff1c6b350c651b20a/tests/integration/it_reservation_settings_test.py#L2-L4

The puzzle was created by Vlad Arefev on 16-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#291](https://github.com/timelesslounge/timelessis/issues/291) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#291](https://github.com/timelesslounge/timelessis/issues/291) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/658ec235-a31c-41af-90d9-f226eff6422c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat waiting for review of PR #335

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #335  ([here](https://github.com/timelesslounge/timelessis/issues/291#issuecomment-465703030))

@krzyk The impediment for [#291](https://github.com/timelesslounge/timelessis/issues/291) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `186-9fde7513` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#356](https://github.com/timelesslounge/timelessis/issues/356) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 45 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job [#291](https://github.com/timelesslounge/timelessis/issues/291) is not in the agenda of @krzyk[/z](https://www.0crat.com/u/krzyk), can't inspect

**Comment by 0crat** [comment]
The job [#291](https://github.com/timelesslounge/timelessis/issues/291) is now out of scope

**Comment by krzyk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/291#issuecomment-465971530))

@krzyk This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#291](https://github.com/timelesslounge/timelessis/issues/291) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 2hr
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will receive 35 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23291%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by krzyk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/291#issuecomment-466329192))

@krzyk This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#291](https://github.com/timelesslounge/timelessis/issues/291) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 24hr
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will receive 35 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23291%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/timelesslounge/timelessis/issues/291#issuecomment-466183671))

@ypshenychka There is no quality review for [#291](https://github.com/timelesslounge/timelessis/issues/291), no performer

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/timelesslounge/timelessis/issues/291#issuecomment-466339620))

@ypshenychka There is no quality review for [#291](https://github.com/timelesslounge/timelessis/issues/291), no performer

**Comment by 0pdd** [comment]
@0pdd the puzzle [#510](https://github.com/timelesslounge/timelessis/issues/510) is still not solved; solved: [#356](https://github.com/timelesslounge/timelessis/issues/356).
