### ISSUE TITLE
forms.py:10-12: excluding greeting_by_time is temporary...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#292]
The puzzle `186-595169e7` from #186 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/1a7bf6bc7e7067ecd0d154dff1c6b350c651b20a/timeless/reservations/forms.py#L10-L12

The puzzle was created by Vlad Arefev on 16-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#292](https://github.com/timelesslounge/timelessis/issues/292) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#292](https://github.com/timelesslounge/timelessis/issues/292) assigned to @salgadobreno[/z](https://www.0crat.com/u/salgadobreno), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/6e9be888-122c-4f39-be4d-af52dbab83f9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#292` already assigned to @salgadobreno, can't assign to @blackout314

**Comment by salgadobreno** [comment]
@0crat wait for clarification from #360

**Comment by 0crat** [comment]
> @0crat wait for clarification from #360  ([here](https://github.com/timelesslounge/timelessis/issues/292#issuecomment-466014966))

@salgadobreno The impediment for [#292](https://github.com/timelesslounge/timelessis/issues/292) was registered successfully by @salgadobreno[/z](https://www.0crat.com/u/salgadobreno)

**Comment by emilianodellacasa** [comment]
@salgadobreno let's close this

**Comment by 0crat** [comment]
Job [#292](https://github.com/timelesslounge/timelessis/issues/292) is not in the agenda of @salgadobreno[/z](https://www.0crat.com/u/salgadobreno), can't inspect

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @salgadobreno[/z](https://www.0crat.com/u/salgadobreno), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#292](https://github.com/timelesslounge/timelessis/issues/292) is now out of scope

**Comment by ypshenychka** [comment]
@salgadobreno No work was done here, right?

**Comment by salgadobreno** [comment]
@ypshenychka yes, we had tried to get a better definition on the puzzle, that didn't happen tho.

**Comment by ypshenychka** [comment]
@salgadobreno thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
