### ISSUE TITLE
README.md:260-262: We need a more user friendly way to...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#296]
The puzzle `224-90cc17e9` from #224 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/29f46e8c6d552800ec2799e106d17e0426edb78a/README.md#L260-L262

The puzzle was created by Carlos Miranda on 19-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#296](https://github.com/timelesslounge/timelessis/issues/296) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#296](https://github.com/timelesslounge/timelessis/issues/296) assigned to @salgadobreno[/z](https://www.0crat.com/u/salgadobreno), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/1fdb7a6a-c6c7-465f-b67d-1d01f017ab90); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#296` already assigned to @salgadobreno, can't assign to @salgadobreno

**Comment by 0pdd** [comment]
The puzzle `224-90cc17e9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#352](https://github.com/timelesslounge/timelessis/issues/352) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 43 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @salgadobreno[/z](https://www.0crat.com/u/salgadobreno), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#296](https://github.com/timelesslounge/timelessis/issues/296) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @salgadobreno[/z](https://www.0crat.com/u/salgadobreno)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#352](https://github.com/timelesslounge/timelessis/issues/352) is solved here.
