### ISSUE TITLE
manager_privileges.py:16-19: Add role to the employee...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#298]
The puzzle `176-54367cd5` from #176 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/6f057773e6afa62de0c0ce792e40d30622961712/timeless/access_control/manager_privileges.py#L16-L19

The puzzle was created by Krzysztof Krason on 17-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#298](https://github.com/timelesslounge/timelessis/issues/298) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#298` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by 0crat** [comment]
The job [#298](https://github.com/timelesslounge/timelessis/issues/298) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/4457df60-4eb6-4ed6-8087-e2e0e0ac6b6e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#298` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by 0pdd** [comment]
@0pdd the puzzle [#341](https://github.com/timelesslounge/timelessis/issues/341) is still not solved.

**Comment by 0pdd** [comment]
The puzzle `176-54367cd5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#298](https://github.com/timelesslounge/timelessis/issues/298) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by 0crat** [comment]
The job [#298](https://github.com/timelesslounge/timelessis/issues/298) is now out of scope

**Comment by paulodamaso** [comment]
@0pdd status

**Comment by 0pdd** [comment]
> @0pdd status

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/298#issuecomment-466358900))

@paulodamaso This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#298](https://github.com/timelesslounge/timelessis/issues/298) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 14hr
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23298%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@ypshenychka Please take a look, @0crat missed this one too

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/timelesslounge/timelessis/issues/298#issuecomment-466361972); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#397](https://github.com/timelesslounge/timelessis/issues/397) is still not solved; solved: [#341](https://github.com/timelesslounge/timelessis/issues/341).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#481](https://github.com/timelesslounge/timelessis/issues/481) is still not solved; solved: [#341](https://github.com/timelesslounge/timelessis/issues/341), [#397](https://github.com/timelesslounge/timelessis/issues/397).
