### ISSUE TITLE
install_db.sh:3-5: Implement a service for Postgres....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#299]
The puzzle `248-2f8cb0ee` from #248 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/dab4df72003b99610431e6b3df5251524adabf8f/scripts/install/deploy/install_db.sh#L3-L5

The puzzle was created by Eugene Kondrashev on 19-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#299](https://github.com/timelesslounge/timelessis/issues/299) is now in scope, role is `DEV`

**Comment by emilianodellacasa** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu  ([here](https://github.com/timelesslounge/timelessis/issues/299#issuecomment-465073315))

@emilianodellacasa The job [#299](https://github.com/timelesslounge/timelessis/issues/299) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/81b27375-80dd-4b7b-a0d8-115eaa10094b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `248-2f8cb0ee` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#374](https://github.com/timelesslounge/timelessis/issues/374) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#299](https://github.com/timelesslounge/timelessis/issues/299) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#490](https://github.com/timelesslounge/timelessis/issues/490) is still not solved; solved: [#374](https://github.com/timelesslounge/timelessis/issues/374).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#374](https://github.com/timelesslounge/timelessis/issues/374), [#490](https://github.com/timelesslounge/timelessis/issues/490).
