### ISSUE TITLE
Company Model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#3]
Timeless IS manages different companies (i.e. bar franchises), each company has its own users having different roles and privileges. The company is the base Business Entity to which almost any other BE refers to.

Those are its base attributes:

- id (Primary Key)
- name (Unique)
- code (Unique)
- address
- created_on
- updated_on

Companies should have its own management pages to list, create, edit and delete them. In the index page it should be possible to sort and filter for every column.

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#39](https://github.com/timelesslounge/timelessis/issues/39) is still not solved; solved: [#103](https://github.com/timelesslounge/timelessis/issues/103), [#40](https://github.com/timelesslounge/timelessis/issues/40), [#91](https://github.com/timelesslounge/timelessis/issues/91), [#94](https://github.com/timelesslounge/timelessis/issues/94).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#unknown]() is still not solved.
