### ISSUE TITLE
install_redis.sh:3-5: Implement a service for Redis....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#300]
The puzzle `248-ab443c03` from #248 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/dab4df72003b99610431e6b3df5251524adabf8f/scripts/install/deploy/install_redis.sh#L3-L5

The puzzle was created by Eugene Kondrashev on 19-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#300](https://github.com/timelesslounge/timelessis/issues/300) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#300](https://github.com/timelesslounge/timelessis/issues/300) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/f9be0452-96eb-42e2-b4e6-ef829578408d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@emilianodellacasa Looks like this is already implemented, please take a look

**Comment by emilianodellacasa** [comment]
@paulodamaso Now we only check if Redis is running when we are deploying, but we should also make sure that it starts at boot

**Comment by paulodamaso** [comment]
@emilianodellacasa You say putting them in dockerfile?

**Comment by emilianodellacasa** [comment]
@paulodamaso No, it's deploying, talking about the staging (or production) server

**Comment by paulodamaso** [comment]
@emilianodellacasa So call them from `deploy.sh`? I'm sorry but I'm a little confused here

**Comment by paulodamaso** [comment]
@emilianodellacasa ping

**Comment by emilianodellacasa** [comment]
@paulodamaso This how it is working now:

1) we call `release.sh` (has been renamed in last merge) to install webapp to staging server;
2) `scripts/install/deploy/install_dependencies.sh` is called to install python, postgres and redis with their own script;
3) in case of Redis, 'scripts/install/deploy/install_redis.sh' is called, where Redis is installed and run;

However, we still do not add a service to be sure that Redis starts when the server is rebooted; what we want on this issue is to create a service for Redis (or using an existing one, I don't know/care) and adding to autostart (if not added yet).

**Comment by 0pdd** [comment]
The puzzle `248-ab443c03` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#300](https://github.com/timelesslounge/timelessis/issues/300) is now out of scope

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
