### ISSUE TITLE
it_floors_test.py:9-11: Once issue with cache (#273) is...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#305]
The puzzle `173-1b9752ab` from #173 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/43a0e0ec6d04b326ce0c63a8d143430b376aa6e6/tests/integration/it_floors_test.py#L9-L11

The puzzle was created by Boris Kuzmic on 19-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#305](https://github.com/timelesslounge/timelessis/issues/305) is now in scope, role is `DEV`

**Comment by ammaratef45** [comment]
@emilianodellacasa this is solved once we merge #294 
needs just to remove the todo and the fixture
I can do this if you permit.

**Comment by emilianodellacasa** [comment]
@0crat assign @ammaratef45

**Comment by emilianodellacasa** [comment]
@ammaratef45 Sure, thanks

**Comment by 0crat** [comment]
> @0crat assign @ammaratef45  ([here](https://github.com/timelesslounge/timelessis/issues/305#issuecomment-465236965))

@emilianodellacasa The job [#305](https://github.com/timelesslounge/timelessis/issues/305) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/7c357070-11da-4b7c-8b86-dcf38b488973); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `173-1b9752ab` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#305](https://github.com/timelesslounge/timelessis/issues/305) is now out of scope

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)
