### ISSUE TITLE
views.py:22-24: Refactor (and uncomment) views below to...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#306]
The puzzle `173-b323501f` from #173 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/43a0e0ec6d04b326ce0c63a8d143430b376aa6e6/timeless/reservations/views.py#L22-L24

The puzzle was created by Boris Kuzmic on 18-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#306](https://github.com/timelesslounge/timelessis/issues/306) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#306](https://github.com/timelesslounge/timelessis/issues/306) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/69d16faa-7800-4b2a-98af-e92cb2f03038); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for https://github.com/timelesslounge/timelessis/pull/451 review and merge

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/timelesslounge/timelessis/pull/451 review and merge ([here](https://github.com/timelesslounge/timelessis/issues/306#issuecomment-468509790))

@paulodamaso The impediment for [#306](https://github.com/timelesslounge/timelessis/issues/306) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `173-b323501f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#306](https://github.com/timelesslounge/timelessis/issues/306) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#306](https://github.com/timelesslounge/timelessis/issues/306) is now out of scope

**Comment by emilianodellacasa** [comment]
@rultor release, tag=`0.0.1`

**Comment by emilianodellacasa** [comment]
@rultor release, tag=`0.0.1`

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
