### ISSUE TITLE
Why do we keep models in one file?

### ISSUE THREAD

**Issue by amihaiemil** [timelesslounge/timelessis#31]
According to [this](https://github.com/timelesslounge/timelessis/blob/master/timeless/models.py#L1), all DB models should be declared into one single file, ``models.py``. Is this the norm in the Python world? 

I find it messy and, in the beginning (until all models are done) there will be a lot of conflicts.

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#237](https://github.com/timelesslounge/timelessis/issues/237) is still not solved.

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#unknown]() is still not solved.
