### ISSUE TITLE
views.py:16-17: Once CreateView is implemented, refactor...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#310]
The puzzle `173-407b679d` from #173 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/43a0e0ec6d04b326ce0c63a8d143430b376aa6e6/timeless/views.py#L16-L17

The puzzle was created by Boris Kuzmic on 18-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#310](https://github.com/timelesslounge/timelessis/issues/310) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#310](https://github.com/timelesslounge/timelessis/issues/310) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/d65ea4c0-ec58-4c3c-9c95-d88dea6ddacf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vryazanov[/z](https://www.0crat.com/u/vryazanov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vryazanov** [comment]
@0crat wait for review, PR is open

**Comment by 0crat** [comment]
> @0crat wait for review, PR is open ([here](https://github.com/timelesslounge/timelessis/issues/310#issuecomment-466810242))

@vryazanov The impediment for [#310](https://github.com/timelesslounge/timelessis/issues/310) was registered successfully by @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0pdd** [comment]
The puzzle `173-407b679d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#310](https://github.com/timelesslounge/timelessis/issues/310) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
