### ISSUE TITLE
views.py:21-23: Once DeleteView is implemented, refactor...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#312]
The puzzle `173-ed27940d` from #173 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/43a0e0ec6d04b326ce0c63a8d143430b376aa6e6/timeless/views.py#L21-L23

The puzzle was created by Boris Kuzmic on 18-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#312](https://github.com/timelesslounge/timelessis/issues/312) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#312](https://github.com/timelesslounge/timelessis/issues/312) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/17b35a14-1d2e-41e6-8b91-aae51de85084); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vryazanov[/z](https://www.0crat.com/u/vryazanov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vryazanov** [comment]
@0crat wait for review, PR is open

**Comment by 0crat** [comment]
> @0crat wait for review, PR is open ([here](https://github.com/timelesslounge/timelessis/issues/312#issuecomment-466810260))

@vryazanov The impediment for [#312](https://github.com/timelesslounge/timelessis/issues/312) was registered successfully by @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0pdd** [comment]
The puzzle `173-ed27940d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#437](https://github.com/timelesslounge/timelessis/issues/437) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#312](https://github.com/timelesslounge/timelessis/issues/312) is not in the agenda of @vryazanov[/z](https://www.0crat.com/u/vryazanov), can't inspect

**Comment by 0crat** [comment]
The job [#312](https://github.com/timelesslounge/timelessis/issues/312) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/timelesslounge/timelessis/issues/312#issuecomment-468132623))

@ypshenychka There is no quality review for [#312](https://github.com/timelesslounge/timelessis/issues/312), no performer

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
