### ISSUE TITLE
it_table_shapes_test.py:54-56: Uncomment below assertion...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#315]
The puzzle `260-f7abb4b5` from #260 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/fcd58cef9e7ad7bdd02d7ffd51f2acab9cf59485/tests/integration/it_table_shapes_test.py#L54-L56

The puzzle was created by @ekondrashev on 19-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#315](https://github.com/timelesslounge/timelessis/issues/315) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#315](https://github.com/timelesslounge/timelessis/issues/315) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/5d929f4e-0d24-4402-a08d-64e59834bb08); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #406 review and merge

**Comment by 0crat** [comment]
> @0crat wait for #406 review and merge ([here](https://github.com/timelesslounge/timelessis/issues/315#issuecomment-467290943))

@paulodamaso The impediment for [#315](https://github.com/timelesslounge/timelessis/issues/315) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `260-f7abb4b5` has disappeared from the source code, that's why I closed this issue.

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/315#issuecomment-469708281))

@paulodamaso This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#315](https://github.com/timelesslounge/timelessis/issues/315) is [in scope](http://www.zerocracy.com/policy.html#14) for 14days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23315%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#315](https://github.com/timelesslounge/timelessis/issues/315) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by 0crat** [comment]
The job [#315](https://github.com/timelesslounge/timelessis/issues/315) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/315#issuecomment-469810826))

@paulodamaso This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#315](https://github.com/timelesslounge/timelessis/issues/315) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 3hr
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23315%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
