### ISSUE TITLE
views.py:19-21: Implement filtering of table shapes from...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#316]
The puzzle `260-042ad018` from #260 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/fcd58cef9e7ad7bdd02d7ffd51f2acab9cf59485/timeless/restaurants/table_shapes/views.py#L19-L21

The puzzle was created by Eugene Kondrashev on 19-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#316](https://github.com/timelesslounge/timelessis/issues/316) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#316](https://github.com/timelesslounge/timelessis/issues/316) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/4414c922-ca6d-4e72-afc0-eaad9bc4c7d3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/316#issuecomment-468514312))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#316](https://github.com/timelesslounge/timelessis/issues/316), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#316](https://github.com/timelesslounge/timelessis/issues/316) assigned to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/b115f657-4c04-4ea9-9499-a8ff1ec6d136); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#316` already assigned to @ebercamargo, can't assign to @ebercamargo

**Comment by 0crat** [comment]
@ebercamargo[/z](https://www.0crat.com/u/ebercamargo) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ebercamargo** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/316#issuecomment-471293461))

@ebercamargo The user @ebercamargo[/z](https://www.0crat.com/u/ebercamargo) resigned from [#316](https://github.com/timelesslounge/timelessis/issues/316), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ebercamargo[/z](https://www.0crat.com/u/ebercamargo)

**Comment by 0crat** [comment]
The job [#316](https://github.com/timelesslounge/timelessis/issues/316) assigned to @soin08[/z](https://www.0crat.com/u/soin08), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/efa2099c-b1a6-4eeb-88b6-f9585b830de0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `260-042ad018` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#538](https://github.com/timelesslounge/timelessis/issues/538) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @soin08[/z](https://www.0crat.com/u/soin08), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#316](https://github.com/timelesslounge/timelessis/issues/316) is not in the agenda of @soin08[/z](https://www.0crat.com/u/soin08), can't inspect

**Comment by 0crat** [comment]
The job [#316](https://github.com/timelesslounge/timelessis/issues/316) is now out of scope

**Comment by ypshenychka** [comment]
@soin08 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

One of your commits doesn't contain link to issue. Please confirm you'll try to follow this rule next time.

**Comment by soin08** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @soin08[/z](https://www.0crat.com/u/soin08)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
