### ISSUE TITLE
models.py:36-39: Implement function to return item...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#318]
The puzzle `217-abdb84b1` from #217 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/116ee0308b53c57e9ca1171915f6dbdcfa5be751/timeless/items/models.py#L36-L39

The puzzle was created by Paulo Lobo on 15-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#318](https://github.com/timelesslounge/timelessis/issues/318) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#318](https://github.com/timelesslounge/timelessis/issues/318) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/878ef5f9-a8d3-47a0-abaa-504e5348988e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `217-abdb84b1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#318](https://github.com/timelesslounge/timelessis/issues/318) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by 0crat** [comment]
The job [#318](https://github.com/timelesslounge/timelessis/issues/318) is now out of scope

**Comment by paulodamaso** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/318#issuecomment-466356111))

@paulodamaso This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#318](https://github.com/timelesslounge/timelessis/issues/318) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 2hr
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23318%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by paulodamaso** [comment]
@ypshenychka Take a look at this one please

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
