### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#32]
A Setting page should be developed for the reservation module. A model for Settings should also be developed and data stored on the database.

- default duration of a Reservation (developed in #27); this value should be shown as default upon a Reservation creation;
- default deposit amount of a Reservation; this value should be shown as default upon a Reservation creation;
- flag for activating SMS notification;
- threshold time after sending an SMS;
- time window to apply a greeting in the SMS notification (Good morning / Good afternoon / Good evening based on current time);
- sex (applicable only for Russian language);
- name (Placeholder);

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#186](https://github.com/timelesslounge/timelessis/issues/186) is still not solved; solved: [#63](https://github.com/timelesslounge/timelessis/issues/63).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#291](https://github.com/timelesslounge/timelessis/issues/291), [#292](https://github.com/timelesslounge/timelessis/issues/292), [#293](https://github.com/timelesslounge/timelessis/issues/293) are still not solved; solved: [#186](https://github.com/timelesslounge/timelessis/issues/186), [#63](https://github.com/timelesslounge/timelessis/issues/63).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#292](https://github.com/timelesslounge/timelessis/issues/292), [#293](https://github.com/timelesslounge/timelessis/issues/293), [#356](https://github.com/timelesslounge/timelessis/issues/356) are still not solved; solved: [#186](https://github.com/timelesslounge/timelessis/issues/186), [#291](https://github.com/timelesslounge/timelessis/issues/291), [#63](https://github.com/timelesslounge/timelessis/issues/63).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#292](https://github.com/timelesslounge/timelessis/issues/292), [#356](https://github.com/timelesslounge/timelessis/issues/356), [#476](https://github.com/timelesslounge/timelessis/issues/476) are still not solved; solved: [#186](https://github.com/timelesslounge/timelessis/issues/186), [#291](https://github.com/timelesslounge/timelessis/issues/291), [#293](https://github.com/timelesslounge/timelessis/issues/293), [#63](https://github.com/timelesslounge/timelessis/issues/63).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#292](https://github.com/timelesslounge/timelessis/issues/292), [#476](https://github.com/timelesslounge/timelessis/issues/476), [#510](https://github.com/timelesslounge/timelessis/issues/510) are still not solved; solved: [#186](https://github.com/timelesslounge/timelessis/issues/186), [#291](https://github.com/timelesslounge/timelessis/issues/291), [#293](https://github.com/timelesslounge/timelessis/issues/293), [#356](https://github.com/timelesslounge/timelessis/issues/356), [#63](https://github.com/timelesslounge/timelessis/issues/63).
