### ISSUE TITLE
test_authorization.py:7-9: This test stopped working...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#329]
The puzzle `181-375c6297` from #181 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/7efee7958a33ae06ec816270ed9178006f4a595d/tests/test_authorization.py#L7-L9

The puzzle was created by Krzysztof Krason on 19-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#329](https://github.com/timelesslounge/timelessis/issues/329) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#329](https://github.com/timelesslounge/timelessis/issues/329) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/b8a9b505-2812-408b-90a1-67030c590489); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@0crat waiting for review of PR #333

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #333  ([here](https://github.com/timelesslounge/timelessis/issues/329#issuecomment-465575702))

@krzyk The impediment for [#329](https://github.com/timelesslounge/timelessis/issues/329) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `181-375c6297` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#358](https://github.com/timelesslounge/timelessis/issues/358) is still not solved.

**Comment by krzyk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/329#issuecomment-465980056))

@krzyk This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#329](https://github.com/timelesslounge/timelessis/issues/329) is [in scope](http://www.zerocracy.com/policy.html#14) for 1days
  * The role is `DEV`
  * The job is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk) for [1days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23329%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Job was finished in 27 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#329](https://github.com/timelesslounge/timelessis/issues/329) is now out of scope

**Comment by 0crat** [comment]
Job [#329](https://github.com/timelesslounge/timelessis/issues/329) is not in the agenda of @krzyk[/z](https://www.0crat.com/u/krzyk), can't inspect

**Comment by krzyk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/329#issuecomment-465992883))

@krzyk This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#329](https://github.com/timelesslounge/timelessis/issues/329) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 24min
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will receive 35 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23329%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/timelesslounge/timelessis/issues/329#issuecomment-466299064))

@ypshenychka There is no quality review for [#329](https://github.com/timelesslounge/timelessis/issues/329), no performer

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#526](https://github.com/timelesslounge/timelessis/issues/526) is still not solved; solved: [#358](https://github.com/timelesslounge/timelessis/issues/358).
