### ISSUE TITLE
views.py:2-9: Continue implementing edit() method, using...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#338]
The puzzle `255-fcaee2d2` from #255 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/38dfc0b767a518dab65f400a41ca993e445c54b1/timeless/roles/views.py#L2-L9

The puzzle was created by @ekondrashev on 19-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#338](https://github.com/timelesslounge/timelessis/issues/338) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#338](https://github.com/timelesslounge/timelessis/issues/338) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/1f467f3d-0518-4f71-9594-e572ad1c79f1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vryazanov** [comment]
@0crat wait for #310 
To implement edit view correctly, I need to reuse some base methods from PR for #310

**Comment by 0crat** [comment]
> @0crat wait for #310 To implement edit view correctly, I need to reuse some base methods from P... ([here](https://github.com/timelesslounge/timelessis/issues/338#issuecomment-466690401))

@vryazanov The impediment for [#338](https://github.com/timelesslounge/timelessis/issues/338) was registered successfully by @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by vryazanov** [comment]
@0crat wait for https://github.com/timelesslounge/timelessis/pull/445
There is generic `UpdateView` implemented which I need to use for resolving this task

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/timelesslounge/timelessis/pull/445 There is generic `UpdateVi... ([here](https://github.com/timelesslounge/timelessis/issues/338#issuecomment-468899334))

@vryazanov Job [#338](https://github.com/timelesslounge/timelessis/issues/338) is already on hold

**Comment by emilianodellacasa** [comment]
@vryazanov  #445 has been merged now, please take care of this one as it is high priority

**Comment by 0pdd** [comment]
The puzzle `255-fcaee2d2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#494](https://github.com/timelesslounge/timelessis/issues/494) is still not solved.

**Comment by 0crat** [comment]
The job [#338](https://github.com/timelesslounge/timelessis/issues/338) is now out of scope

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/338#issuecomment-471071028))

@ypshenychka This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#338](https://github.com/timelesslounge/timelessis/issues/338) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 1days
  * @vryazanov[/z](https://www.0crat.com/u/vryazanov) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23338%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#494](https://github.com/timelesslounge/timelessis/issues/494) is solved here.
