### ISSUE TITLE
views.py:2-4: Implement activate() methods. Update html...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#339]
The puzzle `232-1f9157a6` from #232 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/f89c21c9a2d2fcde3b274bd1087678ded65bf848/timeless/auth/views.py#L2-L4

The puzzle was created by Paulo Lobo on 20-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#339](https://github.com/timelesslounge/timelessis/issues/339) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#339](https://github.com/timelesslounge/timelessis/issues/339) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/1c36187b-1fab-471a-83e4-eb8fdb9d16b0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@emilianodellacasa 
>Architect must document what activate() method must do.

So, what should activate do?

**Comment by emilianodellacasa** [comment]
@ammaratef45 'activate()' is a function that set the `account_status` of an employee to True (default is false, when created), allowing the employee to login to the webapp

**Comment by ammaratef45** [comment]
@emilianodellacasa How an employee should be activated? Does he provide something like an activation code?

**Comment by emilianodellacasa** [comment]
@ammaratef45 A mail is sent to the employee with an activation link. However, there should also be a link in the employee list page to manually activate/deactivate employees

**Comment by 0pdd** [comment]
The puzzle `232-1f9157a6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#339](https://github.com/timelesslounge/timelessis/issues/339) is not in the agenda of @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), can't inspect

**Comment by 0crat** [comment]
The job [#339](https://github.com/timelesslounge/timelessis/issues/339) is now out of scope

**Comment by ammaratef45** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/339#issuecomment-466737512))

@ammaratef45 This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#339](https://github.com/timelesslounge/timelessis/issues/339) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 8hr
  * @ammaratef45[/z](https://www.0crat.com/u/ammaratef45) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23339%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ammaratef45** [comment]
@ypshenychka zerocrat is doing it again :laughing:

**Comment by ypshenychka** [comment]
@ammaratef45 There was a [notification](https://github.com/timelesslounge/timelessis/issues/339#issuecomment-466700966), so 0crat is doing his best :)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
