### ISSUE TITLE
views.py:5-7: Continue implementing forgot_password...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#340]
The puzzle `232-7d302a24` from #232 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/f89c21c9a2d2fcde3b274bd1087678ded65bf848/timeless/auth/views.py#L5-L7

The puzzle was created by Paulo Lobo on 20-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#340](https://github.com/timelesslounge/timelessis/issues/340) is now in scope, role is `DEV`

**Comment by emilianodellacasa** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu  ([here](https://github.com/timelesslounge/timelessis/issues/340#issuecomment-465732961))

@emilianodellacasa The job [#340](https://github.com/timelesslounge/timelessis/issues/340) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/c33da447-3db6-4fde-95c6-9f99771f9035); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `232-7d302a24` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#370](https://github.com/timelesslounge/timelessis/issues/370) is still not solved.

**Comment by 0crat** [comment]
Job was finished in 36 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#340](https://github.com/timelesslounge/timelessis/issues/340) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389) are still not solved; solved: [#370](https://github.com/timelesslounge/timelessis/issues/370).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388) are still not solved; solved: [#370](https://github.com/timelesslounge/timelessis/issues/370), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#387](https://github.com/timelesslounge/timelessis/issues/387), [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved; solved: [#370](https://github.com/timelesslounge/timelessis/issues/370), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved; solved: [#370](https://github.com/timelesslounge/timelessis/issues/370), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#464](https://github.com/timelesslounge/timelessis/issues/464) is still not solved; solved: [#370](https://github.com/timelesslounge/timelessis/issues/370), [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389), [#465](https://github.com/timelesslounge/timelessis/issues/465).
