### ISSUE TITLE
it_manager_privilages_test.py:125-127: Add check that...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#341]
The puzzle `298-a994a93f` from #298 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/3e422449e912cef4c75075defcac7822a9f4eb14/tests/integration/it_manager_privilages_test.py#L125-L127

The puzzle was created by Paulo Lobo on 20-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#341](https://github.com/timelesslounge/timelessis/issues/341) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#341](https://github.com/timelesslounge/timelessis/issues/341) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/71cd6c58-250d-4717-a1e7-a26b23cb4b53); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `298-a994a93f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#397](https://github.com/timelesslounge/timelessis/issues/397) is still not solved.

**Comment by 0crat** [comment]
Job [#341](https://github.com/timelesslounge/timelessis/issues/341) is not in the agenda of @vryazanov[/z](https://www.0crat.com/u/vryazanov), can't inspect

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#341](https://github.com/timelesslounge/timelessis/issues/341) is now out of scope

**Comment by vryazanov** [comment]
@0crat refuse

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#481](https://github.com/timelesslounge/timelessis/issues/481) is still not solved; solved: [#397](https://github.com/timelesslounge/timelessis/issues/397).
