### ISSUE TITLE
sync.py:4-6: Move this logic from sync_location method to...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#343]
The puzzle `187-9c4d2494` from #187 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/a21a759d7896e9c0b9b7a99f7102689305b71716/timeless/sync/sync.py#L4-L6

The puzzle was created by Vlad Arefev on 19-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#343](https://github.com/timelesslounge/timelessis/issues/343) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#343](https://github.com/timelesslounge/timelessis/issues/343) assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/8676a494-3bd1-47e5-b162-e45da46098a1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vladarefiev[/z](https://www.0crat.com/u/vladarefiev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vladarefiev** [comment]
@0crat wait for https://github.com/timelesslounge/timelessis/pull/420 will be reviewed

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/timelesslounge/timelessis/pull/420 will be reviewed ([here](https://github.com/timelesslounge/timelessis/issues/343#issuecomment-467961908))

@vladarefiev The impediment for [#343](https://github.com/timelesslounge/timelessis/issues/343) was registered successfully by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0pdd** [comment]
The puzzle `187-9c4d2494` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#453](https://github.com/timelesslounge/timelessis/issues/453) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#343](https://github.com/timelesslounge/timelessis/issues/343) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#566](https://github.com/timelesslounge/timelessis/issues/566) is still not solved.
