### ISSUE TITLE
it_sync_tables_test.py:9-11: Implement integration tests...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#345]
The puzzle `187-1dd3a479` from #187 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/a21a759d7896e9c0b9b7a99f7102689305b71716/tests/integration/sync/it_sync_tables_test.py#L9-L11

The puzzle was created by Vlad Arefev on 19-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#345](https://github.com/timelesslounge/timelessis/issues/345) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#345](https://github.com/timelesslounge/timelessis/issues/345) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/3861bdea-88aa-4e1f-9963-d3a4e6103368); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by emilianodellacasa** [comment]
@krzyk closing this as it's duplicated by #342

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#345](https://github.com/timelesslounge/timelessis/issues/345) is now out of scope

**Comment by ypshenychka** [comment]
@krzyk No work was done here. right?

**Comment by krzyk** [comment]
@ypshenychka correct

**Comment by ypshenychka** [comment]
@krzyk thanks

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
