### ISSUE TITLE
views.py:2-4: Continue implementing Create, Edit and...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#348]
The puzzle `57-cb8584ba` from #57 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/068d6df259873ecbbb6afc8d3a658fb18ff70a77/timeless/employees/views.py#L2-L4

The puzzle was created by @rultor on 20-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#348](https://github.com/timelesslounge/timelessis/issues/348) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#348](https://github.com/timelesslounge/timelessis/issues/348) assigned to @vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/c29cd517-2373-410f-b246-3e792e8a0f9c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `57-cb8584ba` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#411](https://github.com/timelesslounge/timelessis/issues/411), [#412](https://github.com/timelesslounge/timelessis/issues/412), [#413](https://github.com/timelesslounge/timelessis/issues/413) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#348](https://github.com/timelesslounge/timelessis/issues/348) is not in the agenda of @vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov), can't inspect

**Comment by 0crat** [comment]
The job [#348](https://github.com/timelesslounge/timelessis/issues/348) is now out of scope

**Comment by ypshenychka** [comment]
@VladimirRyzhkov According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed

Please add reference to corresponding PR (you can do this by mentioning this issue number in PR's description).

**Comment by ypshenychka** [comment]
@VladimirRyzhkov it's here now, thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#412](https://github.com/timelesslounge/timelessis/issues/412), [#413](https://github.com/timelesslounge/timelessis/issues/413), [#503](https://github.com/timelesslounge/timelessis/issues/503) are still not solved; solved: [#411](https://github.com/timelesslounge/timelessis/issues/411).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#413](https://github.com/timelesslounge/timelessis/issues/413), [#503](https://github.com/timelesslounge/timelessis/issues/503), [#529](https://github.com/timelesslounge/timelessis/issues/529) are still not solved; solved: [#411](https://github.com/timelesslounge/timelessis/issues/411), [#412](https://github.com/timelesslounge/timelessis/issues/412).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
