### ISSUE TITLE
Set up Dockerfile

### ISSUE THREAD

**Issue by vladarefiev** [timelesslounge/timelessis#35]
To avoid project deployment on a personal OS, I suggest to set up Dockerfile with `docker-compose.yml`. 

- In Dockerfile we should make all preparations for our application container (set up python, install dependencies, etc)
- `docker-compose.yml` should contain application and postgres containers at this moment.
- Command `docker-compose up` should run flask application.

**Comment by vryazanov** [comment]
@emilianodellacasa I understand that this task is out of scope, but I'll anyway prepare PR for this. Just I cannot start local environment without docker. If you are against, I just will keep docker settings under local git ignore.

**Comment by emilianodellacasa** [comment]
@0crat assign @vryazanov

**Comment by 0crat** [comment]
Job [#35](https://github.com/timelesslounge/timelessis/issues/35) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign @vryazanov  ([here](https://github.com/timelesslounge/timelessis/issues/35#issuecomment-461730797))

@emilianodellacasa The job [#35](https://github.com/timelesslounge/timelessis/issues/35) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/801fef52-b6ec-4671-8b0d-ef0d3e2a82e9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by vryazanov** [comment]
@vladarefiev It's merged, pls have a look

**Comment by vladarefiev** [comment]
@vryazanov  Great, thanks

**Comment by 0crat** [comment]
Job was finished in 7 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#35](https://github.com/timelesslounge/timelessis/issues/35) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
