### ISSUE TITLE
views.py:5-8: Continue implementing List to enable...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#357]
The puzzle `57-294a904f` from #57 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/452ce9bd951a96c3cd8bb3ae5f864f03e932ad13/timeless/employees/views.py#L5-L8

The puzzle was created by Boris Kuzmic on 21-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#357](https://github.com/timelesslounge/timelessis/issues/357) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#357](https://github.com/timelesslounge/timelessis/issues/357) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/4e07fc94-3645-4e67-8524-e1b3bdff5f18); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/357#issuecomment-469527483))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#357](https://github.com/timelesslounge/timelessis/issues/357), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#357](https://github.com/timelesslounge/timelessis/issues/357) assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/7953de66-9652-4155-b9e3-50c2068d67ea); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vladarefiev[/z](https://www.0crat.com/u/vladarefiev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vladarefiev** [comment]
@0crat wait till #536 is not merged

**Comment by 0pdd** [comment]
The puzzle `57-294a904f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#542](https://github.com/timelesslounge/timelessis/issues/542) is still not solved.

**Comment by 0crat** [comment]
> @0crat wait till #536 is not merged ([here](https://github.com/timelesslounge/timelessis/issues/357#issuecomment-472075304))

@vladarefiev The impediment for [#357](https://github.com/timelesslounge/timelessis/issues/357) was registered successfully by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#357](https://github.com/timelesslounge/timelessis/issues/357) is not in the agenda of @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), can't inspect

**Comment by 0crat** [comment]
The job [#357](https://github.com/timelesslounge/timelessis/issues/357) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/timelesslounge/timelessis/issues/357#issuecomment-472558688))

@ypshenychka You @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) need to have one of these roles in order to do "Complete `QA` review": `ARC`, `QA`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by vladarefiev** [comment]
@emilianodellacasa may be you could do this?

**Comment by emilianodellacasa** [comment]
@0crat quality good

**Comment by emilianodellacasa** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/timelesslounge/timelessis/issues/357#issuecomment-472572946))

@emilianodellacasa The job [#357](https://github.com/timelesslounge/timelessis/issues/357) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/f5f49110-eaa3-45b9-ad4f-c6c117cc1013); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/timelesslounge/timelessis/issues/357#issuecomment-472572946))

@emilianodellacasa Job `gh:timelesslounge/timelessis#357` already assigned to @emilianodellacasa, can't assign to @vladarefiev

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@0crat off

**Comment by 0crat** [comment]
> @0crat off ([here](https://github.com/timelesslounge/timelessis/issues/357#issuecomment-472756250))

@emilianodellacasa Can't understand "off", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by emilianodellacasa** [comment]
@0crat out

**Comment by 0crat** [comment]
Job was finished in 13 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/timelesslounge/timelessis/issues/357#issuecomment-472757724))

@emilianodellacasa The job [#357](https://github.com/timelesslounge/timelessis/issues/357) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@emilianodellacasa It's still in my agenda

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
