### ISSUE TITLE
Puzzle #292 is not clear enough for me to work on it

### ISSUE THREAD

**Issue by salgadobreno** [timelesslounge/timelessis#360]
Puzzle #292 is too vague, it says:

         @todo #186:30min excluding greeting_by_time is temporary solution. 
          forms.BaseModelForm can't handle JSON field. 
          Need to research how to fix this case and fix it.

Commenting the line that excludes `greeting_by_time` does not break any test nor it breaks getting the app running or what action the exclusions is for. I don't know what the "temporary solution" is solving.
It says `forms.BaseModelForm` can't handle JSON field but I don't understand how.
"Need to research how to fix this case and fix it" is clearly a vague phrase. I'd need a "case" at least to work from.

Please clarify this puzzle.

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@salgadobreno Let's ask @vladarefiev what had in mind

**Comment by vladarefiev** [comment]
@salgadobreno @emilianodellacasa Sorry, guys. I have lost this conversation. If now it works, let's close it, I think.

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#360` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
