### ISSUE TITLE
Setup Integration tests for models

### ISSUE THREAD

**Issue by bkuzmic** [timelesslounge/timelessis#37]
In order to properly test models, we will have to setup integration tests with database.
Here is an example of how to do this:
https://pypi.org/project/pytest-flask-sqlalchemy/

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#37](https://github.com/timelesslounge/timelessis/issues/37) is now out of scope

**Comment by ypshenychka** [comment]
@bkuzmic According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Problem reporter and problem solver are two different persons

Please confirm you'll ask ARC to reassign the issue if such situation happens in future.

**Comment by bkuzmic** [comment]
@ypshenychka I confirm.

**Comment by ypshenychka** [comment]
@bkuzmic thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
