### ISSUE TITLE
auth.py:20-24: Continue implementing forgot_password. End...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#370]
The puzzle `340-5247f867` from #340 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/cf59ec4ad667932fdc84bb6fd42348924ff25dab/timeless/auth/auth.py#L20-L24

The puzzle was created by marceloamadeu on 21-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#370](https://github.com/timelesslounge/timelessis/issues/370) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#370](https://github.com/timelesslounge/timelessis/issues/370) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/b3ebef57-1dc9-4234-b5c9-94df6189bb33); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#370` already assigned to @paulodamaso, can't assign to @paulodamaso

**Comment by 0pdd** [comment]
The puzzle `340-5247f867` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389) are still not solved.

**Comment by 0crat** [comment]
Job was finished in 37 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#370](https://github.com/timelesslounge/timelessis/issues/370) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388) are still not solved; solved: [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#387](https://github.com/timelesslounge/timelessis/issues/387), [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved; solved: [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved; solved: [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#464](https://github.com/timelesslounge/timelessis/issues/464) is still not solved; solved: [#387](https://github.com/timelesslounge/timelessis/issues/387), [#388](https://github.com/timelesslounge/timelessis/issues/388), [#389](https://github.com/timelesslounge/timelessis/issues/389), [#465](https://github.com/timelesslounge/timelessis/issues/465).
