### ISSUE TITLE
it_reservations_test.py:13-16: Find out why form...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#380]
The puzzle `235-8ebed21e` from #235 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/90e103893e65f4c3367745ef1000e99c07c98d94/tests/integration/it_reservations_test.py#L13-L16

The puzzle was created by Vatavuk on 18-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu  ([here](https://github.com/timelesslounge/timelessis/issues/380#issuecomment-466557795))

@emilianodellacasa The job [#380](https://github.com/timelesslounge/timelessis/issues/380) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/11a4cc1e-c3ab-4a18-b66d-f6024c8192e3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job [#380](https://github.com/timelesslounge/timelessis/issues/380) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `235-8ebed21e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#434](https://github.com/timelesslounge/timelessis/issues/434) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#380](https://github.com/timelesslounge/timelessis/issues/380) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#492](https://github.com/timelesslounge/timelessis/issues/492) is still not solved; solved: [#434](https://github.com/timelesslounge/timelessis/issues/434).
