### ISSUE TITLE
views.py:72-75: Implement tests for this method. Tests...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#385]
The puzzle `399-f11dbfdc` from #399 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/fbcf2bf86023cb519fb0f8a3f09ff448f1ddd2f8/timeless/auth/views.py#L72-L75

The puzzle was created by rultor on 23-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#385](https://github.com/timelesslounge/timelessis/issues/385) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#385](https://github.com/timelesslounge/timelessis/issues/385) assigned to @vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/d4c5748e-824b-47aa-8843-40f9788f27a4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by VladimirRyzhkov** [comment]
@0pdd refuse

**Comment by 0pdd** [comment]
> @0pdd refuse

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by VladimirRyzhkov** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/385#issuecomment-469678566))

@VladimirRyzhkov The user @vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov) resigned from [#385](https://github.com/timelesslounge/timelessis/issues/385), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov)

**Comment by 0crat** [comment]
The job [#385](https://github.com/timelesslounge/timelessis/issues/385) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/27dd035f-2b34-402c-82d8-9f0bcca9af01); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@0pdd the puzzle [#485](https://github.com/timelesslounge/timelessis/issues/485) is still not solved.

**Comment by paulodamaso** [comment]
@emilianodellacasa I've forgot to remoe the `@todo` (again), please merge this last commit.

**Comment by 0pdd** [comment]
The puzzle `399-f11dbfdc` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#385](https://github.com/timelesslounge/timelessis/issues/385) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#385](https://github.com/timelesslounge/timelessis/issues/385) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#485](https://github.com/timelesslounge/timelessis/issues/485) is solved here.
