### ISSUE TITLE
views.py:9-12: Continue implementing...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#386]
The puzzle `97-f1e01378` from #97 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/ff5e47b062f47f1c7a4cec5e3928305f5342157c/timeless/schemetypes/views.py#L9-L12

The puzzle was created by Boris Kuzmic on 22-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#386](https://github.com/timelesslounge/timelessis/issues/386) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#386](https://github.com/timelesslounge/timelessis/issues/386) assigned to @vryazanov[/z](https://www.0crat.com/u/vryazanov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/58f0838d-4e8a-4fee-8c71-42775f5e664b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@0pdd the puzzle [#455](https://github.com/timelesslounge/timelessis/issues/455) is still not solved.

**Comment by 0pdd** [comment]
The puzzle `97-f1e01378` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vryazanov[/z](https://www.0crat.com/u/vryazanov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#386](https://github.com/timelesslounge/timelessis/issues/386) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vryazanov[/z](https://www.0crat.com/u/vryazanov)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#568](https://github.com/timelesslounge/timelessis/issues/568) is still not solved.
