### ISSUE TITLE
it_auth_test.py:78-80: Forgot password routine. Create a...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#388]
The puzzle `370-7fa43b29` from #370 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/9de13c38c8fcb4703f8f9305b826b607d5f809d7/tests/integration/it_auth_test.py#L78-L80

The puzzle was created by Paulo Lobo on 22-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#388](https://github.com/timelesslounge/timelessis/issues/388) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#388](https://github.com/timelesslounge/timelessis/issues/388) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/77d0a4ac-df59-4dc5-9253-cf06e61dcefa); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `370-7fa43b29` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#464](https://github.com/timelesslounge/timelessis/issues/464), [#465](https://github.com/timelesslounge/timelessis/issues/465) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#388](https://github.com/timelesslounge/timelessis/issues/388) is not in the agenda of @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), can't inspect

**Comment by 0crat** [comment]
The job [#388](https://github.com/timelesslounge/timelessis/issues/388) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#464](https://github.com/timelesslounge/timelessis/issues/464) is still not solved; solved: [#465](https://github.com/timelesslounge/timelessis/issues/465).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
