### ISSUE TITLE
auth.py:5-10: Decouple routines from database. Database...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#389]
The puzzle `370-7db59df9` from #370 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/9de13c38c8fcb4703f8f9305b826b607d5f809d7/timeless/auth/auth.py#L5-L10

The puzzle was created by Paulo Lobo on 23-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#389](https://github.com/timelesslounge/timelessis/issues/389) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#389](https://github.com/timelesslounge/timelessis/issues/389) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/0248a504-49b1-40b9-a8a9-c91c2556c657); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@emilianodellacasa I thini that one have to be rethinked too, based on decisions made on #270

**Comment by ammaratef45** [comment]
@paulodamaso I've been following #270 and I found you were using factories.
Is that the decision or something else?

**Comment by emilianodellacasa** [comment]
@paulodamaso @ammaratef45 Correct, we better close this one, sorry about that

**Comment by ammaratef45** [comment]
@emilianodellacasa shouldn't we delete the puzzle?

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@ammaratef45 you are right of course, please submit a PR to remove the puzzle

**Comment by ammaratef45** [comment]
@emilianodellacasa Done, please check it.

**Comment by 0crat** [comment]
GitHub issue is still open, won't close

**Comment by 0pdd** [comment]
The puzzle `370-7db59df9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4154210c-14b1-4b35-b303-3542e1c565a6, thread: pool-4-thread-7
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:timelesslounge/timelessis#389] declared for identity constraint of element "verbosity".
```

[0.43.1](https://github.com/zerocracy/farm): CID: [9c371737-1394-4e21-a149-3fb284b9184b](https://www.0crat.com/footprint/CF9LG1YCA/9c371737-1394-4e21-a149-3fb284b9184b), Type: "Close job"

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Job [#389](https://github.com/timelesslounge/timelessis/issues/389) is not in the agenda of @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), can't inspect

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#389](https://github.com/timelesslounge/timelessis/issues/389) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
