### ISSUE TITLE
owner_privileges.py:7-10: Implement owner privileges...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#392]
The puzzle `242-e919dfa9` from #242 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/1585cede336dc21cea9fdfb2227caa2abaf1f041/timeless/access_control/owner_privileges.py#L7-L10

The puzzle was created by rultor on 24-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#392](https://github.com/timelesslounge/timelessis/issues/392) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#392](https://github.com/timelesslounge/timelessis/issues/392) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/f6adff56-4ebb-436f-84ea-f280439d0eec); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@emilianodellacasa What tests should I uncomment?

**Comment by emilianodellacasa** [comment]
@ammaratef45 They are in 'tests/integration/it_owner_privileges_test.py'

**Comment by ammaratef45** [comment]
@emilianodellacasa They are all uncommented already!!

**Comment by emilianodellacasa** [comment]
@ammaratef45 let me check and also ask @paulodamaso who created the issue

**Comment by emilianodellacasa** [comment]
@ammaratef45 I see there are skipped tests in https://github.com/timelesslounge/timelessis/blob/master/tests/integration/it_owner_privileges_test.py please double check

**Comment by ammaratef45** [comment]
@emilianodellacasa I must look dumb now 😆 
Sorry, was searching about comments and didn't try looking for the skip.

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@0crat wait for #397

**Comment by 0crat** [comment]
> @0crat wait for #397  ([here](https://github.com/timelesslounge/timelessis/issues/392#issuecomment-469984214))

@ammaratef45 The impediment for [#392](https://github.com/timelesslounge/timelessis/issues/392) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by ammaratef45** [comment]
@emilianodellacasa @vryazanov tests were removed in 96eafff by @vryazanov 
The tests now ignore the role of the user completely, why it's implemented this way?

**Comment by vryazanov** [comment]
@ammaratef45 if user is not `owner` then code from `timeless/access_control/owner_privileges.py` will not be executed
so it doesnt make any sense to set role type

**Comment by ammaratef45** [comment]
@vryazanov If I understood right, that means this puzzle makes no sense too, right?

**Comment by vryazanov** [comment]
@ammaratef45 hm, i think yes, since it's aleady implemented

**Comment by ammaratef45** [comment]
@emilianodellacasa what you think? I will only delete the puzzle (which isn't something I should be paid for).

**Comment by emilianodellacasa** [comment]
@ammaratef45 It makes sense, please do that

**Comment by 0pdd** [comment]
The puzzle `242-e919dfa9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#392](https://github.com/timelesslounge/timelessis/issues/392) is now out of scope

**Comment by ypshenychka** [comment]
@ammaratef45 No work was done here, right?

**Comment by ammaratef45** [comment]
@ypshenychka yes

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
