### ISSUE TITLE
models.py:24-25: Need to find nice way to understand what...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#397]
The puzzle `341-9c211a77` from #341 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/fe0ed422bf4ba7343643b5475c38d936fea3788d/timeless/roles/models.py#L24-L25

The puzzle was created by Vadim Ryazanov on 24-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#397](https://github.com/timelesslounge/timelessis/issues/397) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#397](https://github.com/timelesslounge/timelessis/issues/397) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/fd31975c-904a-4951-8e38-5adb3789b31a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@vryazanov Do you want to use a `type` filed instead of the name? what is the purpose?

**Comment by vryazanov** [comment]
@ammaratef45 I just dont like the idea to understand the role by free text column called name :)
I believe we should use something like this: https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#sqlalchemy_utils.types.choice.ChoiceType
and possible options for `name` should be fixed

**Comment by vryazanov** [comment]
@ammaratef45 I mean that, for example, I as administrator can create a role named `master` and our logic will be broken since we are using hardcoded value `Master` (capital case)

**Comment by ammaratef45** [comment]
@vryazanov Now I totally got you 😆 
You are right 👍

**Comment by 0crat** [comment]
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ammaratef45** [comment]
@0crat wait for code review

**Comment by 0crat** [comment]
> @0crat wait for code review ([here](https://github.com/timelesslounge/timelessis/issues/397#issuecomment-469988223))

@ammaratef45 The impediment for [#397](https://github.com/timelesslounge/timelessis/issues/397) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `341-9c211a77` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#481](https://github.com/timelesslounge/timelessis/issues/481) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#397](https://github.com/timelesslounge/timelessis/issues/397) is not in the agenda of @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), can't inspect

**Comment by 0crat** [comment]
The job [#397](https://github.com/timelesslounge/timelessis/issues/397) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
