### ISSUE TITLE
Employee Model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#4]
Employee model represents the employee of each company and the account accessing the webapp.

Those are the base attributes:

- Id
- First Name
- Last Name
- Username
- Phone Number
- Birth Date
- Registration Date
- Account Status (Activated / Not Activated)
- User Status (Working / Fired)
- Email
- Password (hashed+salted)
- Individual pin-code (4 digits, unique key)
- Comment
- company_id
- created_on
- updated_on

Employees should have its own management pages to list, create, edit and delete them. In the index page it should be possible to sort and filter for every column. Other possible actions on the Employees should be:

- Activate/Deactivate button;
- Fire button;

The page/window for creating a new User must contain fields for entering all of User's attributes, except

- Registration Date - set automatically (current date)
- Account Status - the default is Not Activated;
- User Status - the default is Working
- Password - generated automatically and sent to the User’s email (specified in the field "Email")
- Individual pin-code - is similar to “Password”. PIN codes of Users must be unique within the network of spots they are involved in

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#149](https://github.com/timelesslounge/timelessis/issues/149), [#57](https://github.com/timelesslounge/timelessis/issues/57) are still not solved; solved: [#58](https://github.com/timelesslounge/timelessis/issues/58).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#283](https://github.com/timelesslounge/timelessis/issues/283), [#57](https://github.com/timelesslounge/timelessis/issues/57) are still not solved; solved: [#149](https://github.com/timelesslounge/timelessis/issues/149), [#58](https://github.com/timelesslounge/timelessis/issues/58).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#283](https://github.com/timelesslounge/timelessis/issues/283), [#348](https://github.com/timelesslounge/timelessis/issues/348), [#57](https://github.com/timelesslounge/timelessis/issues/57) are still not solved; solved: [#149](https://github.com/timelesslounge/timelessis/issues/149), [#58](https://github.com/timelesslounge/timelessis/issues/58).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#283](https://github.com/timelesslounge/timelessis/issues/283), [#348](https://github.com/timelesslounge/timelessis/issues/348), [#357](https://github.com/timelesslounge/timelessis/issues/357) are still not solved; solved: [#149](https://github.com/timelesslounge/timelessis/issues/149), [#57](https://github.com/timelesslounge/timelessis/issues/57), [#58](https://github.com/timelesslounge/timelessis/issues/58).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#283](https://github.com/timelesslounge/timelessis/issues/283), [#357](https://github.com/timelesslounge/timelessis/issues/357), [#411](https://github.com/timelesslounge/timelessis/issues/411), [#412](https://github.com/timelesslounge/timelessis/issues/412), [#413](https://github.com/timelesslounge/timelessis/issues/413) are still not solved; solved: [#149](https://github.com/timelesslounge/timelessis/issues/149), [#348](https://github.com/timelesslounge/timelessis/issues/348), [#57](https://github.com/timelesslounge/timelessis/issues/57), [#58](https://github.com/timelesslounge/timelessis/issues/58).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#357](https://github.com/timelesslounge/timelessis/issues/357), [#411](https://github.com/timelesslounge/timelessis/issues/411), [#412](https://github.com/timelesslounge/timelessis/issues/412), [#413](https://github.com/timelesslounge/timelessis/issues/413), [#460](https://github.com/timelesslounge/timelessis/issues/460) are still not solved; solved: [#149](https://github.com/timelesslounge/timelessis/issues/149), [#283](https://github.com/timelesslounge/timelessis/issues/283), [#348](https://github.com/timelesslounge/timelessis/issues/348), [#57](https://github.com/timelesslounge/timelessis/issues/57), [#58](https://github.com/timelesslounge/timelessis/issues/58).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#357](https://github.com/timelesslounge/timelessis/issues/357), [#412](https://github.com/timelesslounge/timelessis/issues/412), [#413](https://github.com/timelesslounge/timelessis/issues/413), [#460](https://github.com/timelesslounge/timelessis/issues/460), [#503](https://github.com/timelesslounge/timelessis/issues/503) are still not solved; solved: [#149](https://github.com/timelesslounge/timelessis/issues/149), [#283](https://github.com/timelesslounge/timelessis/issues/283), [#348](https://github.com/timelesslounge/timelessis/issues/348), [#411](https://github.com/timelesslounge/timelessis/issues/411), [#57](https://github.com/timelesslounge/timelessis/issues/57), [#58](https://github.com/timelesslounge/timelessis/issues/58).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#357](https://github.com/timelesslounge/timelessis/issues/357), [#413](https://github.com/timelesslounge/timelessis/issues/413), [#460](https://github.com/timelesslounge/timelessis/issues/460), [#503](https://github.com/timelesslounge/timelessis/issues/503), [#529](https://github.com/timelesslounge/timelessis/issues/529) are still not solved; solved: [#149](https://github.com/timelesslounge/timelessis/issues/149), [#283](https://github.com/timelesslounge/timelessis/issues/283), [#348](https://github.com/timelesslounge/timelessis/issues/348), [#411](https://github.com/timelesslounge/timelessis/issues/411), [#412](https://github.com/timelesslounge/timelessis/issues/412), [#57](https://github.com/timelesslounge/timelessis/issues/57), [#58](https://github.com/timelesslounge/timelessis/issues/58).

**Comment by 0pdd** [comment]
@emilianodellacasa 5 puzzles [#413](https://github.com/timelesslounge/timelessis/issues/413), [#460](https://github.com/timelesslounge/timelessis/issues/460), [#503](https://github.com/timelesslounge/timelessis/issues/503), [#529](https://github.com/timelesslounge/timelessis/issues/529), [#542](https://github.com/timelesslounge/timelessis/issues/542) are still not solved; solved: [#149](https://github.com/timelesslounge/timelessis/issues/149), [#283](https://github.com/timelesslounge/timelessis/issues/283), [#348](https://github.com/timelesslounge/timelessis/issues/348), [#357](https://github.com/timelesslounge/timelessis/issues/357), [#411](https://github.com/timelesslounge/timelessis/issues/411), [#412](https://github.com/timelesslounge/timelessis/issues/412), [#57](https://github.com/timelesslounge/timelessis/issues/57), [#58](https://github.com/timelesslounge/timelessis/issues/58).
