### ISSUE TITLE
synced_customer.py:6-8: Continue synchronization between...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#409]
The puzzle `262-3c8226cd` from #262 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/3436473f7e64740fa08a15a2aab9831fa10c3dff/timeless/sync/synced_customer.py#L6-L8

The puzzle was created by rultor on 26-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#409](https://github.com/timelesslounge/timelessis/issues/409) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#409](https://github.com/timelesslounge/timelessis/issues/409) assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/cabc6fbd-e94b-479e-ba97-f79abb5e7c93); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `262-3c8226cd` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#531](https://github.com/timelesslounge/timelessis/issues/531) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#409](https://github.com/timelesslounge/timelessis/issues/409) is not in the agenda of @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), can't inspect

**Comment by 0crat** [comment]
The job [#409](https://github.com/timelesslounge/timelessis/issues/409) is now out of scope

**Comment by vladarefiev** [comment]
@ypshenychka ping

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
