### ISSUE TITLE
views.py:28-30: Continue implementing Edit view when...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#411]
The puzzle `348-77a170af` from #348 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/2440bd230b9e60f131f0ed8c0968bf3f80564d45/timeless/employees/views.py#L28-L30

The puzzle was created by VladimirRyzhkov on 26-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@0crat assign @ekondrashev

**Comment by 0crat** [comment]
Job [#411](https://github.com/timelesslounge/timelessis/issues/411) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign @ekondrashev  ([here](https://github.com/timelesslounge/timelessis/issues/411#issuecomment-469217528))

@emilianodellacasa The job [#411](https://github.com/timelesslounge/timelessis/issues/411) assigned to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/1ae41dcd-3f11-492f-b49f-86f7bfc53e56); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `348-77a170af` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#503](https://github.com/timelesslounge/timelessis/issues/503) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ekondrashev[/z](https://www.0crat.com/u/ekondrashev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#411](https://github.com/timelesslounge/timelessis/issues/411) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ekondrashev[/z](https://www.0crat.com/u/ekondrashev)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
