### ISSUE TITLE
views.py:43-48: This form currently cannot save pictures....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#415]
The puzzle `205-afef22cc` from #205 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/7f4c469bd1082eae78ec436cecf6f568bcc91fa2/timeless/restaurants/table_shapes/views.py#L43-L48

The puzzle was created by Eugene Kondrashev on 26-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `205-afef22cc` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#415` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#415](https://github.com/timelesslounge/timelessis/issues/415) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#415](https://github.com/timelesslounge/timelessis/issues/415) assigned to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/1b19c1fc-46e6-4346-a15f-1b2d14d128e3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by vladarefiev** [comment]
@emilianodellacasa I vote for getting rid of this one https://github.com/timelesslounge/timelessis/blob/master/timeless/views.py#L292

I suggest to use factories and real queries.

**Comment by vladarefiev** [comment]
@emilianodellacasa I have got two questions:
- I can find only this puzzle in codebase https://github.com/timelesslounge/timelessis/blob/master/timeless/restaurants/table_shapes/views.py#L40 is this it?
- We have to upload image by providing image or by url?

**Comment by amihaiemil** [comment]
@vladarefiev 
The actual puzzle for this ticket has been accidentally replaced with the old and obsolete puzzle you found, see [this discussion](https://github.com/timelesslounge/timelessis/issues/286#issuecomment-467904886).

I guess you can just proceed with this task. I removed the old puzzle in my branch :)

**Comment by amihaiemil** [comment]
@emilianodellacasa well, I guess this Issue here and mine ([here](https://github.com/timelesslounge/timelessis/issues/286)) are basically the same task comming from different directions. WDYT?

**Comment by vladarefiev** [comment]
@amihaiemil I see, thanks. I can start now

**Comment by vladarefiev** [comment]
@emilianodellacasa Pls close it, It was done here - https://github.com/timelesslounge/timelessis/pull/461/files

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#415](https://github.com/timelesslounge/timelessis/issues/415) is not in the agenda of @vladarefiev[/z](https://www.0crat.com/u/vladarefiev), can't inspect

**Comment by 0crat** [comment]
The job [#415](https://github.com/timelesslounge/timelessis/issues/415) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vladarefiev[/z](https://www.0crat.com/u/vladarefiev)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
