### ISSUE TITLE
test_items.py:9-12: Factories session problem. Sometimes...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#417]
The puzzle `270-9b75992d` from #270 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/394730a21aafbcc12b3a3e0c99767c51c58be287/tests/view/items/test_items.py#L9-L12

The puzzle was created by Paulo Lobo on 26-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#417](https://github.com/timelesslounge/timelessis/issues/417) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#417](https://github.com/timelesslounge/timelessis/issues/417) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/732dd6a3-ecdd-4b97-9881-daa91d9729be); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `270-9b75992d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#527](https://github.com/timelesslounge/timelessis/issues/527) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#417](https://github.com/timelesslounge/timelessis/issues/417) is not in the agenda of @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), can't inspect

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
The job [#417](https://github.com/timelesslounge/timelessis/issues/417) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
