### ISSUE TITLE
views.py:2-5: Continue implementing list floors view....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#421]
The puzzle `95-130b3147` from #95 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/9ce9cae40ff5932bbfc56ba18e497e11f28f33a8/timeless/restaurants/floors/views.py#L2-L5

The puzzle was created by Paulo Lobo on 26-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Job [#421](https://github.com/timelesslounge/timelessis/issues/421) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/timelesslounge/timelessis/issues/421#issuecomment-469221201))

@emilianodellacasa The job [#421](https://github.com/timelesslounge/timelessis/issues/421) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/05b94c8a-0591-4203-9f12-e7049d24e182); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `95-130b3147` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#483](https://github.com/timelesslounge/timelessis/issues/483) is still not solved.

**Comment by 0crat** [comment]
The job [#421](https://github.com/timelesslounge/timelessis/issues/421) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
