### ISSUE TITLE
views.py:6-11: Implement create floor view. Create floor...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#422]
The puzzle `95-9a26f2d6` from #95 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/9ce9cae40ff5932bbfc56ba18e497e11f28f33a8/timeless/restaurants/floors/views.py#L6-L11

The puzzle was created by Paulo Lobo on 26-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/timelesslounge/timelessis/issues/422#issuecomment-470891775))

@emilianodellacasa The job [#422](https://github.com/timelesslounge/timelessis/issues/422) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/3bfc634d-1280-4fac-b2f3-97a2b8fa51b8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `95-9a26f2d6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#422](https://github.com/timelesslounge/timelessis/issues/422) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by ypshenychka** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/422#issuecomment-472064612))

@ypshenychka This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#422](https://github.com/timelesslounge/timelessis/issues/422) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23422%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@emilianodellacasa Why QA review is not assigned here?

**Comment by emilianodellacasa** [comment]
@ypshenychka Because I did, and apparently when the ARC is the assignee there is no review
