### ISSUE TITLE
views.py:16-20: Refactor all blueprint views to use...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#429]
The puzzle `309-e0f3db47` from #309 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/c2979ca8212eafa70e6eff2b599536ef23b10a6a/timeless/views.py#L16-L20

The puzzle was created by Paulo Lobo on 26-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#429](https://github.com/timelesslounge/timelessis/issues/429) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#429](https://github.com/timelesslounge/timelessis/issues/429) assigned to @vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/537fc9c1-0276-4509-b77e-195a5f145c50); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by VladimirRyzhkov** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/429#issuecomment-468887521))

@VladimirRyzhkov The user @vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov) resigned from [#429](https://github.com/timelesslounge/timelessis/issues/429), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @vladimirryzhkov[/z](https://www.0crat.com/u/vladimirryzhkov)

**Comment by emilianodellacasa** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu  ([here](https://github.com/timelesslounge/timelessis/issues/429#issuecomment-468935082))

@emilianodellacasa The job [#429](https://github.com/timelesslounge/timelessis/issues/429) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/2a2e893e-0952-4d90-8fef-ae3f19d46160); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
@marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `309-e0f3db47` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#429](https://github.com/timelesslounge/timelessis/issues/429) is not in the agenda of @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), can't inspect

**Comment by 0crat** [comment]
The job [#429](https://github.com/timelesslounge/timelessis/issues/429) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu)
