### ISSUE TITLE
views.py:118-122: Continue. When we use the...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#434]
The puzzle `380-2426b146` from #380 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/a4b3d4158790f7f65207263e5a0d8a4d5d479c55/timeless/reservations/views.py#L118-L122

The puzzle was created by marceloamadeu on 27-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Job [#434](https://github.com/timelesslounge/timelessis/issues/434) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/timelesslounge/timelessis/issues/434#issuecomment-469221149))

@emilianodellacasa The job [#434](https://github.com/timelesslounge/timelessis/issues/434) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/211cc2ef-cb17-4dd6-9b0a-52a3def58de5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by emilianodellacasa** [comment]
@0crat wait - PR #486 to be merged

**Comment by 0crat** [comment]
> @0crat wait - PR #486 to be merged ([here](https://github.com/timelesslounge/timelessis/issues/434#issuecomment-470486925))

@emilianodellacasa The impediment for [#434](https://github.com/timelesslounge/timelessis/issues/434) was registered successfully by @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `380-2426b146` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#492](https://github.com/timelesslounge/timelessis/issues/492) is still not solved.

**Comment by 0crat** [comment]
The job [#434](https://github.com/timelesslounge/timelessis/issues/434) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
