### ISSUE TITLE
Deploy scripts to staging server using Rultor

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#45]
We need to develop a script using Rultor to deploy and run the webapp in a staging server.

As a reference, in this phase we will use a [Digital Ocean Droplet](https://www.digitalocean.com/products/droplets/)

The script shall:
- accept an input param as tag;
- verify that the test runs smoothly;
- git tag;
- copy code on remote server;
- create database (if not existing);
- run migrations;
- set env variables and restart the server;
- add scripts in cron (like the one created in #47)
- verify the webapplication is running;

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240) are still not solved; solved: [#126](https://github.com/timelesslounge/timelessis/issues/126).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#248](https://github.com/timelesslounge/timelessis/issues/248) are still not solved; solved: [#126](https://github.com/timelesslounge/timelessis/issues/126), [#240](https://github.com/timelesslounge/timelessis/issues/240).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300) are still not solved; solved: [#126](https://github.com/timelesslounge/timelessis/issues/126), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#238](https://github.com/timelesslounge/timelessis/issues/238), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300) are still not solved; solved: [#126](https://github.com/timelesslounge/timelessis/issues/126), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#238](https://github.com/timelesslounge/timelessis/issues/238), [#299](https://github.com/timelesslounge/timelessis/issues/299) are still not solved; solved: [#126](https://github.com/timelesslounge/timelessis/issues/126), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248), [#300](https://github.com/timelesslounge/timelessis/issues/300).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#299](https://github.com/timelesslounge/timelessis/issues/299) is still not solved; solved: [#126](https://github.com/timelesslounge/timelessis/issues/126), [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248), [#300](https://github.com/timelesslounge/timelessis/issues/300).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#374](https://github.com/timelesslounge/timelessis/issues/374) is still not solved; solved: [#126](https://github.com/timelesslounge/timelessis/issues/126), [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#490](https://github.com/timelesslounge/timelessis/issues/490) is still not solved; solved: [#126](https://github.com/timelesslounge/timelessis/issues/126), [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300), [#374](https://github.com/timelesslounge/timelessis/issues/374).

**Comment by 0pdd** [comment]
@emilianodellacasa all 9 puzzles are solved here: [#126](https://github.com/timelesslounge/timelessis/issues/126), [#238](https://github.com/timelesslounge/timelessis/issues/238), [#239](https://github.com/timelesslounge/timelessis/issues/239), [#240](https://github.com/timelesslounge/timelessis/issues/240), [#248](https://github.com/timelesslounge/timelessis/issues/248), [#299](https://github.com/timelesslounge/timelessis/issues/299), [#300](https://github.com/timelesslounge/timelessis/issues/300), [#374](https://github.com/timelesslounge/timelessis/issues/374), [#490](https://github.com/timelesslounge/timelessis/issues/490).
