### ISSUE TITLE
it_auth_test.py:71-73: Forgot password routine. Test a...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#465]
The puzzle `388-4a843a62` from #388 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/886456b1d000f381f67c570e4750b81a85ee5cd1/tests/integration/it_auth_test.py#L71-L73

The puzzle was created by Ammar Atef on 02-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#465](https://github.com/timelesslounge/timelessis/issues/465) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#465](https://github.com/timelesslounge/timelessis/issues/465) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/844284c8-4b66-449c-9707-7eab856b483a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by ammaratef45** [comment]
@emilianodellacasa 
```
@pytest.mark.skip(reason="Can't inject mock user base")
def test_forgot_password_post(client):
```
Where is the issue that is supposed to solve this?

**Comment by emilianodellacasa** [comment]
@ammaratef45 It's issue #387 and there is already an open PR that is under review

**Comment by ammaratef45** [comment]
@emilianodellacasa Thanks

**Comment by ammaratef45** [comment]
@0crat wait for #387

**Comment by 0crat** [comment]
> @0crat wait for #387  ([here](https://github.com/timelesslounge/timelessis/issues/465#issuecomment-470061785))

@ammaratef45 The impediment for [#465](https://github.com/timelesslounge/timelessis/issues/465) was registered successfully by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0pdd** [comment]
The puzzle `388-4a843a62` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#465](https://github.com/timelesslounge/timelessis/issues/465) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
