### ISSUE TITLE
Create script for regular backups

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#47]
Create a script to be run in cron to backup (and restore) production DB.

The script will upload the backup to a Google Drive account.

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#115](https://github.com/timelesslounge/timelessis/issues/115), [#191](https://github.com/timelesslounge/timelessis/issues/191) are still not solved; solved: [#114](https://github.com/timelesslounge/timelessis/issues/114), [#116](https://github.com/timelesslounge/timelessis/issues/116).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#191](https://github.com/timelesslounge/timelessis/issues/191), [#224](https://github.com/timelesslounge/timelessis/issues/224) are still not solved; solved: [#114](https://github.com/timelesslounge/timelessis/issues/114), [#115](https://github.com/timelesslounge/timelessis/issues/115), [#116](https://github.com/timelesslounge/timelessis/issues/116).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#224](https://github.com/timelesslounge/timelessis/issues/224) is still not solved; solved: [#114](https://github.com/timelesslounge/timelessis/issues/114), [#115](https://github.com/timelesslounge/timelessis/issues/115), [#116](https://github.com/timelesslounge/timelessis/issues/116), [#191](https://github.com/timelesslounge/timelessis/issues/191).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#296](https://github.com/timelesslounge/timelessis/issues/296) is still not solved; solved: [#114](https://github.com/timelesslounge/timelessis/issues/114), [#115](https://github.com/timelesslounge/timelessis/issues/115), [#116](https://github.com/timelesslounge/timelessis/issues/116), [#191](https://github.com/timelesslounge/timelessis/issues/191), [#224](https://github.com/timelesslounge/timelessis/issues/224).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#352](https://github.com/timelesslounge/timelessis/issues/352) is still not solved; solved: [#114](https://github.com/timelesslounge/timelessis/issues/114), [#115](https://github.com/timelesslounge/timelessis/issues/115), [#116](https://github.com/timelesslounge/timelessis/issues/116), [#191](https://github.com/timelesslounge/timelessis/issues/191), [#224](https://github.com/timelesslounge/timelessis/issues/224), [#296](https://github.com/timelesslounge/timelessis/issues/296).

**Comment by 0pdd** [comment]
@emilianodellacasa all 7 puzzles are solved here: [#114](https://github.com/timelesslounge/timelessis/issues/114), [#115](https://github.com/timelesslounge/timelessis/issues/115), [#116](https://github.com/timelesslounge/timelessis/issues/116), [#191](https://github.com/timelesslounge/timelessis/issues/191), [#224](https://github.com/timelesslounge/timelessis/issues/224), [#296](https://github.com/timelesslounge/timelessis/issues/296), [#352](https://github.com/timelesslounge/timelessis/issues/352).
