### ISSUE TITLE
Need a definition for string quotes

### ISSUE THREAD

**Issue by paulodamaso** [timelesslounge/timelessis#48]
According to [String quotes section in PEP](https://www.python.org/dev/peps/pep-0008/#string-quotes):

> In Python, single-quoted strings and double-quoted strings are the same. This PEP does not make a recommendation for this. Pick a rule and stick to it. When a string contains single or double quote characters, however, use the other one to avoid backslashes in the string. It improves readability.

We do not have defined which character to use, so we have a both of them being used in our files, violationg this rule. Let's define which character to use (`'` or `"`) and replace the other one in all files

**Comment by 0pdd** [comment]
@paulodamaso all 2 puzzles are solved here: [#69](https://github.com/timelesslounge/timelessis/issues/69), [#74](https://github.com/timelesslounge/timelessis/issues/74).
