### ISSUE TITLE
test_auth.py:27-29: Inject user into session in the test...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#485]
The puzzle `385-76f7ffb3` from #385 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/118db7fb85c645717912b53818cf788e21cdfb2a/tests/test_auth.py#L27-L29

The puzzle was created by Paulo Lobo on 06-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@0crat assign me

**Comment by 0crat** [comment]
Job [#485](https://github.com/timelesslounge/timelessis/issues/485) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/timelesslounge/timelessis/issues/485#issuecomment-470583212))

@emilianodellacasa The job [#485](https://github.com/timelesslounge/timelessis/issues/485) assigned to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/0d9e22da-54bc-40a7-a938-89113089518a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `385-76f7ffb3` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#485](https://github.com/timelesslounge/timelessis/issues/485) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)
