### ISSUE TITLE
install_db.sh:3-13: Continue the deploy algorithm. We...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#490]
The puzzle `374-ef460cff` from #374 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/b2cdd0e32c0097a25b9e5994c00aea2c832f89e6/scripts/install/deploy/install_db.sh#L3-L13

The puzzle was created by Paulo Lobo on 06-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#490](https://github.com/timelesslounge/timelessis/issues/490) is now in scope, role is `DEV`

**Comment by emilianodellacasa** [comment]
@0crat assign @soin08

**Comment by 0crat** [comment]
> @0crat assign @soin08  ([here](https://github.com/timelesslounge/timelessis/issues/490#issuecomment-470479674))

@emilianodellacasa The job [#490](https://github.com/timelesslounge/timelessis/issues/490) assigned to @soin08[/z](https://www.0crat.com/u/soin08), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/265251e3-e32c-4967-803f-ffc460087038); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `374-ef460cff` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @soin08[/z](https://www.0crat.com/u/soin08), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#490](https://github.com/timelesslounge/timelessis/issues/490) is not in the agenda of @soin08[/z](https://www.0crat.com/u/soin08), can't inspect

**Comment by 0crat** [comment]
The job [#490](https://github.com/timelesslounge/timelessis/issues/490) is now out of scope

**Comment by soin08** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/490#issuecomment-471219227))

@soin08 This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#490](https://github.com/timelesslounge/timelessis/issues/490) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 33min
  * @soin08[/z](https://www.0crat.com/u/soin08) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%23490%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@soin08 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Ticket must have references to all pull requests where the problem was actually fixed

Please add reference to corresponding PR (you can do this by mentioning this issue in PR's description).

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @soin08[/z](https://www.0crat.com/u/soin08)

**Comment by 0crat** [comment]
Quality review completed: +6 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
