### ISSUE TITLE
Possible BUG - I think this is not correct

### ISSUE THREAD

**Issue by ebercamargo** [timelesslounge/timelessis#491]
@emilianodellacasa 
For some reason, I managed to commit a branch, please request that it be verified if this is correct for my profile or it is a BUG.

To see:
https://github.com/timelesslounge/timelessis/pull/487

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@ebercamargo you are right, that shouldn't happen. Fixing in settings now. Thanks for reporting

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#491` is not assigned, can't get performer
