### ISSUE TITLE
views.py:2-4: Continue to implement html templates using...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#494]
The puzzle `338-ce2e954e` from #338 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/ac5afe24a60ad5c3c89528702bc660c7c0e7c0f5/timeless/roles/views.py#L2-L4

The puzzle was created by Vadim Ryazanov on 07-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#494](https://github.com/timelesslounge/timelessis/issues/494) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `338-ce2e954e` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#494` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#494](https://github.com/timelesslounge/timelessis/issues/494) is now out of scope
