### ISSUE TITLE
Access management

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#5]
In order for the employees to access the webapp, we should provide the access system.

These are the functions that shall be developed:

- login (by username and password defined in Employee model, see #4);
- logout;
- activation link sent by email upon account creation (developed in #4)
- forgotten password;

The login page shall have the following elements:

- Logo
- Caption “Login Page”
- username
- password
- Login Button

Forgotten password page should be similar in structure.

Once user has logged in we will redirect to his/her profile page, containing 

- a navbar at the top left (that should appear in all internal pages);
- "Profile" menu item;
- "Logout" menu item;
- Employee name minified (ex. "John S.")

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#59](https://github.com/timelesslounge/timelessis/issues/59) is still not solved; solved: [#60](https://github.com/timelesslounge/timelessis/issues/60).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#200](https://github.com/timelesslounge/timelessis/issues/200), [#201](https://github.com/timelesslounge/timelessis/issues/201), [#60](https://github.com/timelesslounge/timelessis/issues/60) are still not solved; solved: [#59](https://github.com/timelesslounge/timelessis/issues/59).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#200](https://github.com/timelesslounge/timelessis/issues/200), [#269](https://github.com/timelesslounge/timelessis/issues/269), [#60](https://github.com/timelesslounge/timelessis/issues/60) are still not solved; solved: [#201](https://github.com/timelesslounge/timelessis/issues/201), [#59](https://github.com/timelesslounge/timelessis/issues/59).

**Comment by 0pdd** [comment]
@emilianodellacasa 4 puzzles [#200](https://github.com/timelesslounge/timelessis/issues/200), [#269](https://github.com/timelesslounge/timelessis/issues/269), [#297](https://github.com/timelesslounge/timelessis/issues/297), [#60](https://github.com/timelesslounge/timelessis/issues/60) are still not solved; solved: [#201](https://github.com/timelesslounge/timelessis/issues/201), [#59](https://github.com/timelesslounge/timelessis/issues/59).

**Comment by 0pdd** [comment]
@emilianodellacasa 3 puzzles [#200](https://github.com/timelesslounge/timelessis/issues/200), [#297](https://github.com/timelesslounge/timelessis/issues/297), [#60](https://github.com/timelesslounge/timelessis/issues/60) are still not solved; solved: [#201](https://github.com/timelesslounge/timelessis/issues/201), [#269](https://github.com/timelesslounge/timelessis/issues/269), [#59](https://github.com/timelesslounge/timelessis/issues/59).

**Comment by 0pdd** [comment]
@emilianodellacasa 2 puzzles [#297](https://github.com/timelesslounge/timelessis/issues/297), [#60](https://github.com/timelesslounge/timelessis/issues/60) are still not solved; solved: [#200](https://github.com/timelesslounge/timelessis/issues/200), [#201](https://github.com/timelesslounge/timelessis/issues/201), [#269](https://github.com/timelesslounge/timelessis/issues/269), [#59](https://github.com/timelesslounge/timelessis/issues/59).

**Comment by 0pdd** [comment]
@emilianodellacasa the puzzle [#297](https://github.com/timelesslounge/timelessis/issues/297) is still not solved; solved: [#200](https://github.com/timelesslounge/timelessis/issues/200), [#201](https://github.com/timelesslounge/timelessis/issues/201), [#269](https://github.com/timelesslounge/timelessis/issues/269), [#59](https://github.com/timelesslounge/timelessis/issues/59), [#60](https://github.com/timelesslounge/timelessis/issues/60).
