### ISSUE TITLE
React Integration Missing

### ISSUE THREAD

**Issue by pablopaul** [timelesslounge/timelessis#514]
React needs to be integrated in the project before I am able to develop #502 

Integration means:
* Setup React dependencies (I will use https://github.com/facebook/create-react-app)
* Add React test execution to CI
* Add React development workflow to readme

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@pablopaul could you do it?

**Comment by 0crat** [comment]
Job [#514](https://github.com/timelesslounge/timelessis/issues/514) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @pablopaul[/z](https://www.0crat.com/u/pablopaul)

**Comment by pablopaul** [comment]
@emilianodellacasa yes I can do it.

**Comment by emilianodellacasa** [comment]
@0crat assign @pablopaul

**Comment by 0crat** [comment]
> @0crat assign @pablopaul  ([here](https://github.com/timelesslounge/timelessis/issues/514#issuecomment-471214181))

@emilianodellacasa The job [#514](https://github.com/timelesslounge/timelessis/issues/514) assigned to @pablopaul[/z](https://www.0crat.com/u/pablopaul), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/e1a0883a-8867-4367-822d-f076de6f11c8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
@pablopaul the puzzle [#532](https://github.com/timelesslounge/timelessis/issues/532) is still not solved.

**Comment by emilianodellacasa** [comment]
@rultor release, tag 0.0.1

**Comment by emilianodellacasa** [comment]
@rultor release, tag=`0.0.1`

**Comment by emilianodellacasa** [comment]
@rultor release, tag 0.0.1

**Comment by emilianodellacasa** [comment]
@rultor release, tag=`0.0.1`

**Comment by emilianodellacasa** [comment]
@rultor release, tag=`0.0.1`

**Comment by emilianodellacasa** [comment]
@rultor deploy

**Comment by emilianodellacasa** [comment]
@rultor deploy

**Comment by emilianodellacasa** [comment]
@rultor deploy

**Comment by emilianodellacasa** [comment]
@rultor deploy

**Comment by emilianodellacasa** [comment]
@rultor deploy

**Comment by emilianodellacasa** [comment]
@rultor deploy

**Comment by emilianodellacasa** [comment]
@rultor deploy

**Comment by emilianodellacasa** [comment]
@rultor merge

**Comment by emilianodellacasa** [comment]
@rultor deploy

**Comment by emilianodellacasa** [comment]
@rultor deploy

**Comment by 0crat** [comment]
The job [#514](https://github.com/timelesslounge/timelessis/issues/514) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @pablopaul[/z](https://www.0crat.com/u/pablopaul)

**Comment by 0pdd** [comment]
@pablopaul the only puzzle [#532](https://github.com/timelesslounge/timelessis/issues/532) is solved here.
