### ISSUE TITLE
Don't push migrations manually

### ISSUE THREAD

**Issue by bkuzmic** [timelesslounge/timelessis#52]
Since migration problems will occure more often as people start adding more and more models, I propose not to push migrations manually. I would drop creating migrations on every change/add of model (add them to git ignore). Instead, I would use rultor to create migration file after each release. WDYT?

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#52` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
