### ISSUE TITLE
Readme lacks explanation of Rultor and Travis CI usage

### ISSUE THREAD

**Issue by pablopaul** [timelesslounge/timelessis#520]
The readme should explain why Travis CI and Rultor is used.
It should be clear where to add what kind of jobs.
For now I am unsure in which pipeline the execution of React tests should be added.

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@pablopaul Travis is used as a way to check if tests are passing before even trying to merge, rultor runs tests and code checks before merging, to avoid bad code to be added in main branch.

Travis and rultor are usend in a pretty standard way, you can see [rultor docs](http://doc.rultor.com/) and [Travis](https://docs.travis-ci.com/user/languages/python/) for more information

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#520` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
