### ISSUE TITLE
.rultor.yml:24: React Frontend tests should be also...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#532]
The puzzle `514-f9121ced` from #514 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/df17ff524a2e6f32ba70cd0cf33bfa375b285c4e/.rultor.yml#L24-L24

The puzzle was created by Paul Vincent Beigang on 09-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#532](https://github.com/timelesslounge/timelessis/issues/532) is now in scope, role is `DEV`

**Comment by emilianodellacasa** [comment]
@0crat assign @pablopaul

**Comment by 0crat** [comment]
> @0crat assign @pablopaul  ([here](https://github.com/timelesslounge/timelessis/issues/532#issuecomment-471612992))

@emilianodellacasa The job [#532](https://github.com/timelesslounge/timelessis/issues/532) assigned to @pablopaul[/z](https://www.0crat.com/u/pablopaul), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/820df493-13a3-4eb4-bb3c-15bf25de032d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0pdd** [comment]
The puzzle `514-f9121ced` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#532](https://github.com/timelesslounge/timelessis/issues/532) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @pablopaul[/z](https://www.0crat.com/u/pablopaul)
