### ISSUE TITLE
PDD min-words config slowing down DEV work

### ISSUE THREAD

**Issue by pablopaul** [timelesslounge/timelessis#544]
This is the second time the TravisCI build failed because of an error like this:

```
ERROR: Puzzle .rultor.yml:26-26 has a very short description of just 14 words while a minimum of 20 is required
```

Please run `pdd` command with a lower `min-words` config like this `--rule min-words:5` in `.pdd`, see https://github.com/yegor256/pdd/#how-to-configure-rules for more info

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@pablopaul I know this could be annoying, but a minimum number of words of 20 force DEVs to be more descriptive of the issue, otherwise they are just going to write "Just fix that f*cking shit" :)

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#544` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
