### ISSUE TITLE
models.py:29-31: Continue implementation as in #17....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#56]
The puzzle `17-965ca61a` from #17 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/e9d82cbeba7cb2a26d78a1ead6b501a2cbac3e5b/schemetypes/models.py#L29-L31

The puzzle was created by @amihaiemil on 29-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by bkuzmic** [comment]
@0crat wait busy on other tasks.

**Comment by 0crat** [comment]
> @0crat wait busy on other tasks. ([here](https://github.com/timelesslounge/timelessis/issues/56#issuecomment-461043548))

@bkuzmic The impediment for [#56](https://github.com/timelesslounge/timelessis/issues/56) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by emilianodellacasa** [comment]
@bkuzmic Are you working on this? May I assign to someone else less busy? Please let me know

**Comment by bkuzmic** [comment]
@emilianodellacasa I wanted to finish the GenericView (#173) first to be able to reuse it. Sorry for taking it too long - I've had problems with caching. As soon as the #173 is merged, I'll get to this one.

**Comment by emilianodellacasa** [comment]
@emilianodellacasa No problem, thank you so much, keep working on this!

**Comment by 0pdd** [comment]
The puzzle `17-965ca61a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#361](https://github.com/timelesslounge/timelessis/issues/361), [#362](https://github.com/timelesslounge/timelessis/issues/362) are still not solved.

**Comment by 0crat** [comment]
Job [#56](https://github.com/timelesslounge/timelessis/issues/56) is not in the agenda of @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), can't inspect

**Comment by 0crat** [comment]
The job [#56](https://github.com/timelesslounge/timelessis/issues/56) is now out of scope

**Comment by bkuzmic** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/56#issuecomment-466111553))

@bkuzmic This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#56](https://github.com/timelesslounge/timelessis/issues/56) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 3hr
  * @bkuzmic[/z](https://www.0crat.com/u/bkuzmic) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%2356%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by bkuzmic** [comment]
@ypshenychka Please make a QA review. It seems that 0crat forgot to notify you.

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#362](https://github.com/timelesslounge/timelessis/issues/362) is still not solved; solved: [#361](https://github.com/timelesslounge/timelessis/issues/361).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved.
