### ISSUE TITLE
models.py:7-11: Continue implementation. Employees should...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#57]
The puzzle `4-49d25317` from #4 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/9d766c68177563543f6cee80591ce186345d0816/employees/models.py#L7-L11

The puzzle was created by Boris Kuzmic on 26-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by bkuzmic** [comment]
@0crat wait busy on other tasks.

**Comment by 0crat** [comment]
> @0crat wait busy on other tasks. ([here](https://github.com/timelesslounge/timelessis/issues/57#issuecomment-461043687))

@bkuzmic The impediment for [#57](https://github.com/timelesslounge/timelessis/issues/57) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by emilianodellacasa** [comment]
@bkuzmic Are you still working on this? May I assign to someone else?

**Comment by 0pdd** [comment]
@0pdd the puzzle [#348](https://github.com/timelesslounge/timelessis/issues/348) is still not solved.

**Comment by bkuzmic** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/57#issuecomment-465920723))

@bkuzmic This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#57](https://github.com/timelesslounge/timelessis/issues/57) is [in scope](http://www.zerocracy.com/policy.html#14) for 23days
  * The role is `DEV`
  * The job is assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic) for [23days](http://www.zerocracy.com/policy.html#8)
  * @bkuzmic[/z](https://www.0crat.com/u/bkuzmic) is on vacation!
  * There is a monetary reward attached
  * @bkuzmic[/z](https://www.0crat.com/u/bkuzmic) will get 50% of their hourly rate for this job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%2357%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
The puzzle `4-49d25317` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#348](https://github.com/timelesslounge/timelessis/issues/348), [#357](https://github.com/timelesslounge/timelessis/issues/357) are still not solved.

**Comment by 0crat** [comment]
Job [#57](https://github.com/timelesslounge/timelessis/issues/57) is not in the agenda of @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), can't inspect

**Comment by 0crat** [comment]
The job [#57](https://github.com/timelesslounge/timelessis/issues/57) is now out of scope

**Comment by bkuzmic** [comment]
@emilianodellacasa Please take a look at this. I needed to create a new PR to remove the puzzle, which I did, but the job just disappeared from my agenda, without QA review.

**Comment by emilianodellacasa** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/timelesslounge/timelessis/issues/57#issuecomment-466027441))

@emilianodellacasa This is what I know about this job in [CF9LG1YCA](https://www.0crat.com/p/CF9LG1YCA), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#57](https://github.com/timelesslounge/timelessis/issues/57) is not in scope
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 3hr
  * @bkuzmic[/z](https://www.0crat.com/u/bkuzmic) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/CF9LG1YCA?q=%7Bjob%3A%27gh%3Atimelesslounge%2Ftimelessis%2357%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by emilianodellacasa** [comment]
@ypshenychka please review for @bkuzmic

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#357](https://github.com/timelesslounge/timelessis/issues/357), [#411](https://github.com/timelesslounge/timelessis/issues/411), [#412](https://github.com/timelesslounge/timelessis/issues/412), [#413](https://github.com/timelesslounge/timelessis/issues/413) are still not solved; solved: [#348](https://github.com/timelesslounge/timelessis/issues/348).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#357](https://github.com/timelesslounge/timelessis/issues/357), [#412](https://github.com/timelesslounge/timelessis/issues/412), [#413](https://github.com/timelesslounge/timelessis/issues/413), [#503](https://github.com/timelesslounge/timelessis/issues/503) are still not solved; solved: [#348](https://github.com/timelesslounge/timelessis/issues/348), [#411](https://github.com/timelesslounge/timelessis/issues/411).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#357](https://github.com/timelesslounge/timelessis/issues/357), [#413](https://github.com/timelesslounge/timelessis/issues/413), [#503](https://github.com/timelesslounge/timelessis/issues/503), [#529](https://github.com/timelesslounge/timelessis/issues/529) are still not solved; solved: [#348](https://github.com/timelesslounge/timelessis/issues/348), [#411](https://github.com/timelesslounge/timelessis/issues/411), [#412](https://github.com/timelesslounge/timelessis/issues/412).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#413](https://github.com/timelesslounge/timelessis/issues/413), [#503](https://github.com/timelesslounge/timelessis/issues/503), [#529](https://github.com/timelesslounge/timelessis/issues/529), [#542](https://github.com/timelesslounge/timelessis/issues/542) are still not solved; solved: [#348](https://github.com/timelesslounge/timelessis/issues/348), [#357](https://github.com/timelesslounge/timelessis/issues/357), [#411](https://github.com/timelesslounge/timelessis/issues/411), [#412](https://github.com/timelesslounge/timelessis/issues/412).
