### ISSUE TITLE
models.py:12-18: Create constructor for Employee model....

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#58]
The puzzle `4-6ceceaee` from #4 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/9d766c68177563543f6cee80591ce186345d0816/employees/models.py#L12-L18

The puzzle was created by Boris Kuzmic on 26-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by bkuzmic** [comment]
@0crat wait for PR: #138

**Comment by 0crat** [comment]
> @0crat wait for PR: #138  ([here](https://github.com/timelesslounge/timelessis/issues/58#issuecomment-461032587))

@bkuzmic The impediment for [#58](https://github.com/timelesslounge/timelessis/issues/58) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0pdd** [comment]
The puzzle `4-6ceceaee` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#58](https://github.com/timelesslounge/timelessis/issues/58) is now out of scope

**Comment by ypshenychka** [comment]
@bkuzmic According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

Please add more details into registered [impediment](https://github.com/timelesslounge/timelessis/issues/58#issuecomment-461032587) to describe what exactly you were waiting for in that PR.

**Comment by bkuzmic** [comment]
@ypshenychka I've edited the comment for impediment. Please take a look

**Comment by ypshenychka** [comment]
@bkuzmic thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
