### ISSUE TITLE
views.py:2-5: Continue implementing login(),...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#59]
The puzzle `5-b6c5b635` from #5 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/e0d7aea5984654c017bebd3326c091fb861d8e98/auth/views.py#L2-L5

The puzzle was created by Boris Kuzmic on 28-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `5-b6c5b635` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#200](https://github.com/timelesslounge/timelessis/issues/200), [#201](https://github.com/timelesslounge/timelessis/issues/201) are still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#59](https://github.com/timelesslounge/timelessis/issues/59) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#200](https://github.com/timelesslounge/timelessis/issues/200), [#269](https://github.com/timelesslounge/timelessis/issues/269) are still not solved; solved: [#201](https://github.com/timelesslounge/timelessis/issues/201).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#200](https://github.com/timelesslounge/timelessis/issues/200), [#269](https://github.com/timelesslounge/timelessis/issues/269), [#297](https://github.com/timelesslounge/timelessis/issues/297) are still not solved; solved: [#201](https://github.com/timelesslounge/timelessis/issues/201).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#200](https://github.com/timelesslounge/timelessis/issues/200), [#297](https://github.com/timelesslounge/timelessis/issues/297) are still not solved; solved: [#201](https://github.com/timelesslounge/timelessis/issues/201), [#269](https://github.com/timelesslounge/timelessis/issues/269).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#297](https://github.com/timelesslounge/timelessis/issues/297) is still not solved; solved: [#200](https://github.com/timelesslounge/timelessis/issues/200), [#201](https://github.com/timelesslounge/timelessis/issues/201), [#269](https://github.com/timelesslounge/timelessis/issues/269).
