### ISSUE TITLE
views.py:6-9: Implement before_app_request function that...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#60]
The puzzle `5-5e1a2150` from #5 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/e0d7aea5984654c017bebd3326c091fb861d8e98/auth/views.py#L6-L9

The puzzle was created by Boris Kuzmic on 28-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by bkuzmic** [comment]
@0crat wait for PR: #131.

**Comment by 0crat** [comment]
> @0crat wait for PR: #131. ([here](https://github.com/timelesslounge/timelessis/issues/60#issuecomment-461042824))

@bkuzmic The impediment for [#60](https://github.com/timelesslounge/timelessis/issues/60) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0pdd** [comment]
The puzzle `5-5e1a2150` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#60](https://github.com/timelesslounge/timelessis/issues/60) is now out of scope

**Comment by ypshenychka** [comment]
@bkuzmic According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary 

Please add more details into registered [impediment](https://github.com/timelesslounge/timelessis/issues/60#issuecomment-461042824).

**Comment by bkuzmic** [comment]
@ypshenychka I have added more details. Please take a look.

**Comment by ypshenychka** [comment]
@bkuzmic thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
