### ISSUE TITLE
views.py:10-12: Continue implementing Settings page for...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#63]
The puzzle `32-d70f7c1c` from #32 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/b787c79b7a9416c612c10714a080e57058bcf008/reservations/views.py#L10-L12

The puzzle was created by Vlad Arefev on 29-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by amihaiemil** [comment]
@0crat waiting for #161 to be merged

**Comment by 0crat** [comment]
> @0crat waiting for #161 to be merged ([here](https://github.com/timelesslounge/timelessis/issues/63#issuecomment-462047352))

@amihaiemil Job [#63](https://github.com/timelesslounge/timelessis/issues/63) is already on hold

**Comment by 0pdd** [comment]
The puzzle `32-d70f7c1c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#186](https://github.com/timelesslounge/timelessis/issues/186) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#63](https://github.com/timelesslounge/timelessis/issues/63) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#291](https://github.com/timelesslounge/timelessis/issues/291), [#292](https://github.com/timelesslounge/timelessis/issues/292), [#293](https://github.com/timelesslounge/timelessis/issues/293) are still not solved; solved: [#186](https://github.com/timelesslounge/timelessis/issues/186).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#292](https://github.com/timelesslounge/timelessis/issues/292), [#293](https://github.com/timelesslounge/timelessis/issues/293), [#356](https://github.com/timelesslounge/timelessis/issues/356) are still not solved; solved: [#186](https://github.com/timelesslounge/timelessis/issues/186), [#291](https://github.com/timelesslounge/timelessis/issues/291).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#292](https://github.com/timelesslounge/timelessis/issues/292), [#356](https://github.com/timelesslounge/timelessis/issues/356), [#476](https://github.com/timelesslounge/timelessis/issues/476) are still not solved; solved: [#186](https://github.com/timelesslounge/timelessis/issues/186), [#291](https://github.com/timelesslounge/timelessis/issues/291), [#293](https://github.com/timelesslounge/timelessis/issues/293).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#292](https://github.com/timelesslounge/timelessis/issues/292), [#476](https://github.com/timelesslounge/timelessis/issues/476), [#510](https://github.com/timelesslounge/timelessis/issues/510) are still not solved; solved: [#186](https://github.com/timelesslounge/timelessis/issues/186), [#291](https://github.com/timelesslounge/timelessis/issues/291), [#293](https://github.com/timelesslounge/timelessis/issues/293), [#356](https://github.com/timelesslounge/timelessis/issues/356).
