### ISSUE TITLE
__init__.py:3-5: Enhance the "DoubleQuotesOnly" rule from...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#74]
The puzzle `69-e0bed019` from #69 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/5d65b42614b85c0d90ee3179ebe92b89abd29743/__init__.py#L3-L5

The puzzle was created by @amihaiemil on 30-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by bkuzmic** [comment]
@0crat wait for fixing small errors in PR: #159

**Comment by 0crat** [comment]
> @0crat wait for fixing small errors in PR: #159 ([here](https://github.com/timelesslounge/timelessis/issues/74#issuecomment-462081949))

@bkuzmic The impediment for [#74](https://github.com/timelesslounge/timelessis/issues/74) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0pdd** [comment]
The puzzle `69-e0bed019` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#74](https://github.com/timelesslounge/timelessis/issues/74) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
