### ISSUE TITLE
Missing quick validation of PR

### ISSUE THREAD

**Issue by krzyk** [timelesslounge/timelessis#86]
It would be very useful fore code reviews to have a CI like travis or circle ci configured.
Without it, the only verification is using rultor, which is quite slow and late in the process.

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) please, pay attention to this issue

**Comment by emilianodellacasa** [comment]
@krzyk Now that the repo is public, we can do this.

I would like to have travis and codecov (for code coverage) configured. 

Commit https://github.com/timelesslounge/timelessis/commit/6bf5903b5d8301e1189a47318a1808968eab85a0 contains a few settings for them

**Comment by 0crat** [comment]
Job [#86](https://github.com/timelesslounge/timelessis/issues/86) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@55d69b91-ec34-4bf1-baee-b9c4b56fbdad, thread: AsyncProc-6
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "bans.xml" in "CF9LG1YCA" in 2min: java.util.concurrent.locks.ReentrantLock@62e21b4b[Locked by thread BkParallel-7]
```

[0.40.15](https://github.com/zerocracy/farm): CID: [2e9624fe-db8d-43a3-aba1-2583c5406d0e](https://www.0crat.com/footprint/CF9LG1YCA/2e9624fe-db8d-43a3-aba1-2583c5406d0e), Type: "Job was added to WBS"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@55d69b91-ec34-4bf1-baee-b9c4b56fbdad, thread: AsyncProc-8
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "ledger.xml" in "CF9LG1YCA" in 2min: java.util.concurrent.locks.ReentrantLock@62e21b4b[Locked by thread BkParallel-7]
```

[0.40.15](https://github.com/zerocracy/farm): CID: [1d8cdf85-d1f4-4980-9cff-def037c53aaa](https://www.0crat.com/footprint/CF9LG1YCA/1d8cdf85-d1f4-4980-9cff-def037c53aaa), Type: "Make payment"

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@55d69b91-ec34-4bf1-baee-b9c4b56fbdad, thread: AsyncProc-8
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "rates.xml" in "CF9LG1YCA" in 2min: java.util.concurrent.locks.ReentrantLock@62e21b4b[Locked by thread BkParallel-7]
```

[0.40.15](https://github.com/zerocracy/farm): CID: [1d8cdf85-d1f4-4980-9cff-def037c53aaa](https://www.0crat.com/footprint/CF9LG1YCA/1d8cdf85-d1f4-4980-9cff-def037c53aaa), Type: "Make payment"

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@emilianodellacasa I didn't get payment for this one

**Comment by 0crat** [comment]
The job [#86](https://github.com/timelesslounge/timelessis/issues/86) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/4a565ef0-6dc1-4e6b-8413-bb59f39e6edb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#86` already assigned to @bkuzmic, can't assign to @bkuzmic

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#86` already assigned to @bkuzmic, can't assign to @bkuzmic

**Comment by 0crat** [comment]
Job `gh:timelesslounge/timelessis#86` already assigned to @bkuzmic, can't assign to @bkuzmic

**Comment by krzyk** [comment]
@emilianodellacasa regarding https://github.com/timelesslounge/timelessis/issues/86#issuecomment-461058729 - 0crat is working stable now :)

**Comment by emilianodellacasa** [comment]
@krzyk of course I will only be able to pay you, without reputation points. Do you agree?

**Comment by krzyk** [comment]
@emilianodellacasa yes

**Comment by emilianodellacasa** [comment]
@0crat pay @krzyk $12.5

**Comment by 0crat** [comment]
> @0crat pay @krzyk $12.5 ([here](https://github.com/timelesslounge/timelessis/issues/86#issuecomment-462048925))

@emilianodellacasa Argument "$12.5" doesn't match regex `@?[a-zA-Z0-9\-]+`

**Comment by emilianodellacasa** [comment]
@0crat pay $12.5 @krzyk

**Comment by 0crat** [comment]
> @0crat pay $12.5 @krzyk  ([here](https://github.com/timelesslounge/timelessis/issues/86#issuecomment-462049007))

@emilianodellacasa Argument "$12.5" doesn't match regex `\d+min`

**Comment by krzyk** [comment]
@emilianodellacasa the format is in mins, e.g. see https://github.com/zerocracy/farm/pull/1799#issuecomment-442457772 (not sure about pay vs extra, maybe it was renamed)

**Comment by emilianodellacasa** [comment]
@0crat pay 15min @krzyk

**Comment by 0crat** [comment]
Direct payment to @krzyk[/z](https://www.0crat.com/u/krzyk) in #86, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -20 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by 0crat** [comment]
Direct payment from @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by emilianodellacasa** [comment]
@bkuzmic Please also add code climate

**Comment by bkuzmic** [comment]
@emilianodellacasa Can you please enable the repository on Travis. I don't have the admin rights.

**Comment by emilianodellacasa** [comment]
@bkuzmic Should be active now, please try and let me go

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by bkuzmic** [comment]
@emilianodellacasa Sorry for not trying this sooner. On the page: https://travis-ci.org/timelesslounge/timelessis I still get error that repository is not active.

**Comment by emilianodellacasa** [comment]
@bkuzmic now it should be active

**Comment by bkuzmic** [comment]
@krzyk Can you please close this ticket since PR is merged?

**Comment by emilianodellacasa** [comment]
@bkuzmic @krzyk Let's wait to see if everything is working correctly with a new PR

**Comment by bkuzmic** [comment]
@0crat wait to see if everything works correctly, as per comment: https://github.com/timelesslounge/timelessis/issues/86#issuecomment-463572214

**Comment by 0crat** [comment]
> @0crat wait to see if everything works correctly, as per comment: https://github.com/timelessloun... ([here](https://github.com/timelesslounge/timelessis/issues/86#issuecomment-463650229))

@bkuzmic The impediment for [#86](https://github.com/timelesslounge/timelessis/issues/86) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by emilianodellacasa** [comment]
@krzyk we can close it

**Comment by krzyk** [comment]
@bkuzmic thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#86](https://github.com/timelesslounge/timelessis/issues/86) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
