### ISSUE TITLE
sync.py:3-7: Implement synchronization between Poster and...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#88]
The puzzle `66-c2cf1df5` from #66 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/84208bb71293765886339be6a3651d2d7844f2c5/sync/sync.py#L3-L7

The puzzle was created by Paulo Lobo on 01-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `66-c2cf1df5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#157](https://github.com/timelesslounge/timelessis/issues/157) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#88](https://github.com/timelesslounge/timelessis/issues/88) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#212](https://github.com/timelesslounge/timelessis/issues/212) is still not solved; solved: [#157](https://github.com/timelesslounge/timelessis/issues/157).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#157](https://github.com/timelesslounge/timelessis/issues/157), [#212](https://github.com/timelesslounge/timelessis/issues/212).
