### ISSUE TITLE
Role model

### ISSUE THREAD

**Issue by emilianodellacasa** [timelesslounge/timelessis#9]
Employee may have one or more roles assigned, determining what the employee can do inside the application.

These are the predefined roles for the application:
- Administrator
- Owner
- Director
- Manager
- Location Admin
- Master
- Cleaner
- Intern
- Candidate

These are the main attributes:
- id
- name
- flag "works on shift"
- company_id

Roles should have its own management pages to list, create, edit and delete them. In the index page it should be possible to sort and filter for every column.

The privileges for each role will be defined in a future issue.

**Comment by 0pdd** [comment]
@emilianodellacasa the only puzzle [#96](https://github.com/timelesslounge/timelessis/issues/96) is solved here.
