### ISSUE TITLE
views.py:2-6: Continue implementing list_floors(),...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#95]
The puzzle `42-8659514f` from #42 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/6b78e2f2be499e58df5ccd62e455a037a7adc55e/restaurants/floors/views.py#L2-L6

The puzzle was created by Boris Kuzmic on 30-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by krzyk** [comment]
@0crat waiting for review of PR #137

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/timelesslounge/timelessis/issues/95#issuecomment-462042577))

@krzyk The user @krzyk[/z](https://www.0crat.com/u/krzyk) resigned from [#95](https://github.com/timelesslounge/timelessis/issues/95), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#95](https://github.com/timelesslounge/timelessis/issues/95) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/de552168-2282-4945-83c6-2ee6c8034796); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@0pdd the puzzle [#192](https://github.com/timelesslounge/timelessis/issues/192) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#255](https://github.com/timelesslounge/timelessis/issues/255) is still not solved; solved: [#192](https://github.com/timelesslounge/timelessis/issues/192).

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by bkuzmic** [comment]
@0crat refuse this is the puzzle i have created and I'm also busy on other tasks.

**Comment by 0crat** [comment]
> @0crat refuse this is the puzzle i have created and I'm also busy on other tasks. ([here](https://github.com/timelesslounge/timelessis/issues/95#issuecomment-464509160))

@bkuzmic The user @bkuzmic[/z](https://www.0crat.com/u/bkuzmic) resigned from [#95](https://github.com/timelesslounge/timelessis/issues/95), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
The job [#95](https://github.com/timelesslounge/timelessis/issues/95) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/CF9LG1YCA/e75a7a9b-280f-44d2-afce-337781ff2e13); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0pdd** [comment]
@0pdd the puzzle [#338](https://github.com/timelesslounge/timelessis/issues/338) is still not solved; solved: [#192](https://github.com/timelesslounge/timelessis/issues/192), [#255](https://github.com/timelesslounge/timelessis/issues/255).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #402 review and merge

**Comment by 0crat** [comment]
> @0crat wait for #402 review and merge ([here](https://github.com/timelesslounge/timelessis/issues/95#issuecomment-467267900))

@paulodamaso The impediment for [#95](https://github.com/timelesslounge/timelessis/issues/95) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0pdd** [comment]
The puzzle `42-8659514f` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#338](https://github.com/timelesslounge/timelessis/issues/338), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#424](https://github.com/timelesslounge/timelessis/issues/424) are still not solved; solved: [#192](https://github.com/timelesslounge/timelessis/issues/192), [#255](https://github.com/timelesslounge/timelessis/issues/255).

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#95](https://github.com/timelesslounge/timelessis/issues/95) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#338](https://github.com/timelesslounge/timelessis/issues/338), [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#424](https://github.com/timelesslounge/timelessis/issues/424), [#483](https://github.com/timelesslounge/timelessis/issues/483) are still not solved; solved: [#192](https://github.com/timelesslounge/timelessis/issues/192), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#421](https://github.com/timelesslounge/timelessis/issues/421).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#424](https://github.com/timelesslounge/timelessis/issues/424), [#483](https://github.com/timelesslounge/timelessis/issues/483), [#494](https://github.com/timelesslounge/timelessis/issues/494) are still not solved; solved: [#192](https://github.com/timelesslounge/timelessis/issues/192), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#338](https://github.com/timelesslounge/timelessis/issues/338), [#421](https://github.com/timelesslounge/timelessis/issues/421).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#483](https://github.com/timelesslounge/timelessis/issues/483), [#494](https://github.com/timelesslounge/timelessis/issues/494), [#499](https://github.com/timelesslounge/timelessis/issues/499) are still not solved; solved: [#192](https://github.com/timelesslounge/timelessis/issues/192), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#338](https://github.com/timelesslounge/timelessis/issues/338), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#424](https://github.com/timelesslounge/timelessis/issues/424).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#338](https://github.com/timelesslounge/timelessis/issues/338), [#422](https://github.com/timelesslounge/timelessis/issues/422), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#483](https://github.com/timelesslounge/timelessis/issues/483), [#499](https://github.com/timelesslounge/timelessis/issues/499) are still not solved; solved: [#192](https://github.com/timelesslounge/timelessis/issues/192), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#424](https://github.com/timelesslounge/timelessis/issues/424), [#494](https://github.com/timelesslounge/timelessis/issues/494).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#338](https://github.com/timelesslounge/timelessis/issues/338), [#423](https://github.com/timelesslounge/timelessis/issues/423), [#483](https://github.com/timelesslounge/timelessis/issues/483), [#499](https://github.com/timelesslounge/timelessis/issues/499), [#530](https://github.com/timelesslounge/timelessis/issues/530) are still not solved; solved: [#192](https://github.com/timelesslounge/timelessis/issues/192), [#255](https://github.com/timelesslounge/timelessis/issues/255), [#421](https://github.com/timelesslounge/timelessis/issues/421), [#422](https://github.com/timelesslounge/timelessis/issues/422), [#424](https://github.com/timelesslounge/timelessis/issues/424), [#494](https://github.com/timelesslounge/timelessis/issues/494).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#unknown](), [#unknown]() are still not solved.
