### ISSUE TITLE
models.py:8-11: Continue implementation. Roles should...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#96]
The puzzle `9-4864baac` from #9 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/dea2fafb3b0bf14894100a5a067a83ce832221ca/roles/models.py#L8-L11

The puzzle was created by Krzysztof Krason on 01-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by krzyk** [comment]
@0crat waiting for review of PR #137

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #137  ([here](https://github.com/timelesslounge/timelessis/issues/96#issuecomment-461017113))

@krzyk There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@55d69b91-ec34-4bf1-baee-b9c4b56fbdad, thread: AsyncProc-6
com.zerocracy.farm.sync.SyncProject[76] java.lang.IllegalStateException: Failed to acquire "impediments.xml" in "CF9LG1YCA" in 2min: java.util.concurrent.locks.ReentrantLock@62e21b4b[Locked by thread BkParallel-7]
```

[0.40.15](https://github.com/zerocracy/farm): CID: [1807afd2-04ec-4c61-90a3-2030ccb48588](https://www.0crat.com/footprint/CF9LG1YCA/1807afd2-04ec-4c61-90a3-2030ccb48588), Type: "Register impediment"

**Comment by krzyk** [comment]
@0crat waiting for review of PR #137

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #137 ([here](https://github.com/timelesslounge/timelessis/issues/96#issuecomment-461057994))

@krzyk The impediment for [#96](https://github.com/timelesslounge/timelessis/issues/96) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0pdd** [comment]
The puzzle `9-4864baac` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#96](https://github.com/timelesslounge/timelessis/issues/96) is now out of scope

**Comment by ypshenychka** [comment]
@krzyk According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All commit messages have links to issues

All your commits in main PR are linked to another issue. Please confirm you'll try to avoid such mistake next time.

**Comment by krzyk** [comment]
@ypshenychka I confirm

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
