### ISSUE TITLE
models.py:61-63: Continue implementation as in #18. The...

### ISSUE THREAD

**Issue by 0pdd** [timelesslounge/timelessis#97]
The puzzle `43-07f6d407` from #43 has to be resolved: 

https://github.com/timelesslounge/timelessis/blob/f2662618a03c2b97da76947b9870d64d9a2c198d/schemetypes/models.py#L61-L63

The puzzle was created by Boris Kuzmic on 01-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by bkuzmic** [comment]
@0crat wait for finishing task #173. This will simplify creating all other views.

**Comment by 0crat** [comment]
> @0crat wait for finishing task #173. This will simplify creating all other views. ([here](https://github.com/timelesslounge/timelessis/issues/97#issuecomment-462308081))

@bkuzmic The impediment for [#97](https://github.com/timelesslounge/timelessis/issues/97) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0pdd** [comment]
The puzzle `43-07f6d407` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#386](https://github.com/timelesslounge/timelessis/issues/386) is still not solved.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#97](https://github.com/timelesslounge/timelessis/issues/97) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#386](https://github.com/timelesslounge/timelessis/issues/386), [#455](https://github.com/timelesslounge/timelessis/issues/455) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#455](https://github.com/timelesslounge/timelessis/issues/455) is still not solved; solved: [#386](https://github.com/timelesslounge/timelessis/issues/386).
